### ISSUE TITLE
Typos in "Import Failed View Details" text

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#1003]
Typos in "Import Failed View Details" text.

Implemented:
<img width="1247" alt="screen shot 2018-07-02 at 2 53 00 pm" src="https://user-images.githubusercontent.com/5589919/42186515-fdee089c-7e1a-11e8-8853-0a8ad2bd2ae6.png">

Design:
<img width="288" alt="screen shot 2018-07-02 at 5 11 48 pm" src="https://user-images.githubusercontent.com/5589919/42186542-0f7f544e-7e1b-11e8-86f1-fe3a8b48f08c.png">

Ought to be "Import failed.  View details"

Found in the following release:
```
$ rpm -qa | grep tendrl | sort
tendrl-api-1.6.3-20180626T110501.5a1c79e.noarch
tendrl-api-httpd-1.6.3-20180626T110501.5a1c79e.noarch
tendrl-commons-1.6.3-20180628T114340.d094568.noarch
tendrl-grafana-plugins-1.6.3-20180622T070617.1f84bc8.noarch
tendrl-grafana-selinux-1.5.4-20180227T085901.984600c.noarch
tendrl-monitoring-integration-1.6.3-20180622T070617.1f84bc8.noarch
tendrl-node-agent-1.6.3-20180618T083110.ba580e6.noarch
tendrl-notifier-1.6.3-20180618T083117.fd7bddb.noarch
tendrl-selinux-1.5.4-20180227T085901.984600c.noarch
tendrl-ui-1.6.3-20180625T085228.23f862a.noarch
```

@gnehapk @mbukatov @nthomas-redhat

**Comment by gnehapk** [comment]
@julienlim This has been fixed along with https://github.com/Tendrl/ui/pull/1002.

**Comment by julienlim** [comment]
This can be tracked also at https://bugzilla.redhat.com/show_bug.cgi?id=1597716.
