### ISSUE TITLE
Repository access rights

### ISSUE THREAD

**Issue by debloper** [Tendrl/ui#2]
The frontend engineering team has agreed to have shared r/w access to the repository, to ensure redundancy of available human resources for the necessary operations (primarily merging).

This does not mean, the team would directly commit/push to the upstream repo. It just merely means, a merge isn't blocked on a certain person's availability, among other things.

I'm requesting to add Karnan, Neha & me to have the R/W privileges on this repo.

GitHub allows pretty fine grained access control. We can achieve this by:
- Invite the users as org members
- Create a team "frontend"
- Add the frontend specific repos (this repo, website repo etc)
- Add the invited members as the members of the team
- Give the team Read and Write privileges (which will be applied on the added repos).

**Comment by sankarshanmukhopadhyay** [comment]
The creation of teams and such was planned for at a later stage. However, I understand how it could be useful to organize work pieces. Thus,

- team has been created
- repository has been added (not the website; that's a separate entity from the front end)
- privileges have been added
