### ISSUE TITLE
When a task fails because of a timeout, this fact is not communicated to the user

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ui#470]
When a task fails because of timeout, the root cause (timeout) is nowhere to be found and the user can't tell what went wrong. The scope of this issue is general and covers all tasks which could timeout. 

This has a significant impact on the cost of debugging problems.

## Version

On Tendrl Server machine:

```
# rpm -qa 'tendrl-*'
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
```

## Reproducer

1. Install Tendrl using tendrl-ansible (full cluster including server and storage nodes), but set `tendrl_gluster_provisioning_support` ansible variable to False so that no machine would be tagged as `provisioner/gluster`. 
2. Try to create gluster cluster via Tendrl web ui
3. See status of related *CreateCluster* task
4. Wait 10 minutes (for the task to timeout)
5. See status of related *CreateCluster* task again

## Actual Result

When the *CreateCluster* task is checked for the first time just after it's creation (as done in step 3), the task status is  "new":

![todo-issue 008 onlypage](https://user-images.githubusercontent.com/4759819/27545919-74b7a64e-5a91-11e7-9efe-3a9eef11340e.png)

Then when the task timeouts after some time, the status is just "failed":

![todo-issue 009](https://user-images.githubusercontent.com/4759819/27545924-77bf1304-5a91-11e7-9d71-f32facd39079.png)

## Expected Result

When the task timeouts, the web ui provides the following information:

* the task failed because of timeout and that the timeout is 10 minutes
* the reason of the timeout: there are no machines tagged with `provisioner/gluster` tag (in this particular case)

## Additional Information

The scope of this issue is general and covers all tasks which could timeout. QE validation should include check of some other task which could timeout.

Also note that since [actual time of the submission is not present on the task detail page](https://github.com/Tendrl/dashboard/issues/469), it's not immediately obvious how long is the task still in new state.

**Comment by sankarshanmukhopadhyay** [comment]
I would propose that this has essentially less to do with dashboard and possibly more around how the API service handles the failure to respond situation. Let's keep this in dashboard for the moment, but possibly bring this up for further discussions - instead of a spot fixing approach, we might need to take a framework like solution for this.

**Comment by r0h4n** [comment]
@anivargi @cloudbehl Every job has attribute "errors"  https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/job/__init__.py#L12

Please make use of that

**Comment by anivargi** [comment]
Fixed in https://github.com/Tendrl/api/pull/304

**Comment by mbukatov** [comment]
For the purposes of verification, reproducer needs to be updated, because the provisioner node is no longer configured by admin or tendrl-ansible, but auto selected by tendrl itself.

**Comment by mbukatov** [comment]
This is still valid, the root cause (timeout) is not shown in the task details, but an alert about the timeout is created. Unfortunately, the alert is shown in a way which provides no easy way for the admin to make sure which job was affected:

![screenshot_20171106_170651](https://user-images.githubusercontent.com/4759819/32450874-b054ae26-c315-11e7-9a51-49d2401360bf.png)


Using versions:

```
# rpm -qa | grep tendrl | sort
tendrl-api-1.5.4-20171102T145114.0783fcd.noarch
tendrl-api-httpd-1.5.4-20171102T145114.0783fcd.noarch
tendrl-commons-1.5.4-20171102T134746.79caec6.noarch
tendrl-grafana-plugins-1.5.4-20171102T143236.7680af0.noarch
tendrl-grafana-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-monitoring-integration-1.5.4-20171102T143236.7680af0.noarch
tendrl-node-agent-1.5.4-20171102T141515.472e4dd.noarch
tendrl-notifier-1.5.4-20171102T144015.3ded35b.noarch
tendrl-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-ui-1.5.4-20171102T160716.46234aa.noarch
```

**Comment by r0h4n** [comment]
@anivargi @gnehapk  Every job has attribute "errors" 

Please make use of that

**Comment by shtripat** [comment]
If a job gets timed out, the job messages get updated accordingly.

**Comment by gnehapk** [comment]
@mbukatov Logs are coming now in API response, if job fails because of timeout. Hence, closing the issue.
