### ISSUE TITLE
Codebase refresh for grafana integration

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/ui#486]
Since grafana is being introduced to serve as the monitoring dashboard (https://github.com/Tendrl/specifications/issues/168), the tendrl UI no longer needs to display all the graphs and metrics that were in the original designs. Many of the original designs have been implemented and currently exist in the master branch. Based on the new direction for the UI, and updated implementation would be required, which would only partly reuse the existing codebase. To address this, the current master needs to be branched into a legacy release and frozen. New master needs to then be initialised with only the codebase required from the legacy release.

**Comment by gnehapk** [comment]
Created a branch named [ui-legacy-code](https://github.com/Tendrl/ui/tree/ui-legacy-code) for pre-grafana UI code.
