### ISSUE TITLE
Delete User from Tendrl

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ui#508]
@julienlim Before deleting a user, it will be good to display a pop up which asks the user to confirm before deleting it(and the impacts the action have).  Please provide a UX design for it.

**Comment by mcarrano** [comment]
A delete confirmation dialog has been added to the flow for User Admin here: https://redhat.invisionapp.com/share/8QCOEVEY9

**Comment by julienlim** [comment]
@gnehapk Please see comment above.
