### ISSUE TITLE
Unable to see title of Import Cluster - Hosts Discovered list

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ui#529]

**Comment by julienlim** [comment]
![import window overlaping views2](https://user-images.githubusercontent.com/5589919/29757608-204c6b24-8b7b-11e7-8d2e-4d4b4b01bee0.png)

**Comment by gnehapk** [comment]
@julienlim I have tried on both Chrome(Version 60.0.3112.78) and Firefox(50.1.0) browsers and I am not able to reproduce this issue. Attaching the screenshots for the same.

![screenshot from 2017-08-28 11-53-52](https://user-images.githubusercontent.com/5517376/29761839-e1d680d2-8be8-11e7-90d1-bea23fd8e88f.png)

![screenshot from 2017-08-28 11-57-32](https://user-images.githubusercontent.com/5517376/29761846-e7dc0e66-8be8-11e7-8732-a1d99a0fe87f.png)

**Comment by gnehapk** [comment]
@julienlim Can you please confirm is it still reproducible on firefox and chrome browsers?

**Comment by julienlim** [comment]
@gnehapk The problem is no longer on Chrome Version 60.0.3112.113 (Official Build) (64-bit), but I still observe it as a problem on Firefox 52.3.0 (64-bit).

Below is the screenshot from Firefox:
![screen shot 2017-09-05 at 11 30 40 am](https://user-images.githubusercontent.com/5589919/30069265-49637d36-922e-11e7-930a-25c92b075f0f.png)

**Comment by julienlim** [comment]
Just verified that it still is a bug on Firefox based on today's build from master.
@gnehapk

**Comment by gnehapk** [comment]
@julienlim Its fixed now. Please verify.

**Comment by julienlim** [comment]
Confirming fix.

<img width="1280" alt="screen shot 2017-09-28 at 10 32 13 am" src="https://user-images.githubusercontent.com/5589919/30972376-61922d8c-a438-11e7-894e-034a91d4d7f9.png">

**Comment by gnehapk** [comment]
@julienlim closing it as its being fixed and verified.
