### ISSUE TITLE
Host List - what is a “Server Node?” -- Confusing terminology

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#532]
* For Tendrl Node, calling it a “Server Node” is strange since Server == Node == Host.  We should not use Node in the UI as it’s consistent with the Host reference used in place of nodes.  Instead, we might call the role “Tendrl Management” or “Tendrl Monitoring” to describe it’s function.  Tendrl in prefix is optional.

* For Gluster Node, calling it “Peer” may be confusing, i.e. is it a peer of the “Server Node?”  I suggest calling it “Gluster Peer.”

@gnehapk @Tendrl/tendrl-core @Tendrl/qe 

@rghatvis@redhat.com -- Please feel free to suggest other terms.

**Comment by julienlim** [comment]
<img width="1280" alt="host list" src="https://user-images.githubusercontent.com/5589919/29757898-4991bd16-8b7d-11e7-81ac-9601259b548c.png">

**Comment by mbukatov** [comment]
I would suggest to use name "Tendrl Server" here, as it would align with [Installation Guide](https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference) (where we call this machine **Tendrl Server** and have section called **Tendrl Server Installation**) and tendrl-ansible (where we have **tendrl-server** role).

@julienlim is **Tendrl Server** ok with you? I you prefer to call this machine differently (eg. **Tendrl Management**), we would need to coordinate across all components and do the rename during work for next milestone.

**Comment by julienlim** [comment]
@mbukatov "Tendrl Server" is okay, but to align the terminology, it should be "Tendrl Host" as we're using host throughout the UI (and other related products, e.g. old console too).

**Comment by cybernth** [comment]
"Tendrl Host" is bit confusing.
Since every one is okay with  "Tendrl Server", let us go ahead with that. @gnehapk

**Comment by gnehapk** [comment]
@julienlim @nthomas-redhat  Its fixed in tendrl-ui-1.5.2-20170919T120332.90b043e.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
@julienlim @nthomas-redhat  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
