### ISSUE TITLE
Hosts to bricks mapping in the hosts list view for gluster

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/ui#534]
[The hosts list view](https://redhat.invisionapp.com/share/2RCOE72PE#/screens/244735173) inside a cluster needs to scale to 128 hosts with 36 bricks each for milestone 3, with the eventual target being 60 bricks per host. Assuming that the bricks for the hosts are accessed by clicking on a host in the list, as either an expanded view or a pop-up view, it may easier to scale with host specific queries to fetch the brick information per host.

**Comment by brainfunked** [comment]
I've created a corresponding discussion at https://github.com/Tendrl/api/issues/249 to discuss the feasibility of a cluster specific host API endpoint.

**Comment by gnehapk** [comment]
@brainfunked Its implemented now. Hence, closing this issue.
