### ISSUE TITLE
cannot close left menu in Firefox

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ui#535]
If user open initial page it is not possible to close left menu.
Reproducer:
1. Open initial Tendrl page before import
2. clear all cache by Ctrl+F5 (Linux)
3. try to close left menu by clicking on button ```=``` in left upper corner

Workaround:
Click on any menu item in left menu and then it is possible to close left menu.

Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by a2batic** [comment]
@mkudlej, the issue has been fixed in tendrl-ui-1.5.2-20170927T130140.6bb4ee5.noarch.rpm, please verify.

**Comment by gnehapk** [comment]
@mkudlej  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
