### ISSUE TITLE
Save and Cancel buttons in Add user form

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#537]
Buttons for `Save` and `Cancel` in `Add user` form are not correctly styled. They overlap over the form and have variable distance from each other when the page is changing zoom or window size.

![829_scbuttons1](https://user-images.githubusercontent.com/22369801/29820575-3e8944fe-8cc5-11e7-81ea-de55c2e9d04d.png)

![829_scbuttons2](https://user-images.githubusercontent.com/22369801/29820583-41648c88-8cc5-11e7-865b-ddcb211a3d8a.png)

Tested with:
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@fbalak Fixed in tendrl-ui-1.5.1-20170830T055110.867cdc4.noarch.rpm build. Please verify it.

**Comment by cybernth** [comment]
@gnehapk , is this a firefox specific issue?
@fbalak , Can you verify whether this issue is fixed?

**Comment by gnehapk** [comment]
@nthomas-redhat its fixed for both  browsers - chrome and firefox.

**Comment by fbalak** [comment]
Seems ok.

Tested with:
tendrl-api-httpd-1.5.2-1.el7.centos.noarch
tendrl-commons-1.5.2-1.el7.centos.noarch
tendrl-api-1.5.2-1.el7.centos.noarch
tendrl-ui-1.5.2-1.el7.centos.noarch
tendrl-node-agent-1.5.2-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.2-1.el7.centos.noarch
tendrl-grafana-plugins-1.5.2-1.el7.centos.noarch
tendrl-notifier-1.5.2-1.el7.centos.noarch
Chromium 59.0.3071.104 64bit
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
