### ISSUE TITLE
Tasks page filter

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#539]
Filter in Admin/Tasks page should be aligned according to https://redhat.invisionapp.com/share/8N93NO7Q4#/screens/200318248 and spaced properly apart for easier readability and usability. When there is one task there should be label with `1 Task` instead of `1 Tasks`. Filter controls don’t seem to match PatternFly Filter control (https://www.patternfly.org/pattern-library/forms-and-controls/filter/#/overview)

![829_filter](https://user-images.githubusercontent.com/22369801/29826746-612fbb24-8cd8-11e7-820a-d3e5e47fbd7e.png)

Tested with:
```
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch
```

**Comment by gnehapk** [comment]
@fbalak Tested on both browser -Firefox and Chrome and works fine for me.

![screenshot from 2017-08-29 20-28-04](https://user-images.githubusercontent.com/5517376/29828026-4952a5a4-8cf9-11e7-9b95-baec873e22a0.png)

Can you please provide more details.

**Comment by fbalak** [comment]
Tested with `Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0` and `Chromium Version 59.0.3071.104 Fedora Project (64-bit)`

**Comment by gnehapk** [comment]
@fbalak Please verify this issue.

**Comment by fbalak** [comment]
Seems ok.
Tested with:
tendrl-api-httpd-1.5.2-1.el7.centos.noarch
tendrl-commons-1.5.2-1.el7.centos.noarch
tendrl-api-1.5.2-1.el7.centos.noarch
tendrl-ui-1.5.2-1.el7.centos.noarch
tendrl-node-agent-1.5.2-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.2-1.el7.centos.noarch
tendrl-grafana-plugins-1.5.2-1.el7.centos.noarch
tendrl-notifier-1.5.2-1.el7.centos.noarch
Chromium 59.0.3071.104 64bit
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
