### ISSUE TITLE
Multiple rows in the Cluster list for the same cluster

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#544]
I'm not sure how this is possible, but when my VPN dropped and I reconnected, my cluster list (which previously showed 1 cluster) is now showing that I have 4 clusters, but they are the same cluster being repeated 4 times with different Volume Profile (enabled/disabled) states!

<img width="1280" alt="screen shot 2017-08-31 at 9 30 11 am" src="https://user-images.githubusercontent.com/5589919/29925714-39f57b0e-8e2f-11e7-943a-5ea4e5812897.png">

In looking at the Import for each of the clusters shown, only the "enabled" for Volume Profile has the representative list.  The "disabled" ones show a subset of nodes in the cluster.

@gnehapk @Tendrl/tendrl-core @Tendrl/qe

**Comment by cloudbehl** [comment]
@julienlim can you share the API response for the cluster list.

**Comment by cloudbehl** [comment]
Steps to retrieve API response from a browser(Chrome):

1. In Chrome press F12 to open Developer's console.
2. Select the Network tab. This tab gives you the information about the requests fired from the browser.
3. Select a request(if not present just refresh the page) by clicking on the request name. There you can find the Header information for that request.
4. Click on Response tab inside Network Tab. This tab will give you the response for that Request.

**Comment by julienlim** [comment]
@cloudbehl I'm not exactly sure what header information you're asking for.  I took a screenshot of the Developer's console and cluster list -- see below:

<img width="1280" alt="screen shot 2017-08-31 at 1 50 55 pm" src="https://user-images.githubusercontent.com/5589919/29937475-b6f1ed12-8e53-11e7-84c9-67d7591c785b.png">

The response is: 
{"clusters":[{"sds_version":"3.11.0rc0","updated_at":"2017-08-30 19:11:09.968397+00:00","cluster_id":"3dfe9397-d7cf-4af0-bcab-c912afadd3ef","cluster_name":"gluster-1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","hash":"107623bd053a7f094dfcdf1342938cb3","integration_id":"3dfe9397-d7cf-4af0-bcab-c912afadd3ef","sds_name":"gluster","errors":[],"public_network":"","cluster_network":"","is_managed":"no","enable_volume_profiling":"yes","nodes":[{"status":"UP","sync_status":"done","tags":["detected_cluster/1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","tendrl/integration/gluster","tendrl/node_9a3129ef-4f9d-4e1c-b8fd-df00567a1056","tendrl/integration/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","provisioner/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","gluster/server","tendrl/node"],"updated_at":"2017-08-31 10:55:32.930922+00:00","fqdn":"glus2","hash":"dbf57b791e874ea2f0e912ff9c0f1eef","last_sync":"2017-08-31 10:55:30.450640+00:00","node_id":"9a3129ef-4f9d-4e1c-b8fd-df00567a1056","node_id":"9a3129ef-4f9d-4e1c-b8fd-df00567a1056"},{"fqdn":"glus3","hash":"2c0ea2ab77b9c5e3c53dd731291c93ce","last_sync":"2017-08-31 03:55:20.008922+00:00","node_id":"9f16586c-31fc-44b4-a221-b38fa4044579","status":"UP","sync_status":"done","tags":["detected_cluster/1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","tendrl/integration/gluster","tendrl/integration/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/node_9f16586c-31fc-44b4-a221-b38fa4044579","gluster/server","tendrl/node"],"updated_at":"2017-08-31 03:55:20.118457+00:00","node_id":"9f16586c-31fc-44b4-a221-b38fa4044579"},{"updated_at":"2017-08-31 17:50:29.991292+00:00","fqdn":"glus0","hash":"195dd56bcbc2119436009bf907e12525","last_sync":"2017-08-31 17:50:29.897294+00:00","node_id":"0090df53-a65c-4eed-85e8-5eae05cf47bb","status":"UP","sync_status":"done","tags":["detected_cluster/1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","tendrl/integration/gluster","tendrl/node_0090df53-a65c-4eed-85e8-5eae05cf47bb","tendrl/integration/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/central-store","gluster/server","provisioner/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/server","tendrl/monitor","tendrl/node"],"node_id":"0090df53-a65c-4eed-85e8-5eae05cf47bb"}]},{"sds_name":"gluster","sds_version":"3.11.0rc0","updated_at":"2017-08-31 08:27:38.270351+00:00","cluster_id":"b6fc3476-b6ce-4c6a-9589-1887512be9de","cluster_name":"gluster-1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","hash":"f4ce29f643e250d9425c87f8686f894b","integration_id":"b6fc3476-b6ce-4c6a-9589-1887512be9de","errors":[],"nodes":[{"sync_status":"done","tags":["detected_cluster/1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","tendrl/integration/gluster","tendrl/node_9a3129ef-4f9d-4e1c-b8fd-df00567a1056","tendrl/integration/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","provisioner/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","gluster/server","tendrl/node"],"updated_at":"2017-08-31 08:27:38.482125+00:00","fqdn":"glus2","hash":"25bf76e408f5b93f094269fa56464b69","last_sync":"2017-08-31 08:27:38.038848+00:00","node_id":"9a3129ef-4f9d-4e1c-b8fd-df00567a1056","status":"UP","node_id":"9a3129ef-4f9d-4e1c-b8fd-df00567a1056"}]},{"sds_version":"3.11.0rc0","updated_at":"2017-08-31 13:08:28.556842+00:00","cluster_id":"d2c1b3ae-e240-43e9-bc04-3706a8814de4","cluster_name":"gluster-1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","hash":"c5f00466d2dd8d3e4aa71616e3e005e2","integration_id":"d2c1b3ae-e240-43e9-bc04-3706a8814de4","sds_name":"gluster","errors":[],"nodes":[{"node_id":"0090df53-a65c-4eed-85e8-5eae05cf47bb","status":"UP","sync_status":"done","tags":["detected_cluster/1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","tendrl/integration/gluster","tendrl/node_0090df53-a65c-4eed-85e8-5eae05cf47bb","tendrl/integration/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/central-store","gluster/server","provisioner/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/server","tendrl/monitor","tendrl/node"],"updated_at":"2017-08-31 13:08:28.651642+00:00","fqdn":"glus0","hash":"f95ce91a81995802d6ef8c94e7279f46","last_sync":"2017-08-31 13:08:28.433125+00:00","node_id":"0090df53-a65c-4eed-85e8-5eae05cf47bb"}]},{"sds_name":"gluster","sds_version":"3.11.0rc0","updated_at":"2017-08-31 09:31:46.493623+00:00","cluster_id":"0f6ff8f1-8266-43f6-aab5-4ca54e0aaa00","cluster_name":"gluster-1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","hash":"681bd951d86b69c229cee6404a6447f4","integration_id":"0f6ff8f1-8266-43f6-aab5-4ca54e0aaa00","errors":[],"nodes":[{"node_id":"0090df53-a65c-4eed-85e8-5eae05cf47bb","status":"UP","sync_status":"done","tags":["detected_cluster/1d4429ac19be9e0482605c5e15f4591c31dda006a1094cdd77866f3138b5cdbb","tendrl/integration/gluster","tendrl/node_0090df53-a65c-4eed-85e8-5eae05cf47bb","tendrl/integration/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/central-store","gluster/server","provisioner/3dfe9397-d7cf-4af0-bcab-c912afadd3ef","tendrl/server","tendrl/monitor","tendrl/node"],"updated_at":"2017-08-31 09:31:46.569599+00:00","fqdn":"glus0","hash":"639684da6846341e1f3b4e9d7bbbaa3d","last_sync":"2017-08-31 09:31:46.377580+00:00","node_id":"0090df53-a65c-4eed-85e8-5eae05cf47bb"}]}]}

BTW, to open the Developer's console (on Mac), it's Cmd + Option + J.  F12 does not work.

**Comment by julienlim** [comment]
Also posted response at https://paste.fedoraproject.org/paste/AnnQb6fyOJgQRdMrDQIDzQ.

**Comment by gnehapk** [comment]
@r0h4n @nthomas-redhat @anivargi As per the response shared, the API response has four objects of cluster with same name but different cluster_id. Please look into it.

**Comment by r0h4n** [comment]
@julienlim 

- Did you complete setup of Gluster trusted storage pool on all the nodes and only  then run tendrl-ansible

Please provide details of how you setup Gluster and then Tendrl

**Comment by julienlim** [comment]
@r0h4n Yes Gluster properly setup on all the nodes following https://gluster.readthedocs.io/en/latest/Install-Guide/Install/ instructions.  I manually installed tendrl.

It had 1 cluster, but during a laptop OS update (nightly), it rebooted my computer and all my Vagrant/Virtualbox VM's were down.  After I brought up VirtualBox, there were then 4 clusters.

**Comment by cybernth** [comment]
@julienlim , to be more specific we want to know the sequecnce of steps you have done. Have you setup gluster cluster first and Installed tendrl after that or the other way around(install tendrl and then setup the gluster cluster)?

**Comment by julienlim** [comment]
@nthomas-redhat I believe I had gluster installed first and then installed tendrl.

**Comment by dahorak** [comment]
I'm in quite the same state now - I see one the same cluster on three rows. The first (which is the correct one) is imported and contains 4 nodes (which is correct). The rest two looks like ready to import and contains only one gluster node.
![screenshot](https://user-images.githubusercontent.com/4759779/30109254-ffcbe3e2-9305-11e7-8d64-558108588cc8.png)

I'm not sure how to reproduce it, but my sequence of steps was this:

1. Install and configure gluster cluster (enable relevant repos, install gluster packages, start glusterd service, create trusted storage pool, create one distributed replicated volume - via gdeploy)
1. Install and configure Tendrl server (using tendrl-ansible roles).
1. Install and configure tendrl-node-agents on gluster storage nodes (using tendrl-ansible).
_^^^ all this three steps was done by ansible playbooks and gdeploy configs from https://github.com/usmqe/usmqe-setup/_
1. Open Tendrl web UI - one gluster cluster is visible and ready to import.
1. Import the cluster via web UI. Everything seems ok, cluster was properly imported.
1. Walk through the available pages in Tendrl web UI (check the hosts, volumes, tasks etc.).
1. After few hours check the Clusters page of Tendrl web UI -> **three clusters with the same name are visible, one is imported, the remaining two looks like ready to import**

The API response to GET clusters call looks like this: https://gist.github.com/dahorak/eff122d18eae54046a22be164fb34311

**Comment by mbukatov** [comment]
This happened to me as well, tendrl received no special treatment from my side to reproduce it, it just happened while I was working on something else.

![screenshot_20170927_195624](https://user-images.githubusercontent.com/4759819/30929248-39e32fd6-a3be-11e7-930b-fcbf7724c976.png)

```
# rpm -qa | grep tendrl | sort
tendrl-api-1.5.2-20170921T125939.61d8945.noarch
tendrl-api-httpd-1.5.2-20170921T125939.61d8945.noarch
tendrl-commons-1.5.2-20170921T220225.c77a8fc.noarch
tendrl-grafana-plugins-1.5.2-20170926T072406.6f3f855.noarch
tendrl-monitoring-integration-1.5.2-20170926T072406.6f3f855.noarch
tendrl-node-agent-1.5.2-20170922T094941.ced9876.noarch
tendrl-notifier-1.5.2-20170922T082559.b6a2768.noarch
tendrl-ui-1.5.2-20170925T180704.770936f.noarch
```


```
# uptime
 17:58:41 up 1 day, 12:22,  1 user,  load average: 0.73, 0.83, 0.83
```

**Comment by gnehapk** [comment]
@nthomas-redhat @r0h4n @shtripat Please close this issue, if its fixed.

**Comment by shtripat** [comment]
Off late this issue I havent seen. Various changes around sds detect have resolved this issue. This could be closed I feel.

**Comment by gnehapk** [comment]
@julienlim Closing this issue. Please feel free to open, if you see this issue again.
