### ISSUE TITLE
Users Page: Typos on the filter and extra vertical bar

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#545]
Typos on the filter, extra vertical bar, and filter rounded edges (vs. straight edges)

Text changes:
* User id --> User ID
* Filter By username... --> Filter by User ID...

There does not need to be a vertical bar at the end of the filter

the User ID dropdown appears to have rounded edges, whereas per PatternFly, it should be straight-edged.  See https://www.patternfly.org/pattern-library/forms-and-controls/filter/#/overview

What's implemented:
<img width="276" alt="screen shot 2017-08-31 at 10 34 23 am" src="https://user-images.githubusercontent.com/5589919/29928889-11be50b2-8e38-11e7-945c-32a5c9265feb.png">

What's designed:
<img width="227" alt="screen shot 2017-08-31 at 10 34 14 am" src="https://user-images.githubusercontent.com/5589919/29928879-08db4f0e-8e38-11e7-9010-532a4809ce9b.png">

@gnehapk @Tendrl/qe @Tendrl/tendrl_frontend @mcarrano

**Comment by cybernth** [comment]
@gnehapk user id on the filter should be chnaged `User ID'
Please make this change

**Comment by gnehapk** [comment]
@julienlim @nthomas-redhat  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
