### ISSUE TITLE
Task "show" filter labels should not word wrap

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#546]
"In progress" should be on one line and not word wrap as there is sufficient white space to not warrant the word wrapping.  Positioning of the labels are also inconsistent, and should be to the right of the checkbox

* Implemented:
<img width="667" alt="screen shot 2017-08-31 at 12 10 29 pm" src="https://user-images.githubusercontent.com/5589919/29933487-c686d11a-8e45-11e7-8887-9fb096538a87.png">

* Design:
<img width="207" alt="screen shot 2017-08-31 at 12 10 19 pm" src="https://user-images.githubusercontent.com/5589919/29933482-c0abf040-8e45-11e7-9d16-fa4c20f3fd19.png">'

@gnehapk @Tendrl/qe @Tendrl/tendrl_frontend @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please verify this issue.

**Comment by julienlim** [comment]
Verified.
![screen shot 2017-09-18 at 4 19 07 pm](https://user-images.githubusercontent.com/5589919/30562628-1d6ed374-9c8d-11e7-8ef2-3733273228a1.png)
