### ISSUE TITLE
User management: Unneeded role and ambiguous user role labels

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#547]
- As the upcoming release will not include active management / provisioning capability, there is no need for a  “Normal User” role.
- Consider labeling “Limited User” to “Read-Only” as “Limited User” is a somewhat ambiguous term.

<img width="1280" alt="screen shot 2017-08-31 at 1 48 21 pm" src="https://user-images.githubusercontent.com/5589919/29937302-19ce575a-8e53-11e7-8998-1dcbc679f9ab.png">

@gnehapk @Tendrl/tendrl_frontend @Tendrl/qe @Tendrl/tendrl-core @mcarrano

**Comment by cybernth** [comment]
There are operations like enble/disable profiling is allowed and can be performed by 'Normal Users' and hence it is required

**Comment by mkudlej** [comment]
@julienlim Could you please change related design documents if this was already decided? Or at least add comment to design document that 'Normal user' will not be supported in upcoming version?

**Comment by mkudlej** [comment]
@nthomas-redhat Is there any list of permissions for these 3 user types?

**Comment by ltrilety** [comment]
@mkudlej actualy there is https://github.com/Tendrl/api/blob/master/docs/authorizaton.adoc

**Comment by julienlim** [comment]
@nthomas-redhat @mkudlej @japplewhite Please look at https://redhat.invisionapp.com/share/KNB25OEQT#/screens/226063802.  The user roles shown in the UI were not "Normal User" or "Limited User."  Instead they should be "Power User" and "Read-Only."

Regarding enabling/disabling storage profiling requiring the Power User / Normal User role, perhaps since it's a limited release, it would be better to say changing the text for what a Power User can do as there really is no provisioning capability.  Enable/Disable storage profiling is *not* provisioning (active management which means making changes to the actual storage that has been carved out), rather it is about adding enabling/disabling deeper monitoring of the volume.

**Comment by ltrilety** [comment]
BTW that's not just enable/disable profiling, but also possibility to import cluster. "Power user" can do that whilst "Read-Only" not.

**Comment by julienlim** [comment]
Related to https://github.com/Tendrl/ui/issues/564, where I've posed the question for details on the RBAC / authorization spec to get further clarification as to what read-only and power /normal user can actually do (or not).

**Comment by ltrilety** [comment]
I have related question to this. Am I right if I say that Grafana should look the same for all types of user roles? Should it be read only for all?

**Comment by cybernth** [comment]
> Related to #564, where I've posed the question for details on the RBAC / authorization spec to get further clarification as to what read-only and power /normal user can actually do (or not).

That is captured here --> https://github.com/Tendrl/api/blob/master/docs/authorizaton.adoc @julienlim

**Comment by julienlim** [comment]
@nthomas-redhat @anivargi @Tendrl/qe I looked at https://github.com/Tendrl/api/blob/master/docs/authorizaton.adoc and it's not specific enough and also mentioned my concerns in https://github.com/Tendrl/ui/issues/564.

**Comment by japplewhite** [comment]
does this mean that all users in this release will only need limited? Import being the one exception though right?

**Comment by gnehapk** [comment]
After discussion with @nthomas-redhat  and @brainfunked, its being decided that Admin, Normal and Read only users terminology will be followed in UI and API both.

**Comment by julienlim** [comment]
@nthomas-redhat @brainfunked @gnehapk @japplewhite @rghatvis@redhat.com @mcarrano @Tendrl/qe 
What is a "normal" user role?  I've seen many RBAC user-facing terminology, but "normal" user role is not common at all in the industry.

I've seen power user, privileged, monitoring, but "normal" is not normal.  I strongly recommend calling it "Power User" or "Privileged" or "Monitoring" or something more indicative of what the user role is serving.  Calling it "normal" is vague and anything but.

**Comment by mcarrano** [comment]
Mockups have been updated here with revised roles and instructional text: https://redhat.invisionapp.com/share/8QCOEVEY9

We decided to stick with Admin, Power User, and Read-Only.  The problem with the term "normal" is normal for who? The term does not reflect any particular level of privilege and becomes ambiguous, i.e. for an Admin, being an admin is his or her normal role.

**Comment by brainfunked** [comment]
> We decided to stick with Admin, Power User, and Read-Only. The problem with the term "normal" is normal for who? The term does not reflect any particular level of privilege and becomes ambiguous, i.e. for an Admin, being an admin is his or her normal role.

The same way, `power user` doesn't convey any specific meaning. It's especially confusing when there's no definition of 'normal' to compare against and in the presence of 'admin'. How is 'power user' different than 'admin'? Let me put it this way: in a context where there's admin and read-only, `normal` is much more normal than `power user`. If we need to be explicit, 'read-write' is extremely precise and explicit.

So, it's either 'normal' or 'read-write'. I think 'normal' sounds better to an end user, so we're using it.

**Comment by mkudlej** [comment]
@mcarrano @julienlim It seems that current implementation will not change. Could you please change design mockups according @brainfunked last comment?

**Comment by rghatvis** [comment]
In the generic RBAC realm, Power Users co-exist with Admin users with clear and pre-defined permissions. Admin is the almighty user, i.e, having total control of the system whereas a Power User is just a level below the Admin having permissions to most of the operations except the operations reserved for the Admin role. It's like the Admin user is the Pilot and the Power User is the co-pilot - second-in-command. If we talk about a "Normal" user, it can conjure many different things. The term "Normal" user has different connotations and can lead to ambiguity just like @julienlim and @mcarrano commented. In the interest of clarity and aligning our UI terms with the common RBAC terminology, I'd consider going with Power User. Other considerations could be Privileged or Standard user.
