### ISSUE TITLE
Import Cluster: Enable Volume Profiling - alignment issues, typos, and extra verbage should be in infotip

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#548]
- Checkbox trailing text not properly aligned with checkbox and also has typos.

- Text that should be in an infotip (and accessible through hovering on the “i” icon) is displayed making it look cluttered and overwhelming to the user.

- The column header "Release" should either be "Release" or "Version" -- the label should be consistent with the label used on the Cluster List (which currently shows "Version").  Please ensure consistency in both places. 

Current implementation:
<img width="1280" alt="screen shot 2017-08-31 at 9 49 04 am" src="https://user-images.githubusercontent.com/5589919/29940414-251e065a-8e5d-11e7-9c50-67ca3d7eaefe.png">

Suggested checkbox and text layout:
<img width="184" alt="screen shot 2017-08-31 at 3 02 34 pm" src="https://user-images.githubusercontent.com/5589919/29940543-9deee4be-8e5d-11e7-842d-cf7e84805329.png">

Suggest infotip:
<img width="188" alt="screen shot 2017-08-31 at 3 02 48 pm" src="https://user-images.githubusercontent.com/5589919/29940550-a3de18ea-8e5d-11e7-81d9-57f47ac0bb0b.png">

@gnehapk @Tendrl/tendrl_frontend @mcarrano @Tendrl/qe

**Comment by cybernth** [comment]
@julienlim , please verify this issue

**Comment by gnehapk** [comment]
@julienlim  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
