### ISSUE TITLE
RFE: Add another column for Release / Version to Host List

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#549]
Is it possible to add the Release (or Version) column to the Host List (before the Role column) -- like we do in the Import Cluster (host list)?

Import Cluster screenshot:
<img width="1280" alt="screen shot 2017-08-30 at 3 20 15 pm" src="https://user-images.githubusercontent.com/5589919/29940797-60569f6a-8e5e-11e7-8873-3a353ebb6210.png">

Host List screenshot:
<img width="1280" alt="screen shot 2017-08-30 at 3 19 03 pm" src="https://user-images.githubusercontent.com/5589919/29940778-5131a048-8e5e-11e7-872a-c860e66be901.png">

@gnehapk @Tendrl/tendrl-core @Tendrl/tendrl_frontend @Tendrl/qe

**Comment by gnehapk** [comment]
@julienlim Column version has been added to host list view. Hence, closing this issue. Please feel free to open, if you see any issue.
