### ISSUE TITLE
There is no error message in user edit page

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ui#552]
There is no error message if user cannot save form for edit user details (Admin -> Users -> Edit).

reproduce:
1. as admin create limited user *test_user*
2. log in as *test_user*
3. go to Admin -> Users -> click on "Edit" for *test_user*
4. change anything
5. click on save
6. there is no error message even if save request fails (403 forbidden)

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
httpd-2.4.6-45.el7.centos.4.x86_64
httpd-tools-2.4.6-45.el7.centos.4.x86_64
python-etcd-0.4.5-1.noarch
python-httplib2-0.7.7-3.el7.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by cybernth** [comment]
This issue is fixed
