### ISSUE TITLE
user cannot change password

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ui#553]
1. I've created user with limited access and I've logged in. This user cannot change his password. I think user with limited access can be able to change his password.
2.  I've created normal user and I've logged in. This user cannot change his password. I think normal user should be able to change his password.
3. Admin user can change his password at "Edit" user page

I think that there should be special dialog for user details (including changing password). this dialog will be available only for user. Design (even if it is for LDAP user and LDAP is not supported) is at https://redhat.invisionapp.com/share/KNB25OEQT#/screens/226063801

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
httpd-2.4.6-45.el7.centos.4.x86_64
httpd-tools-2.4.6-45.el7.centos.4.x86_64
python-etcd-0.4.5-1.noarch
python-httplib2-0.7.7-3.el7.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@mkudlej LDAP is not supported in this release.

**Comment by julienlim** [comment]
@Tendrl/qe @gnehapk The change password dialog (https://redhat.invisionapp.com/share/KNB25OEQT#/screens/226063801) is valid whether or not LDAP is supported or not.

Each user should be able to change his/her own password.

**Comment by a2batic** [comment]
PR: #576

**Comment by cybernth** [comment]
Read-only user still not able to change his settings, @a2batic

**Comment by a2batic** [comment]
@mkudlej, This has been fixed in latest builds. Please verify.

**Comment by gnehapk** [comment]
@mkudlej  Closing the issue as its been in pending verification state for long time. You can re-open, if required.

**Comment by julienlim** [comment]
Confirmed that I am able to change the user for a normal user.
