### ISSUE TITLE
lost user in user list after search

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ui#554]
Default admin user has empty *Last name*. If user searches users according *Last Name* and finally deletes all characters in filter input, Admin user is not in list even if Admin user (and all other users) should be visible in user list.

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
httpd-2.4.6-45.el7.centos.4.x86_64
httpd-tools-2.4.6-45.el7.centos.4.x86_64
python-etcd-0.4.5-1.noarch
python-httplib2-0.7.7-3.el7.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@mkudlej I am not able to reproduce this issue(deleting last name search text shows all the users in the list).  Can you please mention what text you have entered in filter input to search user by last name.

**Comment by mkudlej** [comment]
@gnehapk 
Please try to watch video zipped in [bug.zip](https://github.com/Tendrl/ui/files/1275069/bug.zip)

**Comment by cybernth** [comment]
Last name itself is removed from the UI. So this bug is not applicable at the moment. Closing the issue

**Comment by mkudlej** [comment]
@nthomas-redhat I still see last name in design document https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738633 Could you please add there comment?
