### ISSUE TITLE
cannot delete and disable user in UI

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ui#556]
There are options in design document https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738633 to delete and disable user. These 2 management actions are not implemented in UI.

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
httpd-2.4.6-45.el7.centos.4.x86_64
httpd-tools-2.4.6-45.el7.centos.4.x86_64
python-etcd-0.4.5-1.noarch
python-httplib2-0.7.7-3.el7.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by cybernth** [comment]
Closing this issue as this feature is planned for next milestone

**Comment by mkudlej** [comment]
@nthomas-redhat Could you please reopen this issue? It is true that this feature is missing in Tendrl 1.5.1. Persons interested in QE will close it once it will be implemented.
