### ISSUE TITLE
Read-only (limited) user

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#558]
A user with read-only (limited) role can open 'edit user' dialog and 'add user' dialog.
It will be better if those actions are not available for the user.

Moreover such user cannot edit or add another one as predicted however when he tries no error is displayed on UI. BTW when console is running API response is `403 Forbidden`.

**Comment by gnehapk** [comment]
@ltrilety 'Users' menu will only be available for admin users.  Role based access to various views/actions PR is merged in master and will be available in the upcoming release.

**Comment by cybernth** [comment]
Closing this issue as this feature is planned for next milestone

**Comment by mkudlej** [comment]
@nthomas-redhat Could you please reopen this issue? It is true that this feature is missing in Tendrl 1.5.1. Persons interested in QE will close it once it will be implemented.

**Comment by julienlim** [comment]
@nthomas-redhat @Tendrl/qe @Tendrl/tendrl_frontend This issue should not be closed but remain open until it can get verified by QE.
