### ISSUE TITLE
User name

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#559]
First and last name on UI is inauspicious choice when API takes only one name. This leads to several issues:

1.  User fills some string with spaces as name. E.g. 'a b' as first name 'c' as last name. A new user with name 'a b c' is created. Such user is displayed on UI as user with 'A' as first name and 'B' as last. Moreover this strings are used when user is edited. So without change the user cannot be saved.
2.  When API prints some error about name it's not clear if it's related to first name or the last one. Currently such error is not displayed at all, so it's not obvious why the user cannot be created or edited.

**Comment by gnehapk** [comment]
@anivargi UI needs separate property name mapped for both first and last name. Created issue for the same - https://github.com/Tendrl/api/issues/254

**Comment by cybernth** [comment]
We are going to have `name` on the UI which is in sync with API provides

**Comment by cybernth** [comment]
UI is inline with https://github.com/Tendrl/ui/issues/559#issuecomment-327440330
closing the issue

**Comment by mkudlej** [comment]
@nthomas-redhat I still see last name in design document https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738633 Could you please add there comment?
