### ISSUE TITLE
user last name

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#560]
When last name is not filled at all during user add UI puts 'undefined' string as last name.

**Comment by gnehapk** [comment]
@ltrilety Can you please paste the API response received for user list API.

**Comment by ltrilety** [comment]
@gnehapk 

data for POST users:
```
{"email":"test7@localhost.localdomain","username":"test7","name":"t undefined","role":"admin","email_notifications":"true"}
```
following GET users part where the user is:
```
{"email":"test7@localhost.localdomain" ,"username":"test7","name":"t undefined","role":"admin","email_notifications":"true"}
```

**Comment by gnehapk** [comment]
@ltrilety Its fixed and will be available in upcoming release.

**Comment by gnehapk** [comment]
@ltrilety Only 'Name" field is displayed on add user form in order to make it consistent with API.

**Comment by mkudlej** [comment]
@gnehapk But UI implementation was based on [design document for users ](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738633). I don't see any note in this design document that only one name will be supported. Could you please change design document or implement UI and API according it?

**Comment by cybernth** [comment]
This is inline with what is discussed in https://github.com/Tendrl/ui/issues/559
closing the issue.
