### ISSUE TITLE
general error for email issues

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#563]
When there is wrong mail filled during user add or edit. API says: `422 Unprocessable Entity: {"errors":{"email":["is invalid"]}}` but UI always says: 'Email is already taken. Please use different one.'

![email_ui_error](https://user-images.githubusercontent.com/22369834/30059985-b733060c-9241-11e7-8ef5-982bab45f47d.png)

**Comment by a2batic** [comment]
Thanks @ltrilety for reporting this, I will send a patch for it soon.

**Comment by cybernth** [comment]
This issue is fixed
