### ISSUE TITLE
read-only (limited) user cluster import

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#564]
User with read-only (limited) role can open cluster import dialog, even click on cluster import without any error. First sign that something is wrong is when the user tries to view the task progress. Then UI says: `No Task Detail Found Detected.`
API returns `403 Forbidden` error much earlier when user clicks on 'Import' button.
Correct behavior would be that cluster import is not available for the user at all.

**Comment by gnehapk** [comment]
@ltrilety Role based access to various views/actions [PR ](https://github.com/Tendrl/ui/pull/551)is merged in master and will be available in the upcoming release.

**Comment by cybernth** [comment]
Since this feature is planned for next milestone, closing this issue

**Comment by mkudlej** [comment]
@nthomas-redhat Could you please reopen this issue? It is true that this feature is missing in Tendrl 1.5.1. Persons interested in QE will close it once it will be implemented.

**Comment by julienlim** [comment]
@gnehapk @nthomas-redhat @Tendrl/tendrl-core @Tendrl/qe @japplewhite

Can someone point me to the spec (is it https://github.com/Tendrl/api/blob/master/docs/authorizaton.adoc which only lists roles and no details beyond the API calls permitted?) that details what the different user roles are permitted in a Gluster-only monitoring release?

E.g.

- admin - Full / all administrative access to all of Tendrl including admin (user, smtp, snmp) configuration.
- normal (power user) - Ability to to enable/disable volume profiling, import cluster, no admin configuration.
- limited (read-only) - Read-only access and can only launch dashboards and view details, but cannot enable/disable volume profiling, cannot import cluster.  This means that the enable/disable volume profiling button and import cluster button in the UI is now shown (vs. greyed out).

Where is this documented and listed?
