### ISSUE TITLE
Tendrl UI is not responsive

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#566]
@Tendrl/tendrl_frontend @Tendrl/qe 

The Tendrl UI is not responsive in that it is not able to adapt to any possible screen size.  When using Firefox version 52.3.0 (64-bit) to display the Cluster List, here is what I observed at initial launching of the Cluster page.  Some of the items to the far right were clobbered and overwriting each other.

![screen shot 2017-09-05 at 11 30 03 am](https://user-images.githubusercontent.com/5589919/30069465-cd23038a-922e-11e7-99ec-d367bd5f04d6.png)

**Comment by gnehapk** [comment]
@julienlim On chrome its working fine. Attaching the screenshot. 
![screenshot from 2017-09-05 21-33-31](https://user-images.githubusercontent.com/5517376/30070864-6d2ba172-9282-11e7-8590-a2ed085f4791.png)

The fix for firefox browser is in progress. This issue is already filed at https://github.com/Tendrl/ui/issues/536.

**Comment by gnehapk** [comment]
@julienlim  Fixed with tendrl-ui-1.5.2-20170925T180704.770936f.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
@julienlim  Closing the issue as its been in pending verification state for long time. You can re-open, if required.

**Comment by mkudlej** [comment]
I can verify this with
```
python2-gluster-4.0dev-0.181.git938adde.el7.centos.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
etcd-3.2.5-1.el7.x86_64
glusterfs-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-api-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-cli-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-geo-replication-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-libs-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-server-4.0dev-0.181.git938adde.el7.centos.x86_64
tendrl-ansible-1.5.3-20171006T142729.a80b984.noarch
tendrl-api-1.5.2-20171006T095605.71ea692.noarch
tendrl-api-httpd-1.5.2-20171006T095605.71ea692.noarch
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-grafana-plugins-1.5.2-20171009T072405.ed38272.noarch
tendrl-monitoring-integration-1.5.2-20171009T072405.ed38272.noarch
tendrl-node-agent-1.5.2-20171007T091926.0f2fd9b.noarch
tendrl-notifier-1.5.2-20171009T082044.7908e91.noarch
tendrl-ui-1.5.2-20171006T150811.7f212c5.noarch
```
