### ISSUE TITLE
Changing admin user role

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#568]
@gnehapk @Tendrl/tendrl-core @Tendrl/qe 

In the Tendrl UI, I was able to change the the user role of the admin from admin to normal user.  Is this something we want to permit?

![screen shot 2017-09-05 at 12 10 37 pm](https://user-images.githubusercontent.com/5589919/30071137-b5a26016-9233-11e7-84fc-1f854db41438.png)

**Comment by ltrilety** [comment]
I already created api issue for this https://github.com/Tendrl/api/issues/255

**Comment by cybernth** [comment]
We will not be supporting this. Closing the issue
