### ISSUE TITLE
Clicking on Task Details (from Tasks List) generates 404

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#577]
In the current Tendrl build I'm using (from master yesterday), whenever I want to look at Task Details of a given Task, I get a 404, and then when I click the back button (on the browser), it then shows the Task Details.  This happens for any task I want to see details for.  This behavior was observed on both Chrome and Firefox.

Here's the sequence of flow:

(1) In the Tasks List, I choose one of the Tasks to see details for:
![screen shot 2017-09-07 at 12 30 17 pm](https://user-images.githubusercontent.com/5589919/30174375-e0ca43d0-93c8-11e7-92c7-2089f1948199.png)

(2) Instead of showing Task Details, I get a 404:
![screen shot 2017-09-07 at 12 29 42 pm](https://user-images.githubusercontent.com/5589919/30174385-e924dc8e-93c8-11e7-9eca-c2c620de1591.png)

(3) Upon clicking on the back button (of the browser), it then correctly shows the task details:
![screen shot 2017-09-07 at 12 29 55 pm](https://user-images.githubusercontent.com/5589919/30174387-ebf1c0e4-93c8-11e7-8a40-79c3e7c574f3.png)

@Tendrl/qe @Tendrl/tendrl_frontend @gnehapk @mcarrano @Tendrl/tendrl-core

**Comment by gnehapk** [comment]
@julienlim Fixed. Will be available in the coming release.

**Comment by cybernth** [comment]
This issue is fixed
