### ISSUE TITLE
Notifications / Alerts in 2 places and have alerts that lack useful information

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#578]
There seems to be Alerts in the left navigation, and Notifications in the notification drawer coming from the top right common utilities area (banner far right).

Per the [UX design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738613), the alerts/notification (which are both the same thing) should be displayed in the notification drawer to be accessible at any time.

In the current implementation, the alerts/notifications seem to only appear when the Alerts menu is selected (from the left navigation bar).

At the moment, there seems to be alerts/notifications generated, but there is not sufficient useful information to know what the alert/notification is about.  I believe it should be brick1 is full on node ten3 (as I generated such a scenario twice), but as you can see from the screenshot, there's a bunch of informational message with no information to go along with it.

![screen shot 2017-09-07 at 12 41 58 pm](https://user-images.githubusercontent.com/5589919/30174939-c9e513b4-93ca-11e7-8737-ee07cf0d1063.png)

@gnehapk @Tendrl/tendrl_frontend @Tendrl/qe

**Comment by cybernth** [comment]
@GowthamShanmugam , This requires your immediate attention. Even on my setup I could see some info which really doesn't make any sense on Alert page.

**Comment by gnehapk** [comment]
@GowthamShanmugam Please close this issue, if it is solved.

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat @gnehapk we can close this issue it is fixed now, now alert page have all necessary information and alerts are also displayed in notifications panel also.

**Comment by gnehapk** [comment]
@julienlim Fixed in tendrl-ui-1.5.2-20170921T165116.b85723e.noarch.rpm. Please verify  and close the issue if its solved.

**Comment by gnehapk** [comment]
@julienlim  Closing this issue. This issue will be tracked on #663
