### ISSUE TITLE
Notifications (Alerts) are truncated and not readable

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#579]
Using the Notification drawer to access the Notifications/Alerts, I am unable to see the notification/alert message as it's truncated.  Furthermore, when you hover over the truncated message, the tooltip is truncated and not fully visible at any time.

See screenshots of the 2 notifications / alerts shown as well as what happens when I hover over them to trip and see the tooltip.

![screen shot 2017-09-07 at 1 29 10 pm](https://user-images.githubusercontent.com/5589919/30176754-912685a6-93d1-11e7-8fb8-33c99182eafa.png)

![screen shot 2017-09-07 at 1 29 04 pm](https://user-images.githubusercontent.com/5589919/30176757-938af0fc-93d1-11e7-8fa5-d8c7894dec36.png)

![screen shot 2017-09-07 at 1 29 07 pm](https://user-images.githubusercontent.com/5589919/30176763-9621a7d4-93d1-11e7-8280-d8c1e7e55b13.png)

I've included below the [UX design for the Notifications/Alerts drawer](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738613):
![screen shot 2017-09-07 at 1 32 16 pm](https://user-images.githubusercontent.com/5589919/30176751-8db3aa48-93d1-11e7-8438-57e850eb8d53.png)

@gnehapk @Tendrl/tendrl_frontend @Tendrl/qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please verify this issue.

**Comment by gnehapk** [comment]
@julienlim  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
