### ISSUE TITLE
Click on task(Admin->tasklist) re-direct to unavailable URL

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ui#583]
Click on task(Admin->tasklist) re-direct to http://<ip>/TendrlModule/

Workaround:
Click on `back` button will provide the expected result

**Comment by cybernth** [comment]
https://github.com/Tendrl/ui/issues/577

**Comment by julienlim** [comment]
@nthomas-redhat @gnehapk I just tried it with the latest build, and it's still giving me a 404.  Can we re-open this?
