### ISSUE TITLE
Click on `Grafana Dashboard` Button is not opening the dashboard

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ui#584]
This is observed on cluster list, host list, volume list, and cluster object details pages

**Comment by nthomas-redhat** [comment]
duplicate of https://github.com/Tendrl/ui/issues/577

**Comment by julienlim** [comment]
@nthomas-redhat The "Grafana Dashboard" seems to work from the host list.

**Comment by julienlim** [comment]
Related to https://github.com/Tendrl/ui/issues/587.

**Comment by cybernth** [comment]
This issue is fixed
