### ISSUE TITLE
Additional "Confirm password" input

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ui#586]
There is extra input *Confirm Password* in current implementation of *Edit User* and *Add User* forms 

which is not in [design](https://redhat.invisionapp.com/share/KNB25OEQT#/screens/226063805).
I think that design or implementation should change.
I understand 2 inputs for password is standard but it is not in design.

@julienlim Could you please comment here?
![bug_user_form](https://user-images.githubusercontent.com/5920442/30274000-cd0a0a3e-96fb-11e7-9602-740851865fb3.png)

**Comment by julienlim** [comment]
@mkudlej We do have a "Confirm Password" in the design -- see https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/252535083.

**Comment by gnehapk** [comment]
@mkudlej as this is already implemented and its as per UX design, closing this issue.
