### ISSUE TITLE
task progress - cancel button

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#589]
The `Cancel` button on the page with `View Task Progress` button doesn't make sense. It seems like it could cancel the current task (currently only import cluster) which is not true.

![cancel_button](https://user-images.githubusercontent.com/22369834/30276736-0e1919d4-9706-11e7-92cc-3baa7bd0ed9d.png)

Used packages:
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch

**Comment by julienlim** [comment]
@Tendrl/tendrl_frontend @Tendrl/qe @mcarrano 

If user is not able to "Cancel" a task, then we should not expose the "Cancel" button.

**Comment by mcarrano** [comment]
Agree. The design does not include a Cancel button for that reason.  See https://redhat.invisionapp.com/share/R88EUSGJK#/193148726_Import-Gluster_Cluster-_Completion

**Comment by gnehapk** [comment]
@julienlim @mcarrano Clicking cancel button takes user to cluster list page. So I feel, renaming "Cancel" to "Close" will be more clear to user. Any suggestions?

**Comment by julienlim** [comment]
@gnehapk I don't believe we'll need a "Close" button as we're not in a dialog, but in a page.  I think what you're asking is how do take the user back to the Clusters List view/page without using the breadcrumb or context switcher.  It's almost like a "Return to Clusters" type of action button you're hinting at.

@mcarrano Any suggestions on how best to label such a button?

**Comment by mcarrano** [comment]
I agree with @julienlim that having a Close button on a page that is not modal is non-standard. But I do see the problem now as I look at the wireframes. Since we removed the left navigation in the All Clusters view, there is not really a way to navigate back except for the breadcrumb. I think labeling the button simply as "Return" will work. So the two buttons are "View Task Details" and "Return" with task details being the primary button.

**Comment by gnehapk** [comment]
@mcarrano Closing the issue as its been in pending verification state for long time. You can re-open, if required.
