### ISSUE TITLE
Tendrl - Blank Slate (for Clusters List) showing wrong / old message

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#590]
When Tendrl UI first comes up (when there are no clusters present), it shows the following message:

No Clusters Detected.
If you have already cluster created or imported and still not see Clusters, make sure the Clusters are configured correctly.

<img width="1280" alt="screen shot 2017-09-08 at 2 49 27 pm" src="https://user-images.githubusercontent.com/5589919/30277355-89686c92-96d5-11e7-859f-1ba737c1bbbb.png">

This message is not ideal as users are not creating clusters with Tendrl but only importing them after tendrl-ansible completes successfully.

I suggest we change the message to the following:

No Clusters Detected
Ensure Tendrl server and node agents were successfully installed, and verify the Tendrl services are correctly configured.

Ideally, we should provide some guidance to users on how to verify the Tendrl services are correctly configured and other troubleshooting tips to help them get a cluster detected to show up in the Tendrl UI.

@gnehapk @Tendrl/tendrl_frontend @ltrilety @Tendrl/qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim  Fixed with tendrl-ui-1.5.2-20170921T165116.b85723e.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
@julienlim  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
