### ISSUE TITLE
Volume is not displaying in Tendrl UI but displays in Grafana dashboards

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#591]
I just deployed Tendrl from the latest master today, and I was able to import the cluster and see the dashboards.

What I was not able to see in the Tendrl UI was the volume (vol0) for my Gluster cluster; however, in Grafana, it did see the volume.

Tendrl UI - no volumes listed for the Gluster cluster:
![screen shot 2017-09-11 at 4 09 14 pm](https://user-images.githubusercontent.com/5589919/30294674-ee521e38-970b-11e7-9954-8979a7c691ac.png)

Grafana - volumes dashboard -- it shows vol0:
![screen shot 2017-09-11 at 4 09 44 pm](https://user-images.githubusercontent.com/5589919/30294684-f25cc64a-970b-11e7-9643-b1b77b3ab942.png)

Grafana - Gluster At-A-Glance -- it shows 1 volume, 2 bricks:
![screen shot 2017-09-11 at 4 10 02 pm](https://user-images.githubusercontent.com/5589919/30294687-f44c098e-970b-11e7-882e-2c68b2689399.png)

Note: The cluster name does not match (Tendrl UI vs. Grafana Dashboard) though they are of the same cluster.

@gnehapk @Tendrl/tendrl_frontend @Tendrl/tendrl-core @Tendrl/qe @nthomas-redhat

**Comment by julienlim** [comment]
I tried adding a gluster volume, and it did appear in Grafana but once again it did not appear in the Tendrl UI.

I also noted that the new volume added did not have volume profiling enabled (despite the cluster having it enabled) when it was added.  I had to manually enable it at the command line (since I couldn't see any of the volumes from the UI).
 
@gnehapk @Tendrl/tendrl_frontend @Tendrl/tendrl-core @Tendrl/qe @nthomas-redhat

**Comment by cybernth** [comment]
@shtripat, can you please check the volume profiling part?

**Comment by shtripat** [comment]
@julienlim can you share the setup details in a mail? I would try to check for errors why the profiling was not enabled for the volumes after import.

**Comment by shtripat** [comment]
@julienlim I tried creating a new volume in an already imported cluster and by next sync the profiling giot enabled for the volume. This is with latest master rpms and dont see the issue.

**Comment by julienlim** [comment]
@shtripat My setup is using vagrant with 3 nodes. 1 node = tendrl server, 2 nodes = gluster nodes.  On the gluster nodes (2 node cluster), I've 2 volumes: vol0 and vol1.  

Here's information about the volume:

[root@tnode1 ~]# gluster volume info
 
Volume Name: vol0
Type: Distribute
Volume ID: 021800ea-d00b-4805-9144-5c0f71e69dab
Status: Started
Snapshot Count: 0
Number of Bricks: 2
Transport-type: tcp
Bricks:
Brick1: tnode1:/bricks/brick1
Brick2: tnode2:/bricks/brick1
Options Reconfigured:
diagnostics.count-fop-hits: on
diagnostics.latency-measurement: on
nfs.disable: on
transport.address-family: inet
 
Volume Name: vol1
Type: Replicate
Volume ID: fbf82afd-363e-478f-b33e-f02e2339525c
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x (2 + 1) = 3
Transport-type: tcp
Bricks:
Brick1: tnode1:/bricks/brick2
Brick2: tnode2:/bricks/brick2
Brick3: tnode2:/bricks/brick3 (arbiter)
Options Reconfigured:
diagnostics.count-fop-hits: on
diagnostics.latency-measurement: on
transport.address-family: inet
nfs.disable: on

I followed install instructions per https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.1-(install-guide) using master.

When I did the initial install, I had only vol0 (distribute volume), but after import, volume did not show up in the Tendrl UI but showed up in Grafana.  After import, I added vol1 (arbiter volume), and again I did not see vol1 in the Tendrl UI but did see it in Grafana.  I enabled volume profiling on vol1 (since it wasn't enabled automatically).  I also did observe in Graphite, that the tree structure for vol0 and vol1 differed slightly.

See below -- specifically brick_count under the ..volumes.{volume_name} tree:
<img width="230" alt="screen shot 2017-09-13 at 11 29 16 am" src="https://user-images.githubusercontent.com/5589919/30386063-e7bf4548-9876-11e7-862a-f8256b16b6d5.png">

Despite that, it did seem to show the correct brick count in the Grafana dashboard.

If you need further information, please advise.

**Comment by cybernth** [comment]
@julienlim Please test this against released build and let us know.
Please not that there a known issue(not fixed yet) -->https://github.com/Tendrl/gluster-integration/issues/418

**Comment by julienlim** [comment]
@nthomas-redhat With the latest Milestone3 build (1.5.2), I can see the volume in the Tendrl UI but not any of the dashboards including the volume dashboard.

**Comment by cybernth** [comment]
@julienlim , I am closing this issue. There are already issues filed by you to track the issue mentioned at https://github.com/Tendrl/ui/issues/591#issuecomment-330344453
