### ISSUE TITLE
Cluster name / unique identifier don't match - ought to be same in both Tendrl UI and Grafana

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#593]
The cluster name / unique identifier differs in Tendrl UI vs. Grafana for the same cluster -- they ought to be the same.

Tendrl UI:
![screen shot 2017-09-11 at 4 15 57 pm](https://user-images.githubusercontent.com/5589919/30294872-a74914d2-970c-11e7-927f-80e115f47f00.png)

Grafana Dashboard:

![screen shot 2017-09-11 at 4 16 20 pm](https://user-images.githubusercontent.com/5589919/30294870-a548d776-970c-11e7-96dc-fee5549a1d57.png)

@gnehapk @Tendrl/qe @Tendrl/tendrl-core @Tendrl/tendrl_frontend

**Comment by cybernth** [comment]
This issue fixed.
