### ISSUE TITLE
There is "Launch Dashboard" link for hosts in Hosts page when cluster is not yet imported

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ui#610]
## Description

There is "Launch Dashboard" link for hosts in Hosts page when cluster is not yet imported, which is not expected behavior, as verified by @julienlim:

> if no cluster is imported,, the grafana dashboard button should not be visible

## Version

Latest snapshot build from master branch (if not fixed, it will be part of [upcoming 1.5.2 version](https://github.com/Tendrl/specifications/milestone/1)):

```
tendrl-ui-1.5.1-20170915T080405.521a085.noarch
```

## Steps to Reproduce

1. Prepare machines with GlusterFS cluster, including gluster volume (I used [nightly builds](https://github.com/usmqe/usmqe-setup/tree/master/roles/gluster-centos-repo) and [volume_usmqe_alpha_distrep_4x2.create.conf](https://github.com/usmqe/usmqe-setup/blob/master/gdeploy_config/volume_usmqe_alpha_distrep_4x2.create.conf))
2. Install Tendrl via tendrl-ansible there, using [snapshot builds](https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/)
3. Log into the Tendrl web interface as an admin user
4. Click on "Hosts" item in the menu to get to the Hosts page
5. See hosts listed on the page

## Actual Results

There are buttons linking to Grafana dashboard for all machines, even though the cluster hasn't been imported yet.

![screenshot_20170915_104856](https://user-images.githubusercontent.com/4759819/30474802-1f9faf4a-9a05-11e7-95fe-874f16e04a76.png)

To provide a complete reference here, the linked dashboard looks like this:

![screenshot_20170915_105052](https://user-images.githubusercontent.com/4759819/30474838-3e36ffbc-9a05-11e7-9992-68003973539a.png)

## Expected Results

There are no links to Grafana dashboard at this point. The links will be shown only later, when the cluster is imported.

**Comment by mbukatov** [comment]
This issue has been discussed during *Daily meeting of developers of Tendrl* on 2017-09-18: api may need to provide additional information for ui to check if hosts is part of imported cluster, @r0h4n and @gnehapk know the details.

**Comment by gnehapk** [comment]
@mbukatov  Its fixed in tendrl-ui-1.5.2-20170919T120332.90b043e.noarch.rpm. Please verify.

**Comment by mbukatov** [comment]
Verifying with `tendrl-ui-1.5.2-20170925T180704.770936f.noarch` and it works, Launch Dashboard buttons for hosts of not imported cluster are grey out and it's not possible to click on them

![screenshot_20170926_092546](https://user-images.githubusercontent.com/4759819/30847726-d52bfffe-a29c-11e7-8de8-9ec790cb1338.png)
