### ISSUE TITLE
Grafana dashboard launch from global host list fails

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ui#618]

**Comment by cloudbehl** [comment]
link: https://github.com/Tendrl/api/issues/288

**Comment by gnehapk** [comment]
@nthomas-redhat  Its fixed in tendrl-ui-1.5.2-20170919T120332.90b043e.noarch.rpm. Please verify.

**Comment by mbukatov** [comment]
This issue seems to be fixed in `tendrl-ui-1.5.2-20170919T122610.d9370be`
