### ISSUE TITLE
Grafana dashboard launch from cluster list fails

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#621]
Using the latest Milestone3 build, when I launch the dashboard from the Cluster list, I get a Dashboard not found.  Further looking in Grafana reveals that no cluster dashboard exists.

![screen shot 2017-09-18 at 4 01 53 pm](https://user-images.githubusercontent.com/5589919/30561951-d8477460-9c8a-11e7-98ab-3c4fc4fc11b4.png)

![screen shot 2017-09-18 at 4 02 39 pm](https://user-images.githubusercontent.com/5589919/30561958-daf7d056-9c8a-11e7-8e3a-31fb28d8465b.png)

@Tendrl/qe @Tendrl/tendrl_frontend @gnehapk @cloudbehl @mcarrano @nthomas-redhat

**Comment by cloudbehl** [comment]
@rishubhjain please have a look.

**Comment by rishubhjain** [comment]
@cloudbehl ack

**Comment by cybernth** [comment]
@julienlim Looks like a duplicate of https://github.com/Tendrl/ui/issues/623. Or is it different?

**Comment by rishubhjain** [comment]
@julienlim Have you signed into grafana using grafana admin id and password?

**Comment by julienlim** [comment]
@rishubhjain I did log into grafana with admin user id.  When we tried on another deployment without the admin user id, we saw the same results.

**Comment by rishubhjain** [comment]
@julienlim if possible can you logout from grafana and relaunch dashboard from cluster list? 
Or if possible can you provide me instance details?, I would like to debug the issue.

**Comment by cybernth** [comment]
As I mentioned at https://github.com/Tendrl/ui/issues/621#issuecomment-330438661 this is a duplicate of https://github.com/Tendrl/ui/issues/623 . I am closing this issue. please re-open if you think otherwise.
