### ISSUE TITLE
Cluster ID in Host List does not match the Cluster ID in the Cluster List or context switcher and text formatting inconsistent

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#622]
The Cluster ID in Host List does not match the Cluster ID in the Cluster List or context switcher even though there is only 1 (same) cluster:

![screen shot 2017-09-18 at 4 04 00 pm](https://user-images.githubusercontent.com/5589919/30562031-21301ba0-9c8b-11e7-92a9-6f8728c856b8.png)

![screen shot 2017-09-18 at 4 04 09 pm](https://user-images.githubusercontent.com/5589919/30562037-22b9455a-9c8b-11e7-89dc-2e6d6926797b.png)

![screen shot 2017-09-18 at 4 05 12 pm](https://user-images.githubusercontent.com/5589919/30562052-2dc2217e-9c8b-11e7-95f1-6fda0f7a3afd.png)

@Tendrl/qe @Tendrl/tendrl_frontend @nthomas-redhat @mcarrano

**Comment by gnehapk** [comment]
@julienlim Its fixed in tendrl-ui-1.5.2-20170919T120332.90b043e.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
@gnehapk @Tendrl/tendrl-qe @mcarrano 

Verified the match but displayed text formatting not consistent, i.e. some are half uppercase and half lowercase and some are completely in lowercase  The displayed text is not-consistent within Tendrl UI as well as then has to be consistent with how it's displayed in Grafana.

See screenshots from the context switcher, clusters list, hosts list, and grafana dashboard:
![screen shot 2017-10-03 at 2 52 25 pm](https://user-images.githubusercontent.com/5589919/31143240-abd0ae94-a84a-11e7-864a-0f65a767447e.png)

![screen shot 2017-10-03 at 2 43 19 pm](https://user-images.githubusercontent.com/5589919/31143250-b23c2fb0-a84a-11e7-8a2a-acf5e51ae6c2.png)

![screen shot 2017-10-03 at 2 52 38 pm](https://user-images.githubusercontent.com/5589919/31143259-b9de569e-a84a-11e7-9bf7-5532b4f5043d.png)

![screen shot 2017-10-03 at 2 52 50 pm](https://user-images.githubusercontent.com/5589919/31143266-c04305d4-a84a-11e7-8354-e89391ac701e.png)

![screen shot 2017-10-03 at 2 53 10 pm](https://user-images.githubusercontent.com/5589919/31143275-cb58f410-a84a-11e7-9ffe-1f5632307d7b.png)

**Comment by a2batic** [comment]
@julienlim, Fixed with tendrl-ui-1.5.2-20171010T124450.4044474.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
This issue appears to have been resolved.

![screen shot 2017-10-24 at 4 09 26 pm](https://user-images.githubusercontent.com/5589919/31965577-c68d3680-b8d5-11e7-9ef6-abbae543d5d6.png)

![screen shot 2017-10-24 at 4 09 36 pm](https://user-images.githubusercontent.com/5589919/31965580-c9541d52-b8d5-11e7-98bc-97c2ecfbe49a.png)
