### ISSUE TITLE
Grafana dashboards fail to launch from Tendrl UI

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#623]
None of the dashboards (cluster, host, volume, brick) launch to a dashboard that is working in Grafana.  

![screen shot 2017-09-18 at 4 07 22 pm](https://user-images.githubusercontent.com/5589919/30562184-8f5cedf6-9c8b-11e7-90a9-7f63657c391e.png)

In fact, they all seem to  point to Not Found in Grafana.  Also, all the canned dashboards (host, volume, bricks... cluster one is missing) in Grafana don't seem to contain any of the default dashboards that I expected.

![screen shot 2017-09-18 at 4 09 18 pm](https://user-images.githubusercontent.com/5589919/30562246-c1985490-9c8b-11e7-8b1b-19bbe9336a8e.png)

![screen shot 2017-09-18 at 4 09 37 pm](https://user-images.githubusercontent.com/5589919/30562263-cab1520c-9c8b-11e7-8f32-00c0055eafcb.png)

![screen shot 2017-09-18 at 4 09 55 pm](https://user-images.githubusercontent.com/5589919/30562275-d4fdc56a-9c8b-11e7-8a64-4f6fcfd4ad0f.png)

@gnehapk @Tendrl/tendrl_frontend @Tendrl/qe @nthomas-redhat @cloudbehl @anivargi

**Comment by cybernth** [comment]
@julienlim , DId you start the tendrl-monitoring-integration successfully?
Cluster imported successfully?
I would like to have a look at your setup.Seems to me that the whole thing is not setup properly. I will have a look and let you know.

**Comment by cybernth** [comment]
One more question- Are you able to launch the dashboards directly http://<IP>:3000 ?

**Comment by anmolbabu** [comment]
I would also like to know the 
1. o/p of service collectd status -l on all nodes
2. /var/log/messages
If no errors in 1 and 2 and collectd is down,
3. Contents of every file in /etc/collectd.d/

**Comment by mbukatov** [comment]
AI for @mbukatov: review this on cluster set up with tendrl-ansible and post updates (as discussed on *Daily meeting of developers of Tendrl*).

**Comment by rishubhjain** [comment]
@julienlim Have you signed into grafana using grafana admin id and password?

**Comment by mbukatov** [comment]
@julienlim I have installed Tendrl from snapshot builds (master branch) using tendrl-ansible (work in progress branch issue_34) and I don't see grafana dashboard broken as much as shown in this issue, that said, I noticed another issue related to linking: https://github.com/Tendrl/ui/issues/625

**Comment by julienlim** [comment]
@nthomas-redhat 

(1) tendrl-monitoring-integration did start successfully and is running.

root     25305     1 11 18:38 ?        00:15:41 /usr/bin/python /usr/bin/tendrl-monitoring-integration

(2) Cluster did import successfully

(3) I can launch http://172.28.128.4:3000/ with no problem, but the problem is that I don’t get the dashboards as expected.  I get something else (see screenshots attached grafana screenshots above with the black theme)

**Comment by julienlim** [comment]
@anmolbabu 

(1) “collectd status -l” does not appear to be valid but I ran the following instead:

[root@node1 gluster-integration]# collectd
plugin_load: plugin "python" successfully loaded.
plugin_load: plugin "exec" successfully loaded.
plugin_load: plugin "threshold" successfully loaded.
plugin_load: plugin "unixsock" successfully loaded.
plugin_load: plugin "aggregation" successfully loaded.
plugin_load: plugin "cpu" successfully loaded.
plugin_load: plugin "write_graphite" successfully loaded.
plugin_load: plugin "disk" successfully loaded.
plugin_load: plugin "ping" successfully loaded.
plugin_load: plugin "memory" successfully loaded.
plugin_load: plugin "df" successfully loaded.
plugin_load: plugin "interface" successfully loaded.
plugin_load: plugin "swap" successfully loaded.

(20 /var/log/messages

[root@node1 gluster-integration]# tail -100 /var/log/messages | grep tendrl
Sep 18 21:03:19 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:19 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:19.693253+00:00", "caller": {"function": "save", "line_no": 114, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Writing /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Bricks/all/node1/bricks_brick1/mount_opts to "}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "0df0ec73-80e1-4953-bdc1-83aee7a48cf4"}
Sep 18 21:03:19 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:19 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:19 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:19 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:19 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:19.698769+00:00", "caller": {"function": "save", "line_no": 114, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Writing /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Bricks/all/node1/bricks_brick1/sequence_number to 1"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "a747c68b-1426-4d10-b0a3-1b573d23cb2b"}
Sep 18 21:03:19 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:19 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:19 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:19 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:19 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:19.704429+00:00", "caller": {"function": "load_definition", "line_no": 39, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Load definitions (.yml) for namespace.gluster.objects.ClientConnection"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "987e957a-893e-417c-82d3-ef777d1ec9f9"}
Sep 18 21:03:19 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:19 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:19 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:19 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:19 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:19.712449+00:00", "caller": {"function": "load_definition", "line_no": 39, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Load definitions (.yml) for namespace.gluster.objects.ClientConnection"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "a873fadc-5678-423f-a29b-4c7364063dd9"}
Sep 18 21:03:19 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:19 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:19 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:19 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:19 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:19 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:19.721032+00:00", "caller": {"function": "load_definition", "line_no": 39, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Load definitions (.yml) for namespace.gluster.objects.ClientConnection"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "a0414761-1a0a-4dae-947c-a259146ffe58"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.029005+00:00", "caller": {"function": "load_definition", "line_no": 39, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Load definitions (.yml) for namespace.gluster.objects.VolumeOptions"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "95c64228-9d41-4245-a311-86ca37885380"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.036985+00:00", "caller": {"function": "load_definition", "line_no": 39, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Load definitions (.yml) for namespace.gluster.objects.VolumeOptions"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "09d39733-dc8d-450f-92c3-8e5d698ad8c5"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.037826+00:00", "caller": {"function": "load", "line_no": 183, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Reading /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/vol_id"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "61a81fef-fb58-4b0c-bc70-c306ce4248d4"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.045552+00:00", "caller": {"function": "load", "line_no": 183, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Reading /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/options/diagnostics.latency-measurement"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "0bf6eaf1-b972-41a3-ba35-db0c4daaeaf7"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.066791+00:00", "caller": {"function": "load", "line_no": 183, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Reading /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/options/diagnostics.count-fop-hits"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "4f072569-c2be-4c65-ad7f-941c3fdb82a3"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.073780+00:00", "caller": {"function": "load", "line_no": 183, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Reading /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/options/transport.address-family"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "4ce7ec53-02dc-4fca-9cb3-21c31d933ed5"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.081497+00:00", "caller": {"function": "load", "line_no": 183, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Reading /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/options/nfs.disable"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "f45dffd2-6317-49d5-8e20-9b0f374c059a"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.086617+00:00", "caller": {"function": "save", "line_no": 114, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Writing /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/vol_id to e5701b48-8391-4eb1-a661-27ca51e633dc"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "7d40773f-d4d4-463c-8a29-659abbcc3514"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.091646+00:00", "caller": {"function": "save", "line_no": 114, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Writing /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/hash to 4a7a511c75d3327e792c0657141c8131"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "043bc487-93a3-4609-9c39-d82a6041e256"}
Sep 18 21:03:20 node1 tendrl-gluster-integration: Traceback (most recent call last):
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 37, in _write
Sep 18 21:03:20 node1 tendrl-gluster-integration: self.sock.connect(self.socket_path)
Sep 18 21:03:20 node1 tendrl-gluster-integration: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 349, in connect
Sep 18 21:03:20 node1 tendrl-gluster-integration: raise error(result, strerror(result))
Sep 18 21:03:20 node1 tendrl-gluster-integration: error: [Errno 2] No such file or directory
Sep 18 21:03:20 node1 tendrl-gluster-integration: Unable to pass the message into socket.{"publisher": "gluster_integration", "job_id": null, "timestamp": "2017-09-18T21:03:20.096660+00:00", "caller": {"function": "save", "line_no": 114, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Writing /clusters/854e5925-8515-4aca-b087-8551cbe3c486/Volumes/e5701b48-8391-4eb1-a661-27ca51e633dc/updated_at to 2017-09-18 21:03:20.086447+00:00"}, "priority": "debug", "parent_id": null, "node_id": "dfe740c1-ddab-4d8e-97ef-237b7c1ee47f", "cluster_id": null, "flow_id": null, "message_id": "ab5247e4-d1e9-439a-af21-9bc88bb245d0"}

(3) 	Contents of every file in /etc/collectd.d/

[root@node1 collectd.d]# ls
cpu.conf     
disk.conf     
memory.conf       
network.conf  
swap.conf                             
tendrl_gluster.conf
dbpush.conf  
latency.conf  
mount_point.conf  
ping.conf     
tendrl_gluster_brick_disk_stats.conf

=== cpu.conf
LoadPlugin cpu

<Plugin cpu>
  ValuesPercentage true
  ReportByCpu false
</Plugin>

=== disk.conf
LoadPlugin disk

=== memory.conf
LoadPlugin memory

<Plugin "memory">
  ValuesPercentage true
</Plugin>

<Plugin "aggregation">
  <Aggregation>
    Plugin "memory"
    Type "memory"

    GroupBy "Host"

    CalculateSum true
  </Aggregation>
</Plugin>

=== network.conf 
LoadPlugin interface

<Plugin "interface">
  Interface "lo"
</Plugin>

=== swap.conf
LoadPlugin swap

<Plugin "swap">
  ValuesPercentage true
  ReportBytes true
  ValuesAbsolute true
</Plugin>

<Plugin "aggregation">
  <Aggregation>
    Plugin "swap"
    Type "swap"

    GroupBy "Host"

    CalculateSum true
  </Aggregation>
</Plugin>

=== dbpush.conf 
::::::::::::::
dbpush.conf
::::::::::::::
LoadPlugin "write_graphite"

<Plugin write_graphite>
    <Node "node1">
        Host "172.28.128.4"
        Port "2003"
        Protocol "tcp"
        LogSendErrors true
        Prefix "tendrl.clusters.854e5925-8515-4aca-b087-8551cbe3c486.nodes."
        StoreRates true
        AlwaysAppendDS false
        EscapeCharacter "_"
    </Node>
</Plugin>

::::::::::::::
disk.conf
::::::::::::::
LoadPlugin disk

=== tendrl_gluster.conf
::::::::::::::
tendrl_gluster_brick_disk_stats.conf
::::::::::::::
<Plugin "python">
    ModulePath "/usr/lib64/collectd/gluster"

    Import "tendrl_gluster_brick_disk_stats"

    <Module "tendrl_gluster_brick_disk_stats">
        integration_id "854e5925-8515-4aca-b087-8551cbe3c486"
        graphite_host "172.28.128.4"
        graphite_port "2003"
        peer_name "node1"
        provisioner False
        etcd_host "172.28.128.4"
        etcd_port 2379
        
            etcd_username ""
            etcd_password ""
        
        
    </Module>
</Plugin>
::::::::::::::
tendrl_gluster.conf
::::::::::::::
<Plugin "python">
    ModulePath "/usr/lib64/collectd/gluster"

    Import "tendrl_gluster"

    <Module "tendrl_gluster">
        integration_id "854e5925-8515-4aca-b087-8551cbe3c486"
        graphite_host "172.28.128.4"
        graphite_port "2003"
        peer_name "node1"
        provisioner False
    </Module>
</Plugin>

=== latency.conf
LoadPlugin "ping"

<Plugin "ping">
  Host "172.28.128.4"
  Interval 5
</Plugin>

=== mount_point.conf
LoadPlugin df

<Plugin "df">
  ValuesPercentage true
  IgnoreSelected false
  ReportInodes true
</Plugin>

=== ping.conf
LoadPlugin ping

=== tendrl_gluster_brick_disk_stats.conf
<Plugin "python">
    ModulePath "/usr/lib64/collectd/gluster"

    Import "tendrl_gluster_brick_disk_stats"

    <Module "tendrl_gluster_brick_disk_stats">
        integration_id "854e5925-8515-4aca-b087-8551cbe3c486"
        graphite_host "172.28.128.4"
        graphite_port "2003"
        peer_name "node1"
        provisioner False
        etcd_host "172.28.128.4"
        etcd_port 2379
        
            etcd_username ""
            etcd_password ""
        
        
    </Module>
</Plugin>

**Comment by julienlim** [comment]
@rishubhjain

Yes I did sign into grafana as admin

**Comment by cybernth** [comment]
@julienlim, Since @mbukatov and the devs are able to bring up the setup, I don't see this as an issue. I think this is happening because the environment is not setup appropriately. Please use tendrl-ansible(when available) for installation and update here.

**Comment by gnehapk** [comment]
@julienlim  Closing the issue as its been in pending verification state for long time. You can re-open, if required.
