### ISSUE TITLE
Inconsistent behavior in how we see object details

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#627]
(1) For a task, we click on the Task name (hyperlink text in blue per PatternFly), and see task (object) details in another page.  This is as expected and per design.

![screen shot 2017-09-18 at 4 19 07 pm](https://user-images.githubusercontent.com/5589919/30606230-fab4a770-9d3e-11e7-959b-c2b64d59aec0.png)

(2) For a cluster, the cluster name is in blue (for hyperlinking) but is not clickable to see cluster (object) details.  Rather, you have to click on the “Cluster Details” button in order to see cluster details in another page.  The preferred behavior is to click on the cluster name to see cluster (object) details and not have a button to do so (which adds clutter and noise) to the UI.

![screen shot 2017-09-18 at 4 05 12 pm](https://user-images.githubusercontent.com/5589919/30606217-ef951df2-9d3e-11e7-890b-af186858d9d5.png)

(3) For a host, the host name is in blue for (hyperlinking per PatternFly) but is not clickable to see host (object) details.  Rather, you have to click on the “Host Details” button in order to see host details.

![screen shot 2017-09-18 at 3 17 50 pm](https://user-images.githubusercontent.com/5589919/30606249-0e2238f4-9d3f-11e7-8e6a-3562dfcd1224.png)

(4) For a volume, the volume name should be clickable and in blue (when hovering over it).  When volume name is clicked on, you should see volume (object) details vs.. using the “Volume Details” button in order to see volume details.

![screen shot 2017-09-18 at 3 18 29 pm](https://user-images.githubusercontent.com/5589919/30606256-17222fb8-9d3f-11e7-908e-e805729320b7.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim As import and launch dashboard actions are triggered by buttons, so to make the behavior consistent across all the pages, we decided to go ahead with buttons only instead of clicking some tasks by link and some by buttons. 
Will add buttons on task list page too and remove the color from the names of all the objects.

**Comment by julienlim** [comment]
@mcarrano FYI.

**Comment by gnehapk** [comment]
@mcarrano @julienlim Fixed with tendrl-ui-1.5.2-20170921T165116.b85723e.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
@mcarrano @julienlim Closing the issue as its been in pending verification state for long time. You can re-open, if required.
