### ISSUE TITLE
Admin area should be launched from the utilities in the top right (and not the left navigation bar)

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#628]
User management (Admin) area should be launched from the top right utilities area.  See https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738612.

![screen shot 2017-09-19 at 2 57 40 pm](https://user-images.githubusercontent.com/5589919/30610052-14e9f97c-9d4b-11e7-812e-b2c156b8b0cd.png)

Design: 

![screen shot 2017-09-19 at 2 59 16 pm](https://user-images.githubusercontent.com/5589919/30610079-242f7498-9d4b-11e7-9c48-ceccb55d2a11.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim As this is implemented in concept b design changes and present in master. Hence, closing it. Please reopen if you see any issue.
