### ISSUE TITLE
UI Issues with Notification Drawer

### ISSUE THREAD

**Issue by mcarrano** [Tendrl/ui#629]
There are two minor issues with the implementation of the Tendrl notification drawer:

1) The caret to the left of the heading "Notifications" does nothing when clicked. If there is only one panel for notifications as per the current design, this control is unnecessary and should be removed as there is no need to expand of collapse the list.

The notifications drawer is missing a close ("X") button in the upper right to close it.  The drawer can only be closed by clicking on the bell icon, however this may not be obvious to all users.

![screen shot 2017-09-19 at 4 30 02 pm](https://user-images.githubusercontent.com/6619860/30614162-7d73ee6e-9d58-11e7-80af-3fefbee3022f.png)

**Comment by gnehapk** [comment]
@mcarrano Caret icon on left hides the list of notification list when notifications are present. We have followed the mockup provided at https://redhat.invisionapp.com/share/8N93NO7Q4#/screens/200318251. 
Will update the UI as per your suggestions. Thanks.

**Comment by mcarrano** [comment]
@gnehapk The mockup you reference is for the original console design where both tasks and alerts were to be shown in the drawer, so the panels could work like an accordion to shown one at a time. If we will only show alerts, this toggle is not needed. This link shows a more recent mockup https://redhat.invisionapp.com/share/8QCOEVEY9#/244738613_Alerts_Drawer  But I see that it is still missing the close button (that was my oversight) so I will fix that. You can also see details of the notification drawer pattern on PatternFly here http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design

@julienlim FYI

**Comment by a2batic** [comment]
@mcarrano, Thanks for adding the link. Will remove the toggle icon and add a close icon button for the notification drawer

**Comment by gnehapk** [comment]
@mcarrano Fixed with tendrl-ui-1.5.2-20170921T165116.b85723e.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
@gnehapk Is it possible to make the Notification drawer wider so the messages don't truncate?  See below.  Since the messages are not clickable to see a tooltip or details, widening might help since there's no way to tell what the alert is at the moment and on which node or device the alert occurred on.

![screen shot 2017-10-02 at 2 37 22 pm](https://user-images.githubusercontent.com/5589919/31094721-1fd4fca4-a784-11e7-97ea-af87d8e25699.png)

**Comment by gnehapk** [comment]
@mcarrano Closing the issue as its been in pending verification state for long time. You can re-open, if required.

@julienlim Widening the notification drawer issue will be handled along with #663
