### ISSUE TITLE
Task Details: Scroll Events so most recent are always in view

### ISSUE THREAD

**Issue by mcarrano** [Tendrl/ui#630]
In the Task Details screen. most recent events are added to the bottom of the Events list, however the list is always shown starting from the top so important messaging is easily missed unless the user manually scrolls.  In the example below, you can see that the task failed, but failure events/messages are not visible.

![screen shot 2017-09-19 at 4 47 55 pm](https://user-images.githubusercontent.com/6619860/30614824-cc5d5ab8-9d5a-11e7-9906-c25eeec4db4b.png)

The list should automatically scroll to the bottom by default so the most recent events are visible as they are added to the list.

**Comment by a2batic** [comment]
@mcarrano  Its fixed in tendrl-ui-1.5.2-20170920T073234.f7b6ad2.noarch.rpm. Please verify. The event list now is sorted according to date, so that the most recent events come on the top.

**Comment by gnehapk** [comment]
@mcarrano Closing the issue as its been in pending verification state for long time. You can re-open, if required.
