### ISSUE TITLE
Filter controls don’t seem to match PatternFly Filter control

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ui#638]
Filter controls don’t seem to match PatternFly Filter control (https://www.patternfly.org/pattern-library/forms-and-controls/filter/#/overview)

**Comment by cloudbehl** [comment]
A filter is not readily available in a patternfly new build. So we need to update the patternfly packages in order to make the filter work and the UI needs to be tested very well with the new version. 

"angular-patternfly": "~4.11.0",
"patternfly": "~3.27.5",

We tried updating the version, few functionalities were hampered eg. bootstrap datepicker(removed in new version). So, it will be good idea to take it in next development cycle. @nthomas-redhat

**Comment by a2batic** [comment]
@cloudbehl @gnehapk, the bug has been fixed with tendrl-ui-1.5.4-20171107T133229.ed61125.noarch.rpm (latest master build). Please verify.

**Comment by gnehapk** [comment]
Closing this issue, as its been opened for quite long time. Please feel free to reopen if the issue still persists.
