### ISSUE TITLE
Problem with responsiveness for Hosts list in Clusters page

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ui#640]
## Description

There is a responsiveness problem for *Hosts list* tab of cluster item in Clusters page. When the screen is too narrow, host names are either one character long or disappear completely.

## Version

Recent snapshot build from master branch:

```
tendrl-ui-1.5.2-20170921T165116.b85723e.noarch
```

I'm using `firefox-55.0.3-1.fc26.x86_64`

## Steps to Reproduce

1. Prepare machines with GlusterFS cluster, including gluster volume (I used [nightly builds](https://github.com/usmqe/usmqe-setup/tree/master/roles/gluster-centos-repo) and [volume_usmqe_alpha_distrep_4x2.create.conf](https://github.com/usmqe/usmqe-setup/blob/master/gdeploy_config/volume_usmqe_alpha_distrep_4x2.create.conf))
2. Install Tendrl via tendrl-ansible there, using [snapshot builds](https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/)
3. Log into the Tendrl web interface as an admin user
4. Import the cluster and wait for task to finish with success
5. Go to *Clusters* page and click on the item for the cluster you just imported so that the Hosts tab is visible
6. Change width of browser window and observe how hosts list look like.

## Actual Result

At some point (996 px), the host names are truncated into single characters:

![screenshot_20170925_182204](https://user-images.githubusercontent.com/4759819/30819376-ca2199c6-a21e-11e7-8171-57f0545d899b.png)

Going further to 880 px, and the host names disappear completely:

![screenshot_20170925_182232](https://user-images.githubusercontent.com/4759819/30819443-f8842ff4-a21e-11e7-879e-d7ccaaed8364.png)

This is still a problem even when the left menu disappears (650 px in this case):

![screenshot_20170925_182317](https://user-images.githubusercontent.com/4759819/30819483-15e8c938-a21f-11e7-8c90-9f63e817b798.png)

## Related Issues

* https://github.com/Tendrl/ui/issues/566 (another problem on Clusters page)

**Comment by gnehapk** [comment]
@mbukatov Fixed with tendrl-ui-1.5.2-20170925T180704.770936f.noarch.rpm. Please verify.

**Comment by mbukatov** [comment]
Verifying with `tendrl-ui-1.5.2-20170925T180704.770936f.noarch` and the problem seems fixed, in a narrow window, the name of the machines is visible relative to the available space:

![screenshot_20170926_094103](https://user-images.githubusercontent.com/4759819/30848447-79ace1f4-a29f-11e7-9ac8-0ad4bd03e20a.png)
