### ISSUE TITLE
[UX] Confusing navigation in the UI produces unexpected results

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#644]
With the context-switcher at the top, select a single cluster or all clusters does not affect what is shown in the list views, which will lead to user confusion as UI is producing unexpected results.

Specifically, if a single cluster is selected (in the context switcher), the user would expect to only see the hosts for the single cluster in the Host List, vs. all the hosts from multiple clusters.

If all clusters is selected (in the context switcher), the user would expect to all the hosts for all clusters known to Tendrl.

This would apply to other list views shown in the navigation, Alerts and Tasks, and Admin -> Users.

If a single cluster is selected (in the context switcher), the user would expect to see only Alerts related to the single cluster and the same goes for Tasks.  What would it mean for users when single cluster is selected?  Does the users only apply to the single cluster?

By mixing and matching different navigational models, the user experience is adversely impacted and leading to user confusion, unexpected results, and poor usability.

I recommend simplifying and going with what's suggested in [Concept B: Single Cluster / Element Manager Concept with Context Switcher Navigation (Optimized UX)](https://redhat.invisionapp.com/share/8QCOEVEY9).

The following screenshot is provided for context of this issue:
![screen shot 2017-09-27 at 1 27 21 pm](https://user-images.githubusercontent.com/5589919/30970934-8423fd34-a434-11e7-9bbb-b4391af6b6ff.png)

@gnehapk @nthomas-redhat @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Can you please tell me how the global host, task and alert list views will be accessible as per Concept B UX design as I don't see any menu or option to access it.

**Comment by julienlim** [comment]
@gnehapk To my knowledge, based on the revised MVP, we were building something that was giving an "element-centric" view of each storage subsystem and optimizing for their experience, and were moving away from providing aggregate/global views in the Tendrl UI.  As there was no longer the requirement to be unified management across multiple storage subsystems, there was no longer a requirement for providing global views.

**Comment by julienlim** [comment]
@gnehapk @a2batic @cloudbehl @sankarshanmukhopadhyay @nthomas-redhat @mcarrano @Tendrl/tendrl-qe 

@bleathem has implemented the fix for this at https://github.com/Tendrl/ui/pull/682.  Can we get it into the release?

**Comment by r0h4n** [comment]
@julienlim Tendrl is under a feature freeze as of now, however @Tendrl/tendrl-core will start reviewing the PR and line it up for functional testing and future release.

**Comment by julienlim** [comment]
@gnehapk @a2batic @cloudbehl @sankarshanmukhopadhyay @nthomas-redhat @mcarrano @r0h4n @Tendrl/tendrl-qe

@bleathem has filed another PR related to this at:
https://github.com/Tendrl/ui/pull/682/files/def3f22528e9e0e8fb92a739012dfde16ebe4db4..28ea0cb1c70b80495b28441ff1b1a13e12658e0f

**Comment by gnehapk** [comment]
UI views are updated as per the concept B designs and are present in tendrl-release v1.5.5. Hence, closing this issue.
