### ISSUE TITLE
"Launch Dashboard" words outside of button widget

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#646]
Something wierd is happening in Chrome where the "Launch Dashboard" words don't seem to be contained in the button.  It is fine in Firefox.

<img width="1117" alt="screen shot 2017-09-28 at 2 14 07 pm" src="https://user-images.githubusercontent.com/5589919/30983314-10c06142-a458-11e7-87c9-2735467f0c05.png">

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim I am not able to reproduce this issue. Tried with both zooming out and zooming  in the view. Attaching the screenshot for the same.
 
![screenshot from 2017-09-29 08-57-16](https://user-images.githubusercontent.com/5517376/30999774-b5bc0b96-a4f4-11e7-9d6f-988cac2fd1dd.png).

Can you please check on RHEL/centos machine and confirm as mac OS sometimes overwrite or don't support few styles. For eg - https://stackoverflow.com/questions/28974069/css-dropdown-option-text-color-not-working-on-mac-os-x

**Comment by julienlim** [comment]
@gnehapk This has to do with putting a fix width on the buttons -- please remove specifying fix width on the buttons.

in .tendrl-cluster-list-view-container.list-group .list-group-item .list-view-pf-actions .btn-default {
width: 124px; } in main.css - a fixed width should not be set

see attached screenshot, by unchecking it, it removed the truncation issue and allowed text in buttons to be visible.

![screen shot 2017-10-02 at 3 56 26 pm](https://user-images.githubusercontent.com/5589919/31096657-b6a5187a-a78a-11e7-8485-eea252e9f193.png)

**Comment by cloudbehl** [comment]
@julienlim The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.src.rpm).

**Comment by julienlim** [comment]
Issue appears to be fixed.  See screenshot below:
![screen shot 2017-10-18 at 2 27 13 pm](https://user-images.githubusercontent.com/5589919/31946784-c42a4b74-b8a0-11e7-95e9-c9dcdf8a1ecb.png)
