### ISSUE TITLE
Import cluster: checkbox text typos, checkbox text, infotip and checkbox not aligned

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#647]
There's typos in the "Enable Volume Profiling." which should be "Enable volume profiling"

The text and checkbox and infotip icon are not aligned and all seem to have a slightly different offset.

This can be seen using both Chrome and Firefox.

Design can be found at: https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/247445416.

<img width="1280" alt="screen shot 2017-09-28 at 2 13 33 pm" src="https://user-images.githubusercontent.com/5589919/30983539-b6d683f4-a458-11e7-90e6-3d391b77329f.png">

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Not producible on my machine for both chrome and firefox browsers. 

Can you please check on RHEL/centos machine and confirm as mac OS sometimes overwrite or don't support few styles. For eg - https://stackoverflow.com/questions/28974069/css-dropdown-option-text-color-not-working-on-mac-os-x

**Comment by julienlim** [comment]
The checkbox is too low there is a vertical-align:sub applied.  Please fix.

@gnehapk @Tendrl/tendrl-qe

**Comment by a2batic** [comment]
@julienlim, Fixed in tendrl-ui-1.5.2-20171011T095120.b554d56.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Issue appears fixed.

![screen shot 2017-10-18 at 1 40 15 pm](https://user-images.githubusercontent.com/5589919/31947394-38e982bc-b8a2-11e7-9108-9179e980e612.png)
