### ISSUE TITLE
Grafana dashboard panels missing light gray background fill

### ISSUE THREAD

**Issue by mcarrano** [Tendrl/ui#649]
In Tendrl build, Grafana dashboard panels have a white background fill against the white page background. This makes it difficult to perceive card boundaries that provide structure to the page. 

![screen shot 2017-09-29 at 4 17 16 pm](https://user-images.githubusercontent.com/6619860/31034508-697397de-a532-11e7-8d57-92014a80f59e.png)

Recommend a light gray panel background to better define the area of the card. Suggest #fafafa or #f5f5f5 as a target gray value.  Also see the below screen shot from Ceph Metric for reference.

![screen shot 2017-09-29 at 4 17 43 pm](https://user-images.githubusercontent.com/6619860/31034608-c8712c42-a532-11e7-99f5-7802ce0ac938.png)

**Comment by julienlim** [comment]
@cloudbehl This needs to be filed in the monitoring-integration repo, can you please address?
@mcarrano @Tendrl/tendrl-qe

**Comment by cloudbehl** [comment]
@julienlim Done
