### ISSUE TITLE
Clusters List differs from design

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#650]
Implemented `Clusters` site differs from [the design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738628).

- [ ] There is missing `?` icon indicating not imported status next to not imported cluster.
- [ ] There is a `Volume Profile` field.
- [ ] The row is clickable (list of hosts appears after click under the cluster row).

![102_clusters](https://user-images.githubusercontent.com/22369801/31113240-96f08f26-a818-11e7-99a0-528e59471963.png)

Tested with:
```
tendrl-commons-1.5.2-20170928T094225.e83ddf7.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
tendrl-node-agent-1.5.2-20170928T123732.dfcaddf.noarch
tendrl-monitoring-integration-1.5.2-20171002T072407.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20171002T072407.2e1d15a.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
Chromium v59.0.3071.104 (64-bit)
```

**Comment by gnehapk** [comment]
@a2batic Add "?" icon for cluster which are not imported.

**Comment by a2batic** [comment]
@fbalak, The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T153913.e46fe49.noarch.rpm).

**Comment by julienlim** [comment]
@fbalak @a2batic All items mentioned above appears to have been fixed. 

<img width="1064" alt="screen shot 2017-10-11 at 12 52 23 pm" src="https://user-images.githubusercontent.com/5589919/31460851-a2fd4308-ae95-11e7-87f8-f65e860d332c.png">

**Comment by fbalak** [comment]
Seems ok.
Tested with:
```
tendrl-notifier-1.5.3-20171011T200310.3c01717.noarch
tendrl-grafana-plugins-1.5.3-20171012T072405.9cb211a.noarch
tendrl-monitoring-integration-1.5.3-20171012T072405.9cb211a.noarch
tendrl-api-httpd-1.5.3-20171011T200630.494b1eb.noarch
tendrl-commons-1.5.3-20171011T195629.890684b.noarch
tendrl-api-1.5.3-20171011T200630.494b1eb.noarch
tendrl-ui-1.5.3-20171012T073358.7df67fb.noarch
tendrl-ansible-1.5.3-20171009T123017.9a9a956.noarch
tendrl-node-agent-1.5.3-20171011T195654.c8b5946.noarch
```
