### ISSUE TITLE
[UX] Change / shorten button labels in the various views in Tendrl UI

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#651]
Change / shorten button labels in the various views in Tendrl UI for improved usability:

- “Import Cluster” → “Import”
- “Launch Dashboard” → “Dashboard”
- “Cluster Details” → “Details”
- "Host Details" → “Details”
- "Volume Details" → “Details”
- "Task Details"  → “Details”

Note: This may also help with labels getting truncated.

@gnehapk @a2batic @mcarrano @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @nthomas-redhat

**Comment by cloudbehl** [comment]
@julienlim The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.src.rpm).

**Comment by julienlim** [comment]
@cloudbehl Just redeployed using tendrl-ansible from master, and verified button labels changed.
