### ISSUE TITLE
Cluster Version - column label and displayed value inconsistency in different views

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#652]
The "Cluster Version" column is displayed inconsistently in different places in the UI.

In the Cluster List, it shows:
Cluster Version
4.0dev

In the Import Cluster page, it shows:
Version
gluster 4.0dev

They should both be consistent.  I'd suggest in both views:
Cluster Version
gluster 4.0dev

Cluster List screenshot:
![screen shot 2017-10-02 at 11 51 46 am](https://user-images.githubusercontent.com/5589919/31127667-a02b1912-a81d-11e7-9eb7-bf108298833a.png)

Import Cluster screenshot:
![screen shot 2017-10-02 at 11 43 44 am](https://user-images.githubusercontent.com/5589919/31127742-aff28984-a81d-11e7-9aef-7fcc3db4d205.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @nthomas-redhat

**Comment by a2batic** [comment]
@julienlim, Fixed with tendrl-ui-1.5.2-20171010T124450.4044474.noarch.rpm. Please verify

**Comment by julienlim** [comment]
This issue has been fixed.

![screen shot 2017-10-18 at 1 38 11 pm](https://user-images.githubusercontent.com/5589919/31947040-72f83af8-b8a1-11e7-85e5-a9b77db94e89.png)

![screen shot 2017-10-18 at 1 40 15 pm](https://user-images.githubusercontent.com/5589919/31947034-6c28f65e-b8a1-11e7-8564-46235a2415e2.png)
