### ISSUE TITLE
Cluster List: Move “Ready to import” column after Volume Profile column

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#653]
Cluster List: Move “Ready to import” column after Volume Profile column
![screen shot 2017-10-02 at 11 42 50 am](https://user-images.githubusercontent.com/5589919/31127906-325c3f96-a81e-11e7-8f6f-83b0fe96de2c.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @mcarrano @Tendrl/tendrl-qe

**Comment by cloudbehl** [comment]
@julienlim We have followed the patternfly way to display the information and correspondingly we have used the same classes provided by patternfly.

http://www.patternfly.org/pattern-library/content-views/list-view/#/overview

**Comment by julienlim** [comment]
@cloudbehl The ask here is not that you didn't follow PatternFly way of displaying information but to move one of the columns.  Specifically moving the 2nd column (Ready to import, Ready to use) to the end.  So user sees the text, and right away sees the action to perform related to the text.

**Comment by gnehapk** [comment]
@julienlim Fixed in tendrl-ui-1.5.2-20171011T153913.e46fe49.noarch.rpm build. Please verify.

**Comment by julienlim** [comment]
Verified fix.  Thank you @gnehapk.
