### ISSUE TITLE
Cluster List: Volume Profile -> Volume Profiling label change

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#654]
Change “Volume Profile” label to “Volume Profiling” as it's about volume profiling and not volume profile (plus it'll be consistent with how it's referred to in Gluster docs).

![screen shot 2017-10-02 at 11 42 50 am](https://user-images.githubusercontent.com/5589919/31128108-d3c7d6a6-a81e-11e7-9ad0-e1fa43b3ead2.png)

@gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano @nthomas-redhat

**Comment by cloudbehl** [comment]
@julienlim The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.src.rpm).

**Comment by julienlim** [comment]
Issue fixed.

![screen shot 2017-10-18 at 1 38 11 pm](https://user-images.githubusercontent.com/5589919/31947123-92b7dbaa-b8a1-11e7-8d7a-655f8a76ae15.png)
