### ISSUE TITLE
Action buttons too far apart or too close

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#655]
Distance the action buttons -- Import and Cancel -- are too far apart. Please update and follow [PatternFly Button on Forms examples](http://www.patternfly.org/pattern-library/forms-and-controls/buttons-on-forms/).

I believe it's roughly about 10px apart.

![screen shot 2017-10-02 at 11 43 44 am](https://user-images.githubusercontent.com/5589919/31129001-5e297244-a821-11e7-8b7c-cbe2e85b8b67.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano 

For the Task in progress page, the buttons are too close:

![screen shot 2017-10-02 at 11 28 25 am](https://user-images.githubusercontent.com/5589919/31140417-51e8bf0a-a842-11e7-9de7-6d0ccbe12431.png)

**Comment by a2batic** [comment]
@julienlim, Fixed with tendrl-ui-1.5.2-20171010T124450.4044474.noarch.rpm. Please verify

**Comment by julienlim** [comment]
Issue resolved.

![screen shot 2017-10-24 at 2 04 43 pm](https://user-images.githubusercontent.com/5589919/31961732-9722b502-b8c9-11e7-897e-ae128f2e6e83.png)

![screen shot 2017-10-24 at 2 05 07 pm](https://user-images.githubusercontent.com/5589919/31961737-9926cba4-b8c9-11e7-951f-81136858ecc1.png)
