### ISSUE TITLE
Tasks List: All filters should be selected by default

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#657]
By default, all the filters (checkboxes) should be selected to show that all tasks with all statuses selected when user clicks to look at the Tasks List.

See task list design for details: https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/251481034

![screen shot 2017-10-02 at 1 59 49 pm](https://user-images.githubusercontent.com/5589919/31129704-5bfc7b40-a823-11e7-8c77-ff837c2b6d49.png)

@gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Fixed in tendrl-ui-1.5.2-20171011T153913.e46fe49.noarch.rpm build. Please verify.

**Comment by julienlim** [comment]
Verified the fix @gnehapk 

<img width="1071" alt="screen shot 2017-10-11 at 12 53 20 pm" src="https://user-images.githubusercontent.com/5589919/31457430-b9edf19e-ae8a-11e7-9a2f-c7f1b78b4e21.png">
