### ISSUE TITLE
Clusters List: Remove kebab menu and move "Disable Profiling" to appear with other buttons

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#659]
Clusters List: No need for kebab menu for single action “Disable Profiling” -- it should be a button as a peer to Cluster Details and Launch Dashboard.

![screen shot 2017-10-03 at 2 43 19 pm](https://user-images.githubusercontent.com/5589919/31142757-36f98056-a849-11e7-971c-2df3e3064d90.png)

By shortening button labels (see https://github.com/Tendrl/ui/issues/651), the buttons shown would be (for a cluster under Tendrl monitoring): Details, Dashboard, Disable Profiling

**Comment by cloudbehl** [comment]
@julienlim The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.src.rpm).

**Comment by julienlim** [comment]
Issue fixed.

![screen shot 2017-10-18 at 1 48 34 pm](https://user-images.githubusercontent.com/5589919/31947176-b3e7d410-b8a1-11e7-8fb3-68970e63b618.png)
