### ISSUE TITLE
Utilisation --> Utilization

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#660]
Hosts > Brick Details and Cluster > Volume > Brick Details:

“Utilisation” (British-English) not consistent with Gluster American-English terminology used unless Tendrl is supporting I18N; note: must also be consistent in Grafana Dashboards

Please change to "Utilization" instead.

**Comment by cloudbehl** [comment]
@julienlim The Issue has been fixed. Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.src.rpm).

**Comment by julienlim** [comment]
Spelling fix resolved.

![screen shot 2017-10-24 at 2 11 57 pm](https://user-images.githubusercontent.com/5589919/31961976-4e3a4340-b8ca-11e7-803e-c83fc0594cdd.png)
