### ISSUE TITLE
Missing end time under “Failed” or “Completed” columns 

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ui#661]
W.R.T : https://redhat.invisionapp.com/share/8N93NO7Q4#/screens/200318248

**Comment by r0h4n** [comment]
Tracking issue: https://github.com/Tendrl/commons/issues/747

**Comment by a2batic** [comment]
@cloudbehl, Fixed with tendrl-ui-1.5.2-20171010T124450.4044474.noarch.rpm. Please verify

**Comment by cloudbehl** [comment]
@a2batic Verfied
