### ISSUE TITLE
Multiple cluster import jobs

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#662]
I had 1 not imported cluster. I clicked on Import cluster and was redirected to screen where I can specify Volume Profiling. (Image below)

![104_import](https://user-images.githubusercontent.com/22369801/31179350-0e004d00-a91c-11e7-9a2b-a288672ef22a.png)

When I clicked on `Import` button I was not redirected immediately so I click on the button twice more. After that I was redirected. This created 3 import tasks. 2 of them failed, 1 has finished successfully.

During the processing of import task I tried to create another import task for the same cluster by repeating the process. I was able to create another import task from main `Clusters` page. There was still `Import` button during cluster import processing.

User shouldn't be able to create more import cluster tasks from UI when the cluster is being imported.

Tested with:
```
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
tendrl-node-agent-1.5.2-20171004T105957.709badc.noarch
tendrl-monitoring-integration-1.5.2-20171004T072405.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20171004T072405.2e1d15a.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
```

**Comment by r0h4n** [comment]
Provide screenshot for failed tasks, tendrl-backend does not allow multiple imports and fails any import jobs if there's already one in progress

**Comment by fbalak** [comment]
It seems to be fixed since yesterday.

Tested with:
```
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
tendrl-node-agent-1.5.2-20171004T105957.709badc.noarch
tendrl-monitoring-integration-1.5.2-20171005T132717.1b8a4c1.noarch
tendrl-grafana-plugins-1.5.2-20171005T132717.1b8a4c1.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
```
