### ISSUE TITLE
Alert filter by hostname not working correctly

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#666]
[1]  Alert filter not working correctly, getting extra line entries in results.  Specifically, when trying to filter on hostname = node3, I get 2 additional non-node3 entries in the alerts list.

<img width="1174" alt="screen shot 2017-10-06 at 7 44 51 pm" src="https://user-images.githubusercontent.com/5589919/31302335-fc00d61a-aace-11e7-9848-551052133842.png">

[2]  When I then try to filter for node4, I get no results, when it should return a single line entry.  See before (without filter applied), and after filter for hostname = node4
<img width="1174" alt="screen shot 2017-10-06 at 7 47 25 pm" src="https://user-images.githubusercontent.com/5589919/31302380-630352e8-aacf-11e7-9082-cfc5f52f630b.png">

<img width="1173" alt="screen shot 2017-10-06 at 7 47 37 pm" src="https://user-images.githubusercontent.com/5589919/31302382-65c72dd8-aacf-11e7-9b20-3faf2b100240.png">

@gnehapk @a2batic @Tendrl/tendrl-qe @Tendrl/tendrl-frontend @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please share the response received for /alerts API response.

**Comment by julienlim** [comment]
@gnehapk I'm noticing that the Alerts filtering doesn't seem to work very well.  It sometimes works and sometimes does not.  E.g. Filter by cluster name does not work at all for me.

Here's the API response for listing alerts

curl -XGET -H "Authorization: Bearer 9d7892c32d2c407eec667908e62648d4b4889bbd3bd3400252ca4c03aeea7f65" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/alerts


[{"severity":"WARNING","updated_at":"2017-10-06 15:05:05.411003+00:00","source":"GRAFANA","acked_at":"","classification":"cluster","alert_type":"UTILIZATION","resource":"bricks_utilization_alert","pid":"23495","acked":"False","ackedby":"","node_id":"8a24152f-dd03-43f2-9dff-87748ad71eb8","ack_comment":"[]","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node3","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","warning_max":75,"brick_path":"|bricks|brick1","plugin_instance":"averageSeries(tendrl.clusters.6cea5c51-5502-4276-a5a8-0ef82a4e3dc7.nodes.node3.bricks.|bricks|brick1.utilization.percent-percent_bytes)","message":"Brick utilization of |bricks|brick1 in node node3 in cluster 6cea5c51-5502-4276-a5a8-0ef82a4e3dc7 is 81.6279933955 which is above WARNING threshold 75"},"hash":"16230dc903b9be2574bd5a5b3ec63900","alert_id":"537cdc65-f306-4f43-a6b8-cf32680528d3","significance":"HIGH","current_value":"81.6279933955","time_stamp":"2017-10-06T15:05:02Z","delivered":"True"},{"resource":"bricks_utilization_alert","updated_at":"2017-10-06 15:09:43.419922+00:00","significance":"HIGH","current_value":"91.4351825248","acked_at":"","classification":"cluster","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node1","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","warning_max":75,"brick_path":"|bricks|brick1","plugin_instance":"averageSeries(tendrl.clusters.6cea5c51-5502-4276-a5a8-0ef82a4e3dc7.nodes.node1.bricks.|bricks|brick1.utilization.percent-percent_bytes)","message":"Brick utilization of |bricks|brick1 in node node1 in cluster 6cea5c51-5502-4276-a5a8-0ef82a4e3dc7 is 91.4351825248 which is above WARNING threshold 75"},"ack_comment":"[]","delivered":"True","severity":"WARNING","hash":"3ea96ba642ac981941835aad978a8b3a","time_stamp":"2017-10-06T15:09:10Z","acked":"False","ackedby":"","source":"GRAFANA","alert_id":"02e4871c-bd87-42a2-894e-8fc1cec87611","node_id":"65214ec0-af37-4bec-a4aa-84aabcd6c89c","alert_type":"UTILIZATION","pid":"23495"},{"alert_type":"STATUS","hash":"05eea3967cf2474591e308698bf7aebc","severity":"INFO","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node3","sds_name":"gluster","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","plugin_instance":"volume_myvolume","message":"Status of volume: myvolume changed from Stopped to Started"},"acked":"True","node_id":"8a24152f-dd03-43f2-9dff-87748ad71eb8","current_value":"Started","acked_at":"2017-10-06T15:11:35.448529+00:00","classification":"cluster","ackedby":"TENDRL","resource":"volume_status","pid":"17462","updated_at":"2017-10-06 15:11:45.980521+00:00","delivered":"True","source":"gluster_integration","alert_id":"edf3dc0f-cd95-4c0c-8092-992846cf65ed","ack_comment":"[\"System acked\"]","significance":"","time_stamp":"2017-10-06T15:11:33.768963+00:00"},{"delivered":"True","pid":"17462","acked":"True","alert_id":"193b0477-b91e-430c-b340-60cd1abdea47","alert_type":"STATUS","hash":"2732c317bc43ba7ebc796dc483e92bb2","classification":"cluster","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node3","sds_name":"gluster","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","plugin_instance":"volume_myvolume|brick_node3:/bricks/brick1","message":"Status of brick: node3:/bricks/brick1 under volume myvolume changed from Stopped to Started"},"resource":"brick_status","ackedby":"TENDRL","current_value":"Started","time_stamp":"2017-10-06T15:11:37.261785+00:00","acked_at":"2017-10-06T15:11:39.327270+00:00","severity":"INFO","updated_at":"2017-10-06 15:11:46.252528+00:00","source":"gluster_integration","node_id":"8a24152f-dd03-43f2-9dff-87748ad71eb8","ack_comment":"[\"System acked\"]","significance":""},{"delivered":"True","alert_type":"STATUS","hash":"d311126721ecc47abd59e40ad278f84b","classification":"cluster","updated_at":"2017-10-06 15:13:49.061334+00:00","source":"gluster_integration","ack_comment":"[\"System acked\"]","significance":"","acked_at":"2017-10-06T15:13:31.826925+00:00","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node1","sds_name":"gluster","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","plugin_instance":"volume_myvolume|brick_node1:/bricks/brick1","message":"Status of brick: node1:/bricks/brick1 under volume myvolume changed from Stopped to Started"},"resource":"brick_status","acked":"True","alert_id":"283d4db7-f2b9-449d-90e4-e3b8e53efab2","time_stamp":"2017-10-06T15:13:30.118191+00:00","pid":"17753","ackedby":"TENDRL","current_value":"Started","severity":"INFO","node_id":"65214ec0-af37-4bec-a4aa-84aabcd6c89c"},{"significance":"HIGH","current_value":"76.7243988308","time_stamp":"2017-10-06T15:29:30Z","acked_at":"2017-10-06T15:29:34.068961+00:00","classification":"cluster","resource":"bricks_utilization_alert","updated_at":"2017-10-06 15:30:05.900195+00:00","alert_type":"UTILIZATION","hash":"c3a29f93a5f7507d29b2d6a4d6f1c911","source":"GRAFANA","ack_comment":"[\"System acked\"]","delivered":"True","ackedby":"TENDRL","alert_id":"de16e9e1-ec71-4a11-b739-c3cffc57ef8f","node_id":"77c63d11-1549-451b-a00c-8d23ee3fae01","severity":"INFO","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node2","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","warning_max":75,"brick_path":"|bricks|brick1","plugin_instance":"averageSeries(tendrl.clusters.6cea5c51-5502-4276-a5a8-0ef82a4e3dc7.nodes.node2.bricks.|bricks|brick1.utilization.percent-percent_bytes)","message":"Brick utilization of |bricks|brick1 in node node2 in cluster 6cea5c51-5502-4276-a5a8-0ef82a4e3dc7 is back normal"},"pid":"23495","acked":"True"},{"classification":"cluster","pid":"23495","updated_at":"2017-10-06 15:30:37.431038+00:00","source":"GRAFANA","node_id":"77c63d11-1549-451b-a00c-8d23ee3fae01","current_value":"76.7243988308","hash":"d344fef12d9a3eab77a71199043594b0","alert_type":"UTILIZATION","severity":"INFO","resource":"bricks_utilization_alert","ackedby":"TENDRL","delivered":"True","alert_id":"0a5909e3-f498-4b66-9d55-c142c0d634a3","significance":"HIGH","acked":"True","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node2","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","warning_max":75,"brick_path":"|bricks|brick1","plugin_instance":"averageSeries(tendrl.clusters.6cea5c51-5502-4276-a5a8-0ef82a4e3dc7.nodes.node2.bricks.|bricks|brick1.utilization.percent-percent_bytes)","message":"Brick utilization of |bricks|brick1 in node node2 in cluster 6cea5c51-5502-4276-a5a8-0ef82a4e3dc7 is back normal"},"ack_comment":"[\"System acked\"]","time_stamp":"2017-10-06T15:30:25Z","acked_at":"2017-10-06T15:30:28.785218+00:00"},{"alert_id":"abb29653-f478-42fe-a87c-eb9f4ba5f677","ack_comment":"[]","alert_type":"STATUS","classification":"cluster","source":"gluster_integration","significance":"","time_stamp":"2017-10-06T15:49:22.770069+00:00","acked_at":"","tags":{"integration_id":"6cea5c51-5502-4276-a5a8-0ef82a4e3dc7","fqdn":"node3","sds_name":"gluster","cluster_name":"gluster-e07e58fdf5e64af25bf3dcce12a644b52e527516f593bb2355b0266cfb7546e4","plugin_instance":"peer_node4","message":"Status of peer: node4 changed from Connected to Disconnected"},"resource":"peer_status","acked":"False","current_value":"Disconnected","hash":"9bf92f755cad4c537672890b8128b0d9","severity":"WARNING","updated_at":"2017-10-06 15:49:30.200897+00:00","ackedby":"","node_id":"8a24152f-dd03-43f2-9dff-87748ad71eb8","delivered":"True","pid":"17462"}][root@node0 tendrl-ansible]#

**Comment by gnehapk** [comment]
@GowthamShanmugam @nthomas-redhat @shtripat @r0h4n @anivargi In the API response, for alert object having  "message":"Status of peer: node4 changed from Connected to Disconnected", its fqdn is set to node3. Hence, UI is displaying this alert object too when someone types node3 in the search box for host name. Please look into it.

**Comment by gnehapk** [comment]
@julienlim Cluster name filtering working for me. Attaching screenshot for the same.

![screenshot from 2017-10-10 15-33-26](https://user-images.githubusercontent.com/5517376/31380902-72cd26be-add0-11e7-8f1c-487dc5f49f5a.png)

Can you please mention by which cluster name, you have performed the filtering.

**Comment by GowthamShanmugam** [comment]
@shtripat @nnDarshan @gnehapk The problem is we are assigning node id of the machine which raises alert, but actually alert is for some other machine. Let's take example node_A goes down, so node_B will raise alert like node_A went down. So node_id of node_B is actually assigned to that alert and message is like node_A is gone down. So filtering of node_A is not showing the alert in UI.

We have to assign node_id of the machine with went down.

**Comment by shtripat** [comment]
@GowthamShanmugam yes. I remember we discussed this once couple of days back. So my suggestion for this would to have entity type and entity id as well associated with each alert message. The entity id is not the node_id/cluster_id in/from which this alert is raised. Its rather the details of the entity for which this alert is raised.

Using these attributes we should be able to filter the alerts for specific entities properly. I understand for this we might end up maintaining more indexed alerts in etcd.

Can you please to come up with a proper dir structure in etcd with this suggestion (if you its a workable solution)?

@Tendrl/tendrl-core comments?

**Comment by GowthamShanmugam** [comment]
@Tendrl/tendrl-core we should handle the brick down alert as node alert. But it is related to cluster also.

@shtripat is suggested like we should maintain brick down alert as node. because We are not maintaining the hierarichal kind of thing like for this cluster and this volume this brick is down in alert directory.

@anmolbabu is suggested like this should be stored at both levels. Because brick alert only raised when brick is used inside the cluster.

Need suggestion from @nthomas-redhat @r0h4n please comment here

**Comment by julienlim** [comment]
@Tendrl/tendrl-core @GowthamShanmugam @shtripat @mcarrano @Tendrl/tendrl-qe 

When a brick is down, from a user's perspective, this impacts the node and the cluster.  So, an alert should be triggered at both the node and cluster level.  If the brick is being used in a volume, then it also impacts the volume, hence then we'd also want an alert to be triggered at the volume level.

**Comment by GowthamShanmugam** [comment]
@julienlim i agree, brick down alert will has to go in
   - cluster
        volume
         brick
   - node
so impact all so we need to increment node count, volume count and cluster count of alerts, it should stored in the node as well as a cluster.
i have raised question and suggestion of @Tendrl/tendrl-core here https://github.com/Tendrl/gluster-integration/issues/449 for this

**Comment by GowthamShanmugam** [comment]
@julienlim @gnehapk This issue is fixed, please verify and close this

**Comment by GowthamShanmugam** [comment]
Please verify this and close it

**Comment by julienlim** [comment]
Verified.
