### ISSUE TITLE
Counter for Replica Set (or Subvolume / Dispersed Set) should start at 0

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#672]
In the Bricks tab view, the replica set counter starts at 1.  In gstatus, it starts at 0.  They should be consistent between the Tendrl UI and gstatus.

See screenshots from Tendrl UI and gstatus output:

![screen shot 2017-10-09 at 9 32 31 am](https://user-images.githubusercontent.com/5589919/31347534-a5554ba2-acea-11e7-9ba5-4590212cbdc0.png)

![screen shot 2017-10-09 at 9 33 25 am](https://user-images.githubusercontent.com/5589919/31347540-aa0c0726-acea-11e7-9e15-2f6f722af13e.png)

@gnehapk @a2batic @nthomas-redhat @mcarrano @Tendrl/tendrl-qe

**Comment by sankarshanmukhopadhyay** [comment]
Probably worth checking with Paul Cuzner/Sachidananda as to why gstatus counter starts from '0' (zero) and have the reason documented prior to making it consistent.

**Comment by shtripat** [comment]
I understand in `gstatus` output its using array index as counter attached to `Replica Set` keyword. Is it really that critical to have replica set numbers in sync with `gstatus`. Also if we don't use `gstatus`, is it correct to compare with `gstatus` output.

I personally feel there is nothing wrong to say `Replica Set1`, `Replica Set2` and `Replica Set3` if there are 3 replica sets in volume.

Still I leave it to broader audience to comment. If we have to match `gstatus` output, it should be small UI change I feel. @cloudbehl ^^

**Comment by cybernth** [comment]
@shtripat , It's not about gstatus output ( we don't really have to match with that) but the gluster documentation also follow the same terminology.  So it is better to have consistency with the doc

**Comment by a2batic** [comment]
@julienlim, Fixed with tendrl-ui-1.5.3-20171012T142223.125d75e.noarch.rpm (current master build). Please verify.

**Comment by julienlim** [comment]
@a2batic @Tendrl/tendrl-qe 

Verified fix.  Results from UI matches what's in gstatus, i.e. both showing Replica Set 0 starting counter.
![screen shot 2017-10-18 at 1 49 08 pm](https://user-images.githubusercontent.com/5589919/31733997-49c9aab2-b40b-11e7-951e-7aef005916de.png)
