### ISSUE TITLE
Task: Filter by flow... labeling changes needed

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#674]
It's not clear to the user what a "flow" is as this is the first time it's mentioned anywhere in the UI.  I think we need to use front-end (and not back-end) terminology here.

Name (in the button) --> Task
"Filter by flow..." --> "Filter by task

Note: I'm suggesting to change "Name" to be clearer what "Name" refers to here, i.e. Task (vs. Task ID or something else).

<img width="1173" alt="screen shot 2017-10-09 at 4 43 55 pm" src="https://user-images.githubusercontent.com/5589919/31357962-c5b21638-ad11-11e7-8f4a-f46887d0e82e.png">

@gnehapk @a2batic @mcarrano @Tendrl/tendrl-qe

**Comment by a2batic** [comment]
@julienlim The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.noarch.rpm).

**Comment by julienlim** [comment]
Issue fixed.

![screen shot 2017-10-24 at 2 35 42 pm](https://user-images.githubusercontent.com/5589919/31961422-ac2648ca-b8c8-11e7-926f-b144589f6fa8.png)
