### ISSUE TITLE
Alerts and Tasks views: date picker unexpected behavior

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#681]
In both the Alerts and Tasks list pages, I've observed the the date picker validation does not appear to work as one would expect.  It currently does the following:

* When user to specifies invalid date ranges, i.e. user specifies a To date earlier than the From date, it provides error message "*To date cannot be greater than from date" -- Note: To date should always be greater than the From date.  Error message is misleading the user.

* When user clicks on the "Clear All Filters" the error message still persists and should be removed

In an ideal scenario, user should not be allowed to pick a To date that is before the From date.

In discussion with @bleathem@redhat.com, he suggested using the date range picker from http://www.daterangepicker.com/ since Tendrl is using jQuery, which I've looked at, and it appears to be a good fit (and hopefully reduces some of the bugs observed above).

![screen shot 2017-10-09 at 9 42 08 am](https://user-images.githubusercontent.com/5589919/31448323-2a9adfce-ae72-11e7-9365-f8aaca572d46.png)

<img width="1082" alt="screen shot 2017-10-11 at 10 52 32 am" src="https://user-images.githubusercontent.com/5589919/31448372-444092f2-ae72-11e7-9d48-0735ba1ecf6d.png">

@cloudbehl @gnehapk @a2batic @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please specify the error message to be displayed when "To date" selected is before "From Date".

**Comment by julienlim** [comment]
@gnehapk @mcarrano @Tendrl/tendrl-qe  It's preferable if we can switch out the component to the datepicker from http://www.daterangepicker.com/ if possible.

Error message probably should say: "The To date must be greater than the From date"
To date cannot be greater than from date

**Comment by gnehapk** [comment]
@julienlim Issues observed for the current date picker are solved with tendrl-ui-1.5.3-20171024T073937.0815acd.noarch.rpm. Please verify. Since, date range picker(http://www.daterangepicker.com/) component is not available in the patternfly yet, we will use it once it gets available in future.

**Comment by julienlim** [comment]
@gnehapk If we're don't plan to change the current date picker, can we at least fix the Error message to something that will not confuse users, i.e. "To date must be greater than the From date, i.e. To > From" and not the existing text which is confusing: "To date cannot be greater than from date" which in other words is saying To < From)

I installed from master yesterday and still it says the confusing error message.

<img width="635" alt="screen shot 2017-10-25 at 10 11 05 am" src="https://user-images.githubusercontent.com/5589919/32003574-841eb358-b96d-11e7-801a-7ca2c05ed50b.png">

@gnehapk

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.3-20171027T071719.c55fbe7.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Error message has been fixed.
![screen shot 2017-11-01 at 4 12 40 pm](https://user-images.githubusercontent.com/5589919/32295441-ac21b6cc-bf1f-11e7-8285-0205a2be90a2.png)
