### ISSUE TITLE
Inconsistent "Dashboard" button behavior before cluster imported

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#683]
In Cluster List page, the "Dashboard" button does not appear until after cluster has been successfully imported.  In the Hosts List page, the "Dashboard" button is greyed out and then is enabled once cluster is successfully imported.  Ideally, in the Hosts List page, the "Dashboard" button should not even appear until the cluster is successfully imported.

Clusters list - before import:
<img width="1198" alt="screen shot 2017-10-11 at 12 48 55 pm" src="https://user-images.githubusercontent.com/5589919/31461025-311c0818-ae96-11e7-9035-e9073ef05973.png">

Hosts list - before import:
<img width="984" alt="screen shot 2017-10-11 at 12 51 13 pm" src="https://user-images.githubusercontent.com/5589919/31461033-35aea6ba-ae96-11e7-8bc9-95476878fe51.png">

Clusters list - after import
<img width="1162" alt="screen shot 2017-10-11 at 1 31 48 pm" src="https://user-images.githubusercontent.com/5589919/31461072-56c977a8-ae96-11e7-8b63-43bbe995e362.png">

@gnehapk @Tendrl/tendrl-qe @a2batic @cloudbehl @mcarrano

**Comment by cloudbehl** [comment]
@julienlim The Issue is fixed with the new builds. Please verify.

**Comment by julienlim** [comment]
@cloudbehl @Tendrl/tendrl-qe 
Verified fix.

![screen shot 2017-10-18 at 1 38 34 pm](https://user-images.githubusercontent.com/5589919/31734176-dc5c57d0-b40b-11e7-9a51-a03cbff683c3.png)
