### ISSUE TITLE
Text and icon alignment issues

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#685]
Breadcrumbs text is not aligned.
Brick status icon not aligned with the brick path text (almost like a superscript to the brick path
Horizontal line bar also slightly offset (higher)

<img width="1157" alt="screen shot 2017-10-11 at 9 07 56 pm" src="https://user-images.githubusercontent.com/5589919/31474643-013d2792-aeca-11e7-8ec9-d169f58725fc.png">
)

@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by cloudbehl** [comment]
@julienlim The Issue is fixed with the new builds. Please verify.

**Comment by julienlim** [comment]
@cloudbehl @Tendrl/tendrl-qe Verified fix.

![screen shot 2017-10-18 at 1 56 39 pm](https://user-images.githubusercontent.com/5589919/31734285-3977b02c-b40c-11e7-8289-75ab1b3f2364.png)
