### ISSUE TITLE
Cluster List: "Details" button should be the first button, followed by Dashboard, Disable Profiling

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#686]
Cluster List: "Details" button should be the first button, followed by Dashboard, Disable Profiling.  It's not consistent with the other views where the "Details" button is shown.  Also, it would be ideal for the buttons to not wrap.

<img width="1158" alt="screen shot 2017-10-11 at 9 22 11 pm" src="https://user-images.githubusercontent.com/5589919/31474707-6a18e4cc-aeca-11e7-87c2-483a3c78c3bb.png">

<img width="1159" alt="screen shot 2017-10-11 at 9 21 55 pm" src="https://user-images.githubusercontent.com/5589919/31474710-6d8b13fa-aeca-11e7-90f9-5ce5c00913d7.png">

<img width="1158" alt="screen shot 2017-10-11 at 9 22 02 pm" src="https://user-images.githubusercontent.com/5589919/31474711-6fdb0066-aeca-11e7-9da2-14784559ba20.png">

@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by cloudbehl** [comment]
@julienlim The Issue is fixed with the new builds. Please verify.

**Comment by julienlim** [comment]
@cloudbehl @Tendrl/tendrl-qe 

Confirming fix.
![screen shot 2017-10-18 at 1 52 05 pm](https://user-images.githubusercontent.com/5589919/31734112-a2fc4d9c-b40b-11e7-9ab1-51453f2c914c.png)
