### ISSUE TITLE
node4 (which has an alert) indicates no alerts in other views (e.g. Hosts List)

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#687]
node4 (which has an alert saying it's disconnected/down) indicates no alerts (No Data) in other views (e.g. Hosts List).

<img width="1074" alt="screen shot 2017-10-11 at 9 24 54 pm" src="https://user-images.githubusercontent.com/5589919/31474755-c76039d2-aeca-11e7-8b8a-66cfbb7b07f0.png">

<img width="1074" alt="screen shot 2017-10-11 at 9 25 03 pm" src="https://user-images.githubusercontent.com/5589919/31474758-c9b82280-aeca-11e7-8cf8-b2e039f4835f.png">

@gnehapk @cloudbehl @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by cloudbehl** [comment]
Linking: https://github.com/Tendrl/node-agent/issues/643

**Comment by GowthamShanmugam** [comment]
@cloudbehl peer connected and disconnected is cluster level alerts, it won't show the count in host page

**Comment by GowthamShanmugam** [comment]
Actually, the alert is peer connected to disconnected, so we are handling this alert as cluster level alert only, so we just increasing cluster alert count by 1. We are not increasing node alert count by 1.

**Comment by julienlim** [comment]
@GowthamShanmugam @cloudbehl @gnehapk @Tendrl/tendrl-qe @mcarrano 
It seems that if something happened on a node, that the node would have the associated alert.  If it's a cluster alert, right now, there appears no place in the UI that we show the alert on the cluster beyond in this Alerts page.

Do we even generate alerts at the volume or node level currently?  I've yet to see the Alerts column in the Tendrl UI actually show any alerts for the node or volume.

Right now, when I have a brick that is more than 90% utilized (capacity), it should generate some kind of alert, that should be associated with the host and volume.  I did not see any alerts generated, and when I did previously see an threshold alert generated, it didn't associate the alert with the node or volume.

**Comment by GowthamShanmugam** [comment]
As per current implementation the alert count increment will work like this,

-- alerts which are related to nodes:
       Cpu utilization alert
       Memory utilization alert
       Swap utilization alert

When these alerts are raised, then the node alert count is incremented for a particular node.

-- cluster related alerts:
     Cluster utilization alert
     Volume utilization alert
     Brick utilization alert
     Volume status alert
     Brick status alert 
     Peer status alert
     Rebalance status alert 
    Georeplication status alert  
    Quorum of volume lost
    Quorum of volume regained
    Svc  connected
    Svc disconnected
    Minimum number of bricks not up in EC subvolume
   Minimum number of bricks up in  EC subvolume
   Afr quorum met for subvolume 
   Afr quorum fail for subvolume
   Afr subvolume up
   Afr subvolume down


When these alerts are raised, then the cluster alert count is incremented for a particular cluster,  Also if the alert is cluster alert and related to volume then volume alert count is also incremented for a particular volume.

(https://docs.google.com/document/d/1vUHep-jc2oSg7bJ2oU57DcC8JiZ33ofqPLBZ9A5pPt8/edit)

In the earlier release, i am done some mistake in alert type checking so all alert is stored in node level only. that is why you saw when the brick alert came then alert is created for the node. Now for node related alerts CPU, memory, swap only considered as node level alert. for this only, i am incrementing node level alert counts.


@r0h4n @nthomas-redhat @shtripat @anmolbabu Now for brick related alerts i am only incrementing only cluster alert by 1.  i am not incrementing volume alert count and node alert count. is this required?
Now i am incrementing only for volume related alert both cluster and vloume alert counts

which is correct way need suggestion.

**Comment by gnehapk** [comment]
@GowthamShanmugam Is this issue fixed?

**Comment by GowthamShanmugam** [comment]
@gnehapk this issue is fixed Tendrl/monitoring-integration/pull/219

**Comment by gnehapk** [comment]
@julienlim Please verify this issue.
