### ISSUE TITLE
Missing icons for nodes that are down

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#691]
In my setup I have not yet imported cluster with 6 nodes. `fbalak-usm1-gl6` node is `up` the rest of them is `down`. I have clicked on cluster on `Clusters` page. Next to `fbalak-usm1-gl6` node is a green icon indicating `up` status of the node. There are missing icons that indicate status of node next to nodes that are `down`. On `Hosts` page it seems ok.

![1012_no_icon](https://user-images.githubusercontent.com/22369801/31484834-176abb02-af32-11e7-9e02-84b97054d69d.png)

Tested with:
```
tendrl-notifier-1.5.3-20171011T200310.3c01717.noarch
tendrl-grafana-plugins-1.5.3-20171012T072405.9cb211a.noarch
tendrl-monitoring-integration-1.5.3-20171012T072405.9cb211a.noarch
tendrl-api-httpd-1.5.3-20171011T200630.494b1eb.noarch
tendrl-commons-1.5.3-20171011T195629.890684b.noarch
tendrl-api-1.5.3-20171011T200630.494b1eb.noarch
tendrl-ui-1.5.3-20171012T073358.7df67fb.noarch
tendrl-ansible-1.5.3-20171009T123017.9a9a956.noarch
tendrl-node-agent-1.5.3-20171011T195654.c8b5946.noarch
```

**Comment by a2batic** [comment]
@fbalak, Similar issue: Tendrl-bug-id: #664. Hence closing it.
