### ISSUE TITLE
Filter Bars non-linear dimensions and Input Hint Text Style Imrovements

### ISSUE THREAD

**Issue by rghatvis** [Tendrl/ui#694]
Issue 1
Filter Bars
The Attribute Selector bar is not aligned with the Filter Query Field bar. The dimensions of both the bars are not linear/consistent. In the PatternFly Filter Bar design page[1], both the bars are linear without any overlap and equal height. The following screen is captured from the Hosts menu of the Tendrl UI but it can be seen in all the menus of the UI. 

![filter-bars-dimensions](https://user-images.githubusercontent.com/16681357/31550648-b1fe4c42-b04f-11e7-98b2-c84a2fa38119.png)

Is this deliberately done to achieve some UX purpose? It is not conforming to the PatternFly design and also not giving a linear look and feel. 

Reference:
[1] PatternFly Filter Bar designs
http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design

Issue 2
The input hint text in the Filter Query Field bar should be changed to sentence-style capitalization and the labels should be capitalized. Also, the ellipsis is not required. 
Example:
For Name: Filter By name... change to **Filter by Name**
For Cluster: Filter By cluster_name... change to **Filter by Cluster name**
For Role: Filter By role... change to **Filter by Role**
For Status: Filter By status... change to **Filter by Status**

References:
[2] Discussions and outcome
https://github.com/patternfly/patternfly-design/issues/246 https://patternfly.atlassian.net/browse/PTNFLY-2583

Tested on Tendrl version:

tendrl-api-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-api-httpd-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-commons-1.5.2-20170926T081245.0fa5e25.noarch
tendrl-grafana-plugins-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-monitoring-integration-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-node-agent-1.5.2-20170926T090753.09d1818.noarch
tendrl-notifier-1.5.2-20170926T102449.7678c47.noarch
tendrl-ui-1.5.2-20170926T100141.770936f.noarch

**Comment by a2batic** [comment]
@rghatvis, Thanks for reporting this issue. We will be solving this bug, but patternfly also seems to have dimension issues in filter[1].
[1] http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#/code

**Comment by a2batic** [comment]
@rghatvis We are planning to upgrade the patternfly to its latest version[1] in next dev cycle and this version will fix the placeholder text bug. Upgrading the Patternfly version right now can create a race around conditions(tried upgrading the version the date pickers and the notifications stopped working). We don't know the exact impact of the upgrade but we are sure that the upgrade will hamper. 
[1] http://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter

**Comment by a2batic** [comment]
@rghatvis, it has been fixed with tendrl-ui-1.5.3-20171023T065857.0c58708.noarch.rpm (latest master build). The filters are now consistent and aligned. Please verify.

**Comment by julienlim** [comment]
Related to https://github.com/Tendrl/ui/issues/638.

**Comment by julienlim** [comment]
@a2batic @gnehapk @rghatvis @mcarrano 

In looking at Tendrl UI in both Chrome and Firefox, the fix appears to have better/closer alignment with PatternFly but they do seem to vary from browser to browser.

Chrome:
![screen shot 2017-10-31 at 1 49 54 pm](https://user-images.githubusercontent.com/5589919/32331800-39564d42-bfba-11e7-887b-e3e22767f1c1.png)

Firefox:
<img width="1218" alt="screen shot 2017-11-02 at 10 38 06 am" src="https://user-images.githubusercontent.com/5589919/32331825-48ab184a-bfba-11e7-80d9-77ee840f8ad9.png">

**Comment by rghatvis** [comment]
Thanks for sharing the rendering on different browsers, Ju. The input hint text has changed to sentence-style capitalization which is cool but not sure why there is variation in the browsers...

**Comment by julienlim** [comment]
@rghatvis - there should not be difference in rendering in different browsers if we're using the latest PatternFly.

@a2batic @gnehapk - comments about the rendering in different browsers?

@mcarrano

**Comment by a2batic** [comment]
@julienlim @rghatvis, It seems to be a bug

**Comment by a2batic** [comment]
@julienlim @rghatvis, the bug has been fixed with tendrl-ui-1.5.4-20171107T133229.ed61125.noarch.rpm (latest master build). Please verify.

**Comment by rghatvis** [comment]
@a2batic: Verified in tendrl-ui-1.5.4-20171107T133229.ed61125.noarch.rpm. Thanks!
