### ISSUE TITLE
Brick Details: Table headings touching line, not following PatternFly table guidelines

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#699]
Table headings for the bricks text alignment is off.  Specifically, the text (Host Name, Brick Path, Utilization, ...) doesn't appear to have any vertical line spacing before the horizontal line.

![screen shot 2017-10-18 at 2 06 27 pm](https://user-images.githubusercontent.com/5589919/31734992-72159cb2-b40e-11e7-9874-2eba759bc803.png)

Per [design](https://redhat.invisionapp.com/share/XMAOW3UC5#/screens/221662346), it was a table.
![screen shot 2017-10-18 at 2 15 09 pm](https://user-images.githubusercontent.com/5589919/31735092-c66045b0-b40e-11e7-86d4-a7a23860b082.png)

Implementation looks more list a list view with headings added.  If list view instead (then no need to have the alternating grey bar effect of the table, or table headings in grey).  Am okay with the list view implementation but would like that the list headers to be better aligned.

@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by julienlim** [comment]
@a2batic It looks much better with the table fix.

![screen shot 2017-10-31 at 1 57 23 pm](https://user-images.githubusercontent.com/5589919/32306574-9dba971a-bf52-11e7-92cd-8ddf32f3e41e.png)

**Comment by gnehapk** [comment]
@julienlim Since this issue is fixed, closing it. Please open it, if required.
