### ISSUE TITLE
Import Cluster infotip - text improvement

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#700]
The import cluster infotip text ought to be shorter and less verbose.  I appreciate that it's implemented per annotations specified in design, but it ought to be less verbose.

Can we leave off the bullet, and update the text to show:

Enabling volume profiling enables volume-level telemetry information to help with troubleshooting, capacity planning, and performance thing.

@gnehapk @a2batic @cloudbehl @mcarrano 

@rghatvis@redhat.com - Is this text okay with you?

Here's what it looks like right now:
![screen shot 2017-10-18 at 1 40 15 pm](https://user-images.githubusercontent.com/5589919/31735382-bd406e82-b40f-11e7-99ba-83df410c0ed2.png)

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.3-20171024T073937.0815acd.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Issue resolved.  See Firefox screenshot.

![screen shot 2017-10-24 at 2 02 44 pm](https://user-images.githubusercontent.com/5589919/31960546-248c556e-b8c6-11e7-8b00-1c0984799ffe.png)
