### ISSUE TITLE
Change the color coding of Progress bar as per the threshold breach.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ui#701]
If the progress bar has reached to 80% and above it should be changed to yellow and if reaches to 90% or above it should be changed to Red.

Linking: https://github.com/Tendrl/monitoring-integration/issues/194

**Comment by gnehapk** [comment]
@cloudbehl Fixed with tendrl-ui-1.5.3-20171024T073937.0815acd.noarch.rpm. Please verify.
