### ISSUE TITLE
"Ready to import" text should say "Importing cluster" when cluster is being imported, and Import button is disabled

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#707]
"Ready to import" text should say "Importing cluster" when cluster is being imported, and Import button is disabled -- see screenshot below (note 2nd row where "Import" button is disabled):

![screen shot 2017-10-24 at 2 06 11 pm](https://user-images.githubusercontent.com/5589919/31998675-a30309e0-b95e-11e7-9035-799fc92d56f5.png)

@gnehapk @a2batic @mcarrano @Tendrl/tendrl-qe

**Comment by a2batic** [comment]
@julienlim, it has been fixed with tendrl-ui-1.5.3-20171027T071719.c55fbe7.noarch.rpm (latest master build). Please verify.

**Comment by julienlim** [comment]
Just installed Tendrl 1.5.4, and this fix is verified.
<img width="1262" alt="screen shot 2017-11-03 at 12 28 18 pm" src="https://user-images.githubusercontent.com/5589919/32384850-9bee732a-c092-11e7-9894-ca179aead4b9.png">
