### ISSUE TITLE
Mystery jobs in Notifications

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#708]
I've only executed "Import" cluster once, and as you can see in the screenshot that it ran successfully.  However, in the Notifications view, I see 4 jobs that have run, when only 1 job was user executed, i.e. Import Cluster.

It would be surprising to the user to see additional jobs run.

<img width="1134" alt="screen shot 2017-10-25 at 8 27 11 am" src="https://user-images.githubusercontent.com/5589919/31998779-fc755d2a-b95e-11e7-9a03-32d2d0b852cf.png">

@gnehapk @cloudbehl @a2batic @mcarrano @Tendrl/tendrl-qe

**Comment by gnehapk** [comment]
@julienlim Please share the response for "/notifications" received.

**Comment by julienlim** [comment]
$ curl -XGET -H "Authorization: Bearer 9d8961cd999d1aaa622f6affca33738ae9cb1e2889e17f98306a665dc59e0380" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/notifications

[{"message_id":"9c8d79fc-26ff-41b4-8a42-1e1d8adad68b","timestamp":"2017-10-25T12:42:06.120833+00:00","priority":"notice","message":"Job failed (job_id: 0a2f6388-f9bd-40a8-8748-b8430fde440d)"},{"message_id":"b45b13c3-8ce8-4968-a4ec-151218b453a2","timestamp":"2017-10-25T12:27:22.369224+00:00","priority":"notice","message":"Status of peer: node3 changed from Connected to Disconnected"},{"message_id":"ad56d256-ed10-46bb-8a57-55282ac6e51f","timestamp":"2017-10-25T12:26:45.911563+00:00","priority":"notice","message":"Job failed (job_id: e228f6b5-56c1-4814-b741-7a821cadda9b)"},{"message_id":"7b49f4a8-9b71-43b0-a91a-1451be09c4d7","timestamp":"2017-10-24T18:13:42.826902+00:00","priority":"notice","message":"Job finished successfully (job_id: f3801f44-9ea9-4c11-92e8-52ea16336a67)"},{"message_id":"aa50de0a-d36f-4819-a4c2-7e58a3d48fa1","timestamp":"2017-10-24T18:13:42.278115+00:00","priority":"notice","message":"Job finished successfully (job_id: 2963fb63-a624-41db-b0df-c197ffc3fbd6)"},{"message_id":"19160f6f-2963-4c55-95dc-c926bc6771bc","timestamp":"2017-10-24T18:09:19.812549+00:00","priority":"notice","message":"Job finished successfully (job_id: 0516a7a3-346f-4783-96a0-bbbb81f9feb3)"}]

@gnehapk

**Comment by gnehapk** [comment]
@r0h4n @nthomas-redhat @shtripat @anivargi Since there are four notification objects present in the API response, UI is displaying 4 jobs in the notification list. Please have a look.

**Comment by shtripat** [comment]
During import job, it creates additional child jobs for other nodes as well. These entries in job list are for them. For end user perspective we may need to display only the parent job and hide all the dependent child jobs if its confusing.

There are many jobs in tendrl which create internal child jobs.

**Comment by gnehapk** [comment]
@shtripat Can you please mention the property name which tells the UI that this is a parent job, so that UI can add filter for it.

**Comment by shtripat** [comment]
In https://github.com/Tendrl/ui/issues/708#issuecomment-339554181 I talked about job. I feel the issue here is talking about notifications only in top right corner.

I just verified in a setup and during import only one notifications is created for the parent import job.

@julienlim please share the setup details as I am not able to simulate the issue at my end.

**Comment by julienlim** [comment]
@shtripat Setup was via tendrl-ansible.  I've reinstalled since I logged this bug, but it's still evident in my latest Tendrl deployment.  Based on comments above, the internal child jobs are being shown and should be suppressed from being shown, i.e. filtered out to only show parent jobs - so user is not "surprised" to see additional jobs that he/she is unaware of the internal Tendrl workings.

**Comment by shtripat** [comment]
I tried this today in a fresh setup as see notification about success of parent job only. Under Tasks, yes child jobs also are listed, but under Notification in top right corner you should see only the entry for success of parent import job.

If you see the issue again, kindly share the setup details with me before removing it. Lets debug and see as I dont see this my setup. We can have BJ setup for the same.

**Comment by gnehapk** [comment]
@julienlim Please close this issue if it is not reproducible any more.

**Comment by julienlim** [comment]
@gnehapk I am no longer seeing this with Tendrl 1.5.5.
