### ISSUE TITLE
Additional instance of node3 in the host list with wrong status

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#709]
I just powered down node3, and now I see 2 node3's in the Host List.  The Cluster List reflects node3 correctly.

<img width="1150" alt="screen shot 2017-10-25 at 8 34 03 am" src="https://user-images.githubusercontent.com/5589919/31998901-732e19ca-b95f-11e7-98fc-e0e641298716.png">

<img width="1144" alt="screen shot 2017-10-25 at 8 34 19 am" src="https://user-images.githubusercontent.com/5589919/31998906-75b91604-b95f-11e7-9f1b-8ec903165feb.png">

@gnehapk @a2batic @cloudbehl @mcarrano @Tendrl/tendrl-qe

**Comment by gnehapk** [comment]
@julienlim Please share the response of "/nodes" received on host list page.

**Comment by julienlim** [comment]
$ curl -XGET -H "Authorization: Bearer 9d8961cd999d1aaa622f6affca33738ae9cb1e2889e17f98306a665dc59e0380" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/nodes

{"nodes":[{"updated_at":"2017-10-25 12:59:44.435546+00:00","node_id":"cfd77186-c29c-42e8-9af9-d27d57abec5c","last_sync":"2017-10-25 12:59:44.420103+00:00","status":"UP","hash":"3980b7e2d8aff6c4b2769af0d0b93649","tags":["tendrl/node_cfd77186-c29c-42e8-9af9-d27d57abec5c","tendrl/integration/monitoring","tendrl/integration/0aed2ff6-255f-40cd-ab07-f897dab424f0","tendrl/central-store","gluster/server","detected_cluster/d5127c66922660968bcf4d7b7230c8de832e817fbef0790bf41e82f271d60e8f","tendrl/server","tendrl/monitor","tendrl/node"],"sync_status":"done","fqdn":"node0","cluster":{"integration_id":"0aed2ff6-255f-40cd-ab07-f897dab424f0","hash":"163b9f1423b421826d477249b8831d35","sds_version":"3.12.1","updated_at":"2017-10-24 17:56:48.859350+00:00","sds_name":"gluster","cluster_name":"gluster-d5127c66922660968bcf4d7b7230c8de832e817fbef0790bf41e82f271d60e8f","cluster_id":"d5127c66922660968bcf4d7b7230c8de832e817fbef0790bf41e82f271d60e8f"}},{"last_sync":"2017-10-25 13:01:02.383193+00:00","status":"UP","hash":"56f429cd0826f5e367baf8c2920e3db4","tags":["tendrl/node_458fdad6-2eb4-41fc-a291-89b866c7f917","detected_cluster/12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","tendrl/integration/abb35e28-a0dc-49aa-a35f-4d77553e2936","tendrl/integration/gluster","gluster/server","tendrl/node"],"sync_status":"done","fqdn":"node1","updated_at":"2017-10-25 13:01:02.401336+00:00","node_id":"458fdad6-2eb4-41fc-a291-89b866c7f917","cluster":{"sds_version":"3.12.1","updated_at":"2017-10-24 17:56:43.274615+00:00","sds_name":"gluster","cluster_name":"gluster-12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","cluster_id":"12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","integration_id":"abb35e28-a0dc-49aa-a35f-4d77553e2936","hash":"26ff43f1c26d56ad2804c5b04eb76573"}},{"tags":["tendrl/integration/gluster","detected_cluster/12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","provisioner/abb35e28-a0dc-49aa-a35f-4d77553e2936","tendrl/integration/abb35e28-a0dc-49aa-a35f-4d77553e2936","tendrl/node_1bbff820-1e8b-4c9d-a864-813eac1a44a5","gluster/server","tendrl/node"],"sync_status":"done","fqdn":"node2","updated_at":"2017-10-25 13:01:46.588494+00:00","node_id":"1bbff820-1e8b-4c9d-a864-813eac1a44a5","last_sync":"2017-10-25 13:01:46.567940+00:00","status":"UP","hash":"cd3facff9e2943fbf33c4ecbcd5a63e1","cluster":{"cluster_id":"12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","integration_id":"abb35e28-a0dc-49aa-a35f-4d77553e2936","hash":"26ff43f1c26d56ad2804c5b04eb76573","sds_version":"3.12.1","updated_at":"2017-10-24 17:56:42.865248+00:00","sds_name":"gluster","cluster_name":"gluster-12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8"}},{"updated_at":"2017-10-24 17:55:55.601875+00:00","node_id":"d82eaa95-2aa1-4cfe-b8d7-14e6536cf412","last_sync":"","status":"UP","hash":"6bbfe268319bca96a390b76ccdaf903f","tags":["tendrl/node_d82eaa95-2aa1-4cfe-b8d7-14e6536cf412","detected_cluster/12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","tendrl/integration/abb35e28-a0dc-49aa-a35f-4d77553e2936","tendrl/node"],"sync_status":"","fqdn":"node3","cluster":{"hash":"26ff43f1c26d56ad2804c5b04eb76573","sds_version":"3.12.1","updated_at":"2017-10-24 17:55:55.406252+00:00","sds_name":"gluster","cluster_name":"gluster-12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","cluster_id":"12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","integration_id":"abb35e28-a0dc-49aa-a35f-4d77553e2936"}},{"status":"DOWN","hash":"534e45b5a45fc4060aa52d939efaf4d9","tags":["tendrl/node_9415713c-32e3-4f62-8b2e-752623e7713b","tendrl/integration/gluster","detected_cluster/12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","tendrl/integration/abb35e28-a0dc-49aa-a35f-4d77553e2936","gluster/server","tendrl/node"],"sync_status":"done","fqdn":"node3","updated_at":"2017-10-25 12:24:07.680655+00:00","node_id":"9415713c-32e3-4f62-8b2e-752623e7713b","last_sync":"2017-10-25 12:24:07.660738+00:00","cluster":{"updated_at":"2017-10-24 17:56:45.662154+00:00","sds_name":"gluster","cluster_name":"gluster-12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","cluster_id":"12d05ba1c3c2b4b1b1c7e8b9cf6fc5187b9febd71c09e46f161969441be707f8","integration_id":"abb35e28-a0dc-49aa-a35f-4d77553e2936","hash":"26ff43f1c26d56ad2804c5b04eb76573","sds_version":"3.12.1"}}]}[root@node0 tendrl-ansible]

@gnehapk

**Comment by gnehapk** [comment]
@r0h4n @nthomas-redhat @shtripat  @anivargi There are two objects which has same fqdn -> "node3" received in the API response. Please check

**Comment by shtripat** [comment]
@r0h4n looks like while NodeContext.status is marked DOWN, there is an additional entry for the same node in etcd with different node_id. Please check.

**Comment by gnehapk** [comment]
@nthomas-redhat @shtripat @r0h4n @GowthamShanmugam Please close this issue it it is fixed.
