### ISSUE TITLE
Missing volume name

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#711]
Currently using the build that current tendrl-ansible is using (Tendrl 1.5.3 release).

From cluster details view, it is missing the volume name (vol1) in the volume listing:

<img width="1210" alt="screen shot 2017-10-25 at 3 33 31 pm" src="https://user-images.githubusercontent.com/5589919/32019168-548d101c-b99a-11e7-8681-e36d54cb66db.png">

Interestingly, when you go to the volume drilldown, it shows what I assume is the volume unique identifier:

<img width="1210" alt="screen shot 2017-10-25 at 3 34 26 pm" src="https://user-images.githubusercontent.com/5589919/32019200-6801df9c-b99a-11e7-8226-10cad1837c53.png">

gstatus -a output:
<img width="612" alt="screen shot 2017-10-25 at 3 38 38 pm" src="https://user-images.githubusercontent.com/5589919/32019263-9e5e99d6-b99a-11e7-944f-93bb6dfda372.png">

@gnehapk @a2batic @cloudbehl @mcarrano @Tendrl/tendrl-qe

**Comment by mbukatov** [comment]
This seems to be the same issue as reported in https://github.com/Tendrl/api/issues/324

**Comment by shtripat** [comment]
@julienlim can you share the setup details in a mail. Will have a look.

**Comment by gnehapk** [comment]
@julienlim Please close this issue if it is not reproducible anymore with the latest builds.

**Comment by julienlim** [comment]
I've not observed this with the latest builds, so I'll close this issue.
