### ISSUE TITLE
Extra punctuation on empty slate (landing) pages

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#716]
For empty / blank slate (landing) pages, there should not be a period at the end of the Empty State Title per PatternFly -- see https://www.patternfly.org/pattern-library/communication/empty-state/.

E.g. No Alerts Detected or No Tasks Detected -- remove period at the end of the title.

See Alerts and Tasks empty slate pages below:

![screen shot 2017-10-31 at 1 50 25 pm](https://user-images.githubusercontent.com/5589919/32240184-02be811e-be43-11e7-8b0b-f7b249781c5b.png)

![screen shot 2017-10-31 at 1 50 34 pm](https://user-images.githubusercontent.com/5589919/32240186-03fe103a-be43-11e7-9080-ebd6f718ead6.png)

@gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.4-20171106T121612.853b7e1.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
@gnehapk This hasn't been fixed.  See below:

<img width="1266" alt="screen shot 2017-11-20 at 10 49 22 pm" src="https://user-images.githubusercontent.com/5589919/33087399-7bd8da1a-ceb8-11e7-8311-068b67170672.png">

<img width="1267" alt="screen shot 2017-11-20 at 10 49 32 pm" src="https://user-images.githubusercontent.com/5589919/33087402-7fae3a5e-ceb8-11e7-9345-234b92ae8c35.png">

**Comment by a2batic** [comment]
@julienlim, This issue has been fixed with the latest master tendrl-ui-1.6.0-20180223T121254.729004b.noarch.rpm, please verify
