### ISSUE TITLE
Volume Details - visual changes suggested

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#717]
In looking at brick details, it's hard to see the utilization chart on the grey background.  We'd suggest changing the fill of the chart background to white.

Before (Current implementation):
![screen shot 2017-10-31 at 1 57 23 pm](https://user-images.githubusercontent.com/5589919/32247407-9d7f9ff2-be58-11e7-8286-e0e0fc4c021d.png)

After (Suggested change):
![screenshot-172 28 128 3-2017-10-31-16-26-51-153](https://user-images.githubusercontent.com/5589919/32247410-a073aa28-be58-11e7-95e7-66b14d27ba07.png)

@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.4-20171106T121612.853b7e1.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Confirmed fix.
