### ISSUE TITLE
Extra line at bottom of page for blank slate

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#725]
For Alerts and Tasks, when there are no alerts or tasks respectively, there's a line that appears at the bottom of the page that should not be there (after No Alerts / Tasks Detected)

![screen shot 2017-10-24 at 2 05 33 pm](https://user-images.githubusercontent.com/5589919/32334369-adc51806-bfc0-11e7-982c-725f31923c4f.png)

![screen shot 2017-10-31 at 1 50 34 pm](https://user-images.githubusercontent.com/5589919/32334441-d3b36676-bfc0-11e7-909e-3f5ec42b9974.png)

@gnehapk @a2batic @mcarrano

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.4-20171106T121612.853b7e1.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
@gnehapk I hope you fixed this for the other places where the blank slate appears too, e.g. Volumes.
![screen shot 2017-11-06 at 9 21 53 am](https://user-images.githubusercontent.com/5589919/32446545-41cc03f2-c2d7-11e7-90f5-3f6dbe249360.png)

Thanks!

**Comment by gnehapk** [comment]
@julienlim Fixed with tendrl-ui-1.5.4-20171107T074153.cccca1d.noarch.rpm. Please verify.

**Comment by julienlim** [comment]
Confirmed fix.
