### ISSUE TITLE
Various status of bricks and corresponding icons

### ISSUE THREAD

**Issue by a2batic** [Tendrl/ui#728]
It is observed, that volumes and bricks have other status too, other than 'Started' and 'Stopped'. One of the other status is 'Created'. We have used 'pficon-ok' for 'Started' and 'pficon-error-circle-o' for 'Stopped'. @nnDarshan what are the other status that can come for volumes and bricks ? @julienlim, what icons should we use for other status?
Attachment: Screenshot with volume status ' Created'

![screenshot from 2017-11-06 18-11-55](https://user-images.githubusercontent.com/12200504/32444949-2eb503e8-c2fc-11e7-9bfa-80b58efd0448.png)

**Comment by mcarrano** [comment]
After some discussion, here are our UX recommendations:

* For volumes/bricks that are running and healthy, let's stick with the green 'fa-check-circle-o'
* Volumes/bricks (and any objects) that are down should use 'fa-arrow-circle-o-down' (not error-circle-o)
* Volumes/bricks that are newly created (not yet started) should use 'pficon-connected'
* Volumes/bricks that are stopped should use 'fa-stop-circle-o'

@julienlim FYI

**Comment by nnDarshan** [comment]
@a2batic
* Volume possible status {"Created",  "Started",  "Stopped" }
* Brick possible status {"Started",  "Stopped"}

**Comment by a2batic** [comment]
@mcarrano @julienlim, since we dont have a 'down' status for volumes/bricks, as per @mcarrano comment, following icons can be used:-

- 'Started' - green 'fa-check-circle-o'
- 'Created' - 'pficon-connected'
- 'Stopped' -  'fa-stop-circle-o'

**Comment by gnehapk** [comment]
@mcarrano @julienlim The color of `fa-check-circle-o` ,`fa-stop-circle-o` icons is dark grey. Do we need to change the color or dark grey is fine.

**Comment by mcarrano** [comment]
'Started' should be the green checkmark as is shown today. I may have made an error when I called out 'fa-check-circle-o' as we also have 'pficon-ok'. Whatever we are currently using to reflect the OK status in various views is what we should continue to use.  'Stop' can be dark grey.

Sorry if I caused some confusion.

**Comment by julienlim** [comment]
@gnehapk See above comment from @mcarrano

**Comment by gnehapk** [comment]
@mcarrano 'pficon-connected" icon is introduced in later version of patternfly 3.25.0. Currently we are using 3.25.0 patternfly's version. Can you suggest some other icon in place of 'pficon-connected".

We are planning to upgrade patternfly version in next development cycle.

**Comment by mcarrano** [comment]
@gnehapk If that is the case, let's go with 'fa-arrow-circle-o-up' to indicate that the volume has been created, but not yet started. Keep the color as dark gray. Does that work?

**Comment by gnehapk** [comment]
@mcarrano Yes. Thanks.

**Comment by a2batic** [comment]
Fixed with tendrl-ui-1.5.4-20171110T074803.fb3f1b1.noarch.rpm.

**Comment by julienlim** [comment]
Just summarizing what was decided for icons for volumes and bricks:

* 'Started' - green 'fa-check-circle-o’, green checkmark
* ’Created' - 'pficon-connected' (if newer PatternFly used) initially recommended, but not available so ended up going with fa-arrow-circle-o-up (older PatternFly used), dark grey
* 'Stopped' - 'fa-stop-circle-o’, dark grey

For anything that's OK - use what’s in place today.
