### ISSUE TITLE
Volume disappears from UI

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#729]
I deployed Tendrl 1.5.4 using tendrl-ansible in my vagrant environment, which has a 3 node Gluster trusted storage pool (tendrl-node-agents). 4 nodes in total if you include the Tendrl server.

I had my nodes go down unexpectedly when my host system crashed.  When I brought the VM's back up and running, Tendrl UI and API no longer seems to know about the Gluster volume that is present.

In Gluster, the volume is up and running just fine.

![screen shot 2017-11-06 at 9 21 13 am](https://user-images.githubusercontent.com/5589919/32449884-bbe7c730-c2e0-11e7-8c86-9c03bde0019f.png)

![screen shot 2017-11-06 at 9 21 37 am](https://user-images.githubusercontent.com/5589919/32449888-bd972620-c2e0-11e7-8c33-64ebd27a7b8c.png)

The Tendrl UI shows no volume present (and when I used the tendrl-api, it said no volumes as well):
![screen shot 2017-11-06 at 9 21 53 am](https://user-images.githubusercontent.com/5589919/32449900-cc530580-c2e0-11e7-88bf-7314d62ea422.png)

The Tendrl dashboard in Grafana seems to still know about it but it's not getting fully updated, i.e. statuses not updating but profilling information is getting updates.

![screen shot 2017-11-06 at 11 21 29 am](https://user-images.githubusercontent.com/5589919/32451427-bbc085c2-c2e4-11e7-9469-261ecefcdb39.png)

@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please share the API response.

**Comment by julienlim** [comment]
@gnehapk 

**# curl -XGET -H "Authorization: Bearer 7240301b9f12d45d7ce54c5fd1612bc9483ea343219cb7706ce23ce1eaeffc82" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/clusters**

{"clusters":[{"sds_name":"gluster","sds_version":"3.12.1","updated_at":"2017-11-03 16:20:42.237491+00:00","cluster_id":"cfac1062-a50d-44e2-bb89-4ce38db4e8ab","cluster_name":"gluster-9057b41460e5e2cad96bc4955e624c7e3c69d88fa1844d0445662dab359de393","hash":"10263de04999719e93addc9e2bef7ef1","integration_id":"cfac1062-a50d-44e2-bb89-4ce38db4e8ab","errors":[],"globaldetails":{"connection_active":"0","connection_count":"0","hash":"783ee5e5058b339b21c3fb2bd91ed4ea","peer_count":"3","status":"healthy","updated_at":"2017-11-03 16:30:19.549343+00:00","vol_count":"1","volume_up_degraded":"0"},"public_network":"","cluster_network":"","is_managed":"yes","enable_volume_profiling":"yes","import_status":"done","import_job_id":"24fef7dc-feb6-4910-9855-5a848d9edf0b","alert_counters":{"integration_id":"cfac1062-a50d-44e2-bb89-4ce38db4e8ab","updated_at":"2017-11-03 17:16:03.510088+00:00","warning_count":"2","hash":"39ef1f92a1104c474beb40cf2ab59718"},"nodes":[{"fqdn":"node2","hash":"b999ebc19bfb46c8be7c21002af02f88","last_sync":"2017-11-06 19:17:46.937936+00:00","node_id":"40c68e88-fc29-4b1b-ac76-6bdca2f64636","status":"UP","sync_status":"done","tags":["detected_cluster/9057b41460e5e2cad96bc4955e624c7e3c69d88fa1844d0445662dab359de393","tendrl/integration/gluster","gluster/server","tendrl/integration/cfac1062-a50d-44e2-bb89-4ce38db4e8ab","provisioner/cfac1062-a50d-44e2-bb89-4ce38db4e8ab","tendrl/node_40c68e88-fc29-4b1b-ac76-6bdca2f64636","tendrl/node"],"updated_at":"2017-11-06 19:17:47.019366+00:00","node_id":"40c68e88-fc29-4b1b-ac76-6bdca2f64636"},{"fqdn":"node1","hash":"1b0c283bb0dbaf318e39a78e58e860ef","last_sync":"2017-11-06 19:18:43.047129+00:00","node_id":"b078efe4-3d50-4212-92c0-b13c52c3fa00","status":"UP","sync_status":"done","tags":["detected_cluster/9057b41460e5e2cad96bc4955e624c7e3c69d88fa1844d0445662dab359de393","tendrl/integration/gluster","gluster/server","tendrl/integration/cfac1062-a50d-44e2-bb89-4ce38db4e8ab","provisioner/cfac1062-a50d-44e2-bb89-4ce38db4e8ab","tendrl/node_b078efe4-3d50-4212-92c0-b13c52c3fa00","tendrl/node"],"updated_at":"2017-11-06 19:18:43.152436+00:00","node_id":"b078efe4-3d50-4212-92c0-b13c52c3fa00"},{"hash":"78f87ef49b835907380cce1751c7acdd","last_sync":"2017-11-06 19:19:26.204671+00:00","node_id":"d76e952d-2a26-448a-968d-61d50f7cf2cf","status":"UP","sync_status":"done","tags":["detected_cluster/9057b41460e5e2cad96bc4955e624c7e3c69d88fa1844d0445662dab359de393","tendrl/integration/gluster","tendrl/node_d76e952d-2a26-448a-968d-61d50f7cf2cf","gluster/server","tendrl/integration/cfac1062-a50d-44e2-bb89-4ce38db4e8ab","tendrl/node"],"updated_at":"2017-11-06 19:19:26.282876+00:00","fqdn":"node3","node_id":"d76e952d-2a26-448a-968d-61d50f7cf2cf"}]}]}


**# curl -XGET  -H "Authorization: Bearer 7240301b9f12d45d7ce54c5fd1612bc9483ea343219cb7706ce23ce1eaeffc82" http://127.0.0.1/api/1.0/clusters/cfac1062-a50d-44e2-bb89-4ce38db4e8ab/volumes**

{"volumes":[]}

**Comment by r0h4n** [comment]
@julienlim Silly question, but when you brought the VM's back up and running did you start all the Tendrl services (tendrl-node-agent, tendrl-gluster-integration etc) ?

**Comment by julienlim** [comment]
@r0h4n I did check tendrl-node-agent and it is running on all nodes.  monitoring integration is running too.  tendrl-gluster-integration isn't -- so I assume that's the culprit.

I stared up tendrl-gluster-integration, and the volume did then show up in the Tendrl UI.

Do we have documented which daemons need to be running (to help with troubleshooting)?  If not, I'd strongly recommend we document which ones need to be running.

For Troubleshooting Guide, I'd suggest the following scenario:

(Q) Volume is not showing up in the Tendrl UI but visible in CLI, API and Dashboards.
(A) Ensure tendrl-node-agent and tendrl-gluster-integration are running on the storage node.

Thanks.

**Comment by mbukatov** [comment]
@julienlim 

> @r0h4n I did check tendrl-node-agent and it is running on all nodes. monitoring integration is running too. tendrl-gluster-integration isn't -- so I assume that's the culprit.

The daemon should be running. If this is a different root cause from what is described in on of: https://github.com/Tendrl/gluster-integration/issues/294 https://github.com/Tendrl/commons/issues/595 https://bugzilla.redhat.com/show_bug.cgi?id=1509314, you can create a new issue.

**Comment by julienlim** [comment]
@mbukatov The problem is indeed that tendrl-gluster-integration does not run after a reboot per https://bugzilla.redhat.com/show_bug.cgi?id=1509314.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/772  and https://github.com/Tendrl/commons/pull/773
