### ISSUE TITLE
rpmlint errors

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/ui#736]
The following are the rpmlint errors found in 1.5.4 release:

tendrl-ui.noarch: E: script-without-shebang /var/www/tendrl/commons/scss/main.css
tendrl-ui.noarch: E: script-without-shebang /var/www/tendrl/index.html
tendrl-ui.noarch: E: script-without-shebang /var/www/tendrl/plugin-bundle.js
tendrl-ui.noarch: W: incoherent-version-in-changelog 1.5.4-1 ['1.5.4-1.el7.centos', '1.5.4-1.centos']

**Comment by gnehapk** [comment]
@TimothyAsirJeyasing Please close this issue if its already done.
