### ISSUE TITLE
Event list design needs to have proper spacing and padding

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ui#740]
![screenshot from 2017-11-10 11-53-33](https://user-images.githubusercontent.com/6695156/32645554-d088cede-c60d-11e7-9275-bbb6e03ef4e5.png)

**Comment by a2batic** [comment]
@cloudbehl Fixed with tendrl-ui-1.5.4-20171110T074803.fb3f1b1.noarch.rpm. Please verify.
