### ISSUE TITLE
Some strange lines and disappearing lines

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#743]
The Events and Tasks list seem to have extra horizontal lines.

And the border (vertical line) for the Alerts drawer line partially disappears when drawer is "opened."

<img width="1171" alt="screen shot 2017-11-10 at 10 12 29 am" src="https://user-images.githubusercontent.com/5589919/32664612-d9a47490-c5ff-11e7-9053-51869ba087b9.png">

<img width="1172" alt="screen shot 2017-11-10 at 10 12 54 am" src="https://user-images.githubusercontent.com/5589919/32664622-e016a9c4-c5ff-11e7-86f9-a8202185eba8.png">

@gnehapk @a2batic @nthomas-redhat @Tendrl/tendrl-qe @mcarrano

**Comment by sankarshanmukhopadhyay** [comment]
Is this specific to a browser or, all browsers? I do not seem to see this on the latest Google Chrome stable on F26 and CentOS 7.4

**Comment by julienlim** [comment]
@sankarshanmukhopadhyay This was on Google Chrome on MacOS.  I didn't try FireFox.  Once I used a filter, the Alerts drawer vertical border was restored.  

<img width="1241" alt="screen shot 2017-11-10 at 10 34 58 am" src="https://user-images.githubusercontent.com/5589919/32665833-943ba4b0-c603-11e7-8e40-69f7cf122551.png">

**Comment by mcarrano** [comment]
The Events view should follow the same form as other list views in the product. There is a design for this here: https://redhat.invisionapp.com/share/8QCOEVEY9#/244738616_Cluster_Details-Events. There should not be a need for the header row, but we should have a filter toolbar at the top as for Tasks.

**Comment by a2batic** [comment]
@julienlim, can you please explain about which horizontal line are you referring here? It will be better if you mark that particular line in the attachment.

@julienlim @mcarrano, can you please provide the updated mockup for events page with required changes.

**Comment by julienlim** [comment]
@a2batic The following shows where the extra horizontal line is -- see Tasks screenshot below:
![tasks - extra line](https://user-images.githubusercontent.com/5589919/32731223-40e501ac-c857-11e7-90ae-6e960b117672.png)

This was similar in the Events list as well.  If you remove the column headers (Description, Timestamp) row, you'll get as close to design as you can based on what the API returns currently:
![chrome events](https://user-images.githubusercontent.com/5589919/32731332-853cccae-c857-11e7-97c0-0b6821ee15b4.png)

**Comment by a2batic** [comment]
@julienlim @mcarrano, this bug has been fixed with tendrl-ui-1.5.4-20171121T111815.8f8f468.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
Closing this issue, as its been opened for quite long time. Please feel free to reopen if the issue still persists.
