### ISSUE TITLE
Event messages are getting truncated

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#745]
Event messages are getting truncated and require user to hover to see the truncated description.

It ought to wordwrap (like Task Details) and not truncate.

Event List:
<img width="1090" alt="screen shot 2017-11-10 at 12 00 22 pm" src="https://user-images.githubusercontent.com/5589919/32669507-c700f2a0-c60e-11e7-81ff-651937a3f01e.png">

Task Details:
<img width="1075" alt="screen shot 2017-11-10 at 11 59 13 am" src="https://user-images.githubusercontent.com/5589919/32669484-b5dd6346-c60e-11e7-97c1-ce2578814daf.png">

It would be preferable to show the full text without hovering so as to avoid having to use the API to see the full text.

Events list design can be found at: https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738616.

Note: There is no need for the column heading per design as well.

Note: Similar to the [Full alert message not visible to user without hovering on the message](https://github.com/Tendrl/ui/issues/744).

@gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by julienlim** [comment]
See also comments in https://github.com/Tendrl/ui/issues/743#issuecomment-343555258.

**Comment by gnehapk** [comment]
@mcarrano As per @julienlim's [comment](https://github.com/Tendrl/ui/issues/663#issuecomment-342535734) only two columns need to be displayed for each event on event list page. Request you to please update the design and mention the possible objects by which event can be filtered w.r.t point **1** on https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738616.

**Comment by julienlim** [comment]
@mcarrano The API does not have all the data we'd like, and so I suggested sticking with the 2 columns for now as that's all we have to work with.  Specifically - here's what the Tendrl Notification API returns (and priority seems to say "notice" all the time):
  {
    "message_id": "b677b7e9-7e38-4da7-bc9e-cc171feeacc3",
    "timestamp": "2017-11-07T12:01:41.885310+00:00",
    "priority": "notice",
    "message": "Job timed out (job_id: c286caaf-e41e-4c01-a756-92fef6fd0314)"
  }

@gnehapk With regards to filter, the only ones that make sense to do seem to be the Date Picker and a Search (like we had in Alerts).

**Comment by julienlim** [comment]
@gnehapk @mcarrano 

Here's what Events should look like -- very similar to what we had in Alerts (< Tendrl 1.5.4 bugfix release).  Since we don't really have any severity levels other than "notice," let's leave off the severity level icon + severity level, along with the severity filters.  Note: The "Search" text should be Italicized (though it doesn't appear so in this mockup).

![cluster details-events 1](https://user-images.githubusercontent.com/5589919/32746552-0bed87c6-c884-11e7-8a76-da7994315430.png)

**Comment by julienlim** [comment]
In the Tendrl 1.5.4 bugfixes-2 release, the Events text is still truncated and needs to still word wrap.
![screen shot 2017-11-21 at 10 55 45 am](https://user-images.githubusercontent.com/5589919/33087014-624018c6-ceb7-11e7-9c23-730760c7a21b.png)

**Comment by a2batic** [comment]
@julienlim, It seems to be old build . Please try with tendrl-ui-1.5.4-20171121T111815.8f8f468.noarch.rpm and verify.

**Comment by julienlim** [comment]
@a2batic I just installed this yesterday with the 1.5.4 bugfixes-2.  I note that the Alerts drawer is wider and alert msg word wraps.  The previous build (1.5.4 bugfixes-1) didn't have these fixes.

This is not resolved yet.

**Comment by a2batic** [comment]
@julienlim, the event page according to the latest build (tendrl-ui-1.5.4-20171121T111815.8f8f468.noarch.rpm) looks like below for me:-

![screenshot from 2017-11-22 01-50-49](https://user-images.githubusercontent.com/12200504/33094912-ac88e04c-cef9-11e7-9880-53f695e91631.png)

**Comment by gnehapk** [comment]
Closing this issue, as its been opened for quite long time. Please feel free to reopen if the issue still persists.
