### ISSUE TITLE
Tendrl UI reporting brick is stopped when it's up and running

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#748]
Tendrl: Release 1.5.4 bugfixes
Scenario: I stopped one of the nodes which has a brick on it.  When node was brought back up, Tendrl is still reporting in the Tendrl UI and Grafana Bricks Dashboard that the brick is stopped.

Node 2 is up and running (after it had previously been stopped):
![screen shot 2017-11-13 at 9 56 59 am](https://user-images.githubusercontent.com/5589919/32732116-a163365a-c859-11e7-8b5a-e6376ed328eb.png)

In Volume Details, it says the brick on node2 is stopped:
![screen shot 2017-11-13 at 9 57 14 am](https://user-images.githubusercontent.com/5589919/32732139-b3e3dc26-c859-11e7-8ea8-8abfbc616291.png)

Grafana Bricks Dashboards says brick on node2 is stopped:
![screen shot 2017-11-13 at 10 01 11 am](https://user-images.githubusercontent.com/5589919/32732180-d0fdca2e-c859-11e7-8913-7f748fc108f8.png)

Output from gstatus, gluster volume info, and tendrl agents running on node2:
![screen shot 2017-11-13 at 10 03 29 am](https://user-images.githubusercontent.com/5589919/32732242-f3734386-c859-11e7-8595-98f4183595de.png)

**Comment by julienlim** [comment]
**API response for listing of bricks for vol1:

$ curl -XGET  -H "Authorization: Bearer 820edcc15c9936e25ada19453811c15bc9be7b5ccfbac6635f81250d946576db" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/clusters/ae9708ba-5c31-4bd9-b21e-b6240e010e52/volumes/ddcdba61-ad6b-4507-80f9-af3bc81a6e6b/bricks**

{
  "bricks": [
    {
      "filesystem_type": "",
      "hostname": "node1",
      "lv": "",
      "pv": [
        
      ],
      "sequence_number": "1",
      "size": "1072693248",
      "clientconnections": {
        "127.0.0.1:49149": {
          "brick_dir": "bricks_brick1",
          "bytesread": "1051184",
          "byteswrite": "911772",
          "fqdn": "node1",
          "hash": "e5851326d5199c4e1f72403a717fa623",
          "hostname": "127.0.0.1:49149",
          "updated_at": "2017-11-13 14:01:55.746716+00:00",
          "brick_name": "node1:_bricks_brick1",
          "opversion": "31200"
        },
        "172.28.128.6:49149": {
          "brick_dir": "bricks_brick1",
          "brick_name": "node1:_bricks_brick1",
          "hash": "e89f45c521716734e4f703b71bf664a4",
          "updated_at": "2017-11-13 13:34:37.593214+00:00",
          "bytesread": "1356",
          "byteswrite": "756",
          "fqdn": "node1",
          "hostname": "172.28.128.6:49149",
          "opversion": "31200"
        },
        "172.28.128.5:49147": {
          "hostname": "172.28.128.5:49147",
          "byteswrite": "716",
          "bytesread": "1288",
          "brick_name": "node1:_bricks_brick1",
          "hash": "0fc46fa5325fb2dcf3344a4bca0c2212",
          "updated_at": "2017-11-13 13:34:37.637247+00:00",
          "brick_dir": "bricks_brick1",
          "opversion": "31200",
          "fqdn": "node1"
        }
      },
      "client_count": "3",
      "disk_count": "",
      "mount_opts": "",
      "vol_id": "ddcdba61-ad6b-4507-80f9-af3bc81a6e6b",
      "devices": [
        "/dev/sdb"
      ],
      "name": "node1:_bricks_brick1",
      "updated_at": "2017-11-13 14:01:55.643165+00:00",
      "used": "True",
      "vg": "",
      "fqdn": "node1",
      "vol_name": "vol1",
      "brick_dir": "bricks_brick1",
      "brick_path": "node1:/bricks/brick1",
      "disk_type": "",
      "mount_path": "/bricks/brick1",
      "pool": "",
      "port": "49152",
      "hash": "0480b49f903d83aa35c5318a0fa1bbf4",
      "node_id": "8d0797fb-0eeb-473c-9496-2739067b5b90",
      "partitions": "[\"/dev/sdb1\"]",
      "status": "Started",
      "stripe_size": "",
      "utilization": {
        "metadata_used": null,
        "used_percent": 3.170480360720674,
        "thinpool_used_percent": null,
        "used": 33898496,
        "free_inode": 523754,
        "used_inode": 22,
        "used_percent_inode": 0.004200268817200481,
        "free": 1035292672,
        "total_inode": 523776,
        "mount_point": "/bricks/brick1",
        "metadata_used_percent": null,
        "metadata_free": null,
        "thinpool_used": null,
        "total": 1069191168,
        "thinpool_size": null,
        "thinpool_free": null,
        "metadata_size": null
      },
      "deleted": "False",
      "deleted_at": "",
      "is_arbiter": "",
      "subvolume": "subvolume0",
      "brick_id": "bricks_brick1"
    },
    {
      "brick_path": "node2:/bricks/brick1",
      "fqdn": "node2",
      "sequence_number": "2",
      "vol_id": "ddcdba61-ad6b-4507-80f9-af3bc81a6e6b",
      "hash": "84c5843799568e34abd5de47737a779e",
      "hostname": "node2",
      "lv": "",
      "utilization": {
        "metadata_used": null,
        "used_percent": 93.39700344400899,
        "thinpool_used_percent": null,
        "used": 998592512,
        "free_inode": 138120,
        "used_inode": 24,
        "metadata_size": null,
        "mount_point": "/bricks/brick1",
        "free": 70598656,
        "thinpool_free": null,
        "total_inode": 138144,
        "used_percent_inode": 0.017373175816544517,
        "metadata_used_percent": null,
        "metadata_free": null,
        "total": 1069191168,
        "thinpool_size": null,
        "thinpool_used": null
      },
      "deleted_at": "",
      "port": "49152",
      "status": "Stopped",
      "mount_opts": "",
      "node_id": "7431e7ec-9e93-4f79-8074-7d0cedf6e8ce",
      "pv": [
        
      ],
      "vol_name": "vol1",
      "brick_dir": "bricks_brick1",
      "deleted": "False",
      "disk_type": "",
      "is_arbiter": "",
      "filesystem_type": "",
      "size": "1072693248",
      "updated_at": "2017-11-10 17:04:37.430661+00:00",
      "used": "True",
      "vg": "",
      "client_count": "3",
      "devices": [
        "/dev/sdb"
      ],
      "mount_path": "/bricks/brick1",
      "pool": "",
      "stripe_size": "",
      "disk_count": "",
      "name": "node2:_bricks_brick1",
      "partitions": "[\"/dev/sdb1\"]",
      "subvolume": "subvolume0",
      "brick_id": "bricks_brick1"
    },
    {
      "brick_path": "node3:/bricks/brick1",
      "deleted": "False",
      "filesystem_type": "",
      "fqdn": "node3",
      "sequence_number": "3",
      "status": "Started",
      "client_count": "3",
      "disk_count": "",
      "used": "True",
      "vol_id": "ddcdba61-ad6b-4507-80f9-af3bc81a6e6b",
      "mount_path": "/bricks/brick1",
      "clientconnections": {
        "127.0.0.1:49150": {
          "fqdn": "node3",
          "hostname": "127.0.0.1:49150",
          "updated_at": "2017-11-13 13:53:47.423881+00:00",
          "brick_dir": "bricks_brick1",
          "brick_name": "node3:_bricks_brick1",
          "bytesread": "1046412",
          "byteswrite": "907612",
          "hash": "b6f8eab2d24ed145dc6973be645bea57",
          "opversion": "31200"
        },
        "172.28.128.4:49150": {
          "opversion": "31200",
          "brick_dir": "bricks_brick1",
          "brick_name": "node3:_bricks_brick1",
          "bytesread": "1480",
          "byteswrite": "888",
          "fqdn": "node3",
          "hash": "de8a42e84b63aecd43c4a37a07766b73",
          "hostname": "172.28.128.4:49150",
          "updated_at": "2017-11-13 13:31:52.012417+00:00"
        },
        "172.28.128.5:49146": {
          "hash": "1a0506bfde5d054c97af46e5f7f67fd4",
          "hostname": "172.28.128.5:49146",
          "updated_at": "2017-11-13 13:35:00.078709+00:00",
          "byteswrite": "584",
          "brick_dir": "bricks_brick1",
          "bytesread": "1164",
          "fqdn": "node3",
          "opversion": "31200",
          "brick_name": "node3:_bricks_brick1"
        }
      },
      "disk_type": "",
      "size": "1072693248",
      "utilization": {
        "metadata_used": null,
        "used_percent": 3.170480360720674,
        "thinpool_used_percent": null,
        "used": 33898496,
        "free_inode": 523754,
        "used_inode": 22,
        "used_percent_inode": 0.004200268817200481,
        "free": 1035292672,
        "total_inode": 523776,
        "mount_point": "/bricks/brick1",
        "metadata_used_percent": null,
        "metadata_free": null,
        "thinpool_used": null,
        "total": 1069191168,
        "thinpool_size": null,
        "thinpool_free": null,
        "metadata_size": null
      },
      "brick_dir": "bricks_brick1",
      "devices": [
        "/dev/sdb"
      ],
      "partitions": "[\"/dev/sdb1\"]",
      "pool": "",
      "deleted_at": "",
      "hash": "0b1b75d92612e88bbec48e11e122c03a",
      "node_id": "19f53da4-c2f2-469a-8bef-53bbe8d1bf2b",
      "vol_name": "vol1",
      "lv": "",
      "mount_opts": "",
      "name": "node3:_bricks_brick1",
      "port": "49152",
      "pv": [
        
      ],
      "vg": "",
      "hostname": "node3",
      "is_arbiter": "",
      "stripe_size": "",
      "updated_at": "2017-11-13 14:00:02.863705+00:00",
      "subvolume": "subvolume0",
      "brick_id": "bricks_brick1"
    }
  ]
}

**Comment by julienlim** [comment]
@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim The page you are referring here is "Host Details" page. Can you please share the API response received for "/clusters/:clusterId/node/:nodeId/bricks".

**Comment by julienlim** [comment]
@gnehapk For host details, it also shows the brick is stopped:

![screen shot 2017-11-13 at 11 39 56 am](https://user-images.githubusercontent.com/5589919/32737214-719f64da-c867-11e7-976c-e4964e73d46a.png)

Here's the volume details where it also shows that the brick has stopped:
![screen shot 2017-11-13 at 2 18 24 pm](https://user-images.githubusercontent.com/5589919/32744478-96eb67aa-c87d-11e7-8fd6-c41800c45cd7.png)

**Comment by julienlim** [comment]
@gnehapk 
Here's the response for "/clusters/:clusterId/node/:nodeId/bricks:"

{
  "bricks": [
    {
      "disk_count": "",
      "name": "node2:_bricks_brick1",
      "partitions": "[\"/dev/sdb1\"]",
      "stripe_size": "",
      "brick_path": "node2:/bricks/brick1",
      "fqdn": "node2",
      "sequence_number": "2",
      "vol_id": "ddcdba61-ad6b-4507-80f9-af3bc81a6e6b",
      "hash": "84c5843799568e34abd5de47737a779e",
      "hostname": "node2",
      "lv": "",
      "utilization": {
        "metadata_used": null,
        "used_percent": 93.39700344400899,
        "thinpool_used_percent": null,
        "used": 998592512,
        "free_inode": 138120,
        "used_inode": 24,
        "metadata_size": null,
        "mount_point": "/bricks/brick1",
        "free": 70598656,
        "thinpool_free": null,
        "total_inode": 138144,
        "used_percent_inode": 0.017373175816544517,
        "metadata_used_percent": null,
        "metadata_free": null,
        "total": 1069191168,
        "thinpool_size": null,
        "thinpool_used": null
      },
      "deleted_at": "",
      "port": "49152",
      "status": "Stopped",
      "vol_name": "vol1",
      "brick_dir": "bricks_brick1",
      "deleted": "False",
      "disk_type": "",
      "is_arbiter": "",
      "mount_opts": "",
      "node_id": "7431e7ec-9e93-4f79-8074-7d0cedf6e8ce",
      "pv": [
        
      ],
      "filesystem_type": "",
      "size": "1072693248",
      "client_count": "3",
      "devices": [
        "/dev/sdb"
      ],
      "mount_path": "/bricks/brick1",
      "pool": "",
      "updated_at": "2017-11-10 17:04:37.430661+00:00",
      "used": "True",
      "vg": "",
      "brick_id": "bricks_brick1"
    }
  ]
}

**Comment by gnehapk** [comment]
@nthomas-redhat @r0h4n @shtripat @anivargi API has returned `"status":"Stopped"` for the brick `"name":"node2:_bricks_brick1"`. Hence the UI is displaying "Stopped" icon for it. Please check.

**Comment by gnehapk** [comment]
@nthomas-redhat @shtripat @r0h4n @GowthamShanmugam Please close this issue it it is fixed.

**Comment by GowthamShanmugam** [comment]
I need to verify this once
