### ISSUE TITLE
Grafana Dashboard: Tooltip icons (providing description) for the Dashboard tab labels are distantly/unevenly placed. 

### ISSUE THREAD

**Issue by rghatvis** [Tendrl/ui#749]
The tooltip icons or dialogue box icons are not placed above the tab labels. For example, for the Hosts label, the tooltip appears to be placed between the airspace of the Overview tab and the Hosts tab. The user can't clearly make out which tooltip icon belongs to which label by a glance. Can we make the icons perpendicular to the labels or place above it or in proximity to the labels? 
![uneven-tooltip-icons](https://user-images.githubusercontent.com/16681357/32770445-bb0a4d4a-c945-11e7-8ff5-4ba0b528229d.png)

**Comment by gnehapk** [comment]
@rghatvis Since this issue belongs to [monitoring-integration](https://github.com/Tendrl/monitoring-integration), request you to move this issue to monitoring-integration component.

**Comment by julienlim** [comment]
@cloudbehl

**Comment by cloudbehl** [comment]
The is a Monitoring Integration issue, so I am moving this issue to the MI repo.
https://github.com/Tendrl/monitoring-integration/issues/386.
