### ISSUE TITLE
Import Cluster tooltip typo "...performance thing."

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#755]
See ending of the tooltip, it should be either "... performance optimization" or "... performance tuning" (the original suggestion) but not "... performance thing."

<img width="1185" alt="screen shot 2017-11-16 at 12 08 25 pm" src="https://user-images.githubusercontent.com/5589919/32905224-55811354-cac7-11e7-93a8-8d922af8e2b0.png">

@gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by a2batic** [comment]
@julienlim, this issue has been fixed with tendrl-ui-1.5.4-20171121T111815.8f8f468.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
Closing this issue, as its been opened for quite long time. Please feel free to reopen if the issue still persists.
