### ISSUE TITLE
UI is showing volume detail even after deletion of volume

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/ui#759]
UI should not show deleted volumes details

**Comment by GowthamShanmugam** [comment]
@cloudbehl @gnehapk please check this issue

**Comment by a2batic** [comment]
@GowthamShanmugam, fixed with tendrl-ui-1.5.4-20171121T111815.8f8f468.noarch.rpm. Please verify.

**Comment by gnehapk** [comment]
Closing this issue, as its been opened for quite long time. Please feel free to reopen if the issue still persists.
