### ISSUE TITLE
tendrl specific names should be taken from configurations

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ui#764]
tendrl speicifc names like node role `Tendrl server`, the dashboard names in grafana dashboards (e.g. Tendrl - Dashboard at a glance) etc should be taken from a configuration file and should not be hard-coded within tendrl codebase. This would make it easy for re-branding tendrl for downstream with different names.

We need to identify all such hardcoded names in tendrl and make them configurable.

**Comment by gnehapk** [comment]
@shtripat I feel this issue is related to monitoring-integration component. Please move it the corresponding repo.

**Comment by shtripat** [comment]
This is no more valid issue. Closing now.
