### ISSUE TITLE
 Tasks filter not showing tasks correctly based on date

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ui#768]
Filed by @fbalak 

Description of problem:
I have one task ImportCluster from `20 Nov 2017 13:25:27`. When I select `From: 20 Nov 2017` and `To: 21 Nov 2017` or later it shows correctly the task but when I select date `20 Nov 2017` (the same date that the task was created) in `To:` field the task disappears.

**Comment by a2batic** [comment]
Currently, the datepicker from A date to B date includes all task on and from A and before B, also, if A and B dates are same, it will list all the task on that particular date. 

Should the range ( A to B ) include the task on B date as well, when dates are different or the current behavior in fine ?
@julienlim @mcarrano, what do you suggest ?

**Comment by mcarrano** [comment]
I would expect the search results to include tasks on the "B" date as well as before. @julienlim do you agree?

**Comment by julienlim** [comment]
@a2batic @gnehapk @fbalak @mcarrano 

Yes, I expect the search results to include tasks including the B date, i.e.
Date Range (A to B) == (Dates >= A) AND (Dates <= B)
