### ISSUE TITLE
 Alerts icon (bell icon) on Web Admin home page needs to show/indicate if there are unread events/alerts

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ui#769]
Description of problem:

The bell icon on the top right corner of Web Admin home page, which signifies alerts, when clicked displays all alerts. IF there are any new alerts generated, then it should signify with a number (inside a red circle, say) - stating loud and clear that there are x number of unread messages/alerts.

Displaying nothing around the bell does not get the attention of admin.

**Comment by julienlim** [comment]
@gnehapk @nthomas-redhat @r0h4n @mbukatov @Tendrl/tendrl-qe @mcarrano 

The bell icon should indicate if there are alerts or not.  Ideally it should signify the number of unread and uncleared alerts requiring attention.

If we're not able to compute the number of unread and uncleared alerts, we should provide some visual treatment on the bell to indicate if there is an alert vs. not, so the Admin knows that there is something requiring his/her attention.

**Comment by mcarrano** [comment]
@gnehapk @julienlim The appearance/behavior of the bell icon in the masthead is specified in PatternFly here: http://www.patternfly.org/pattern-library/application-framework/masthead/. When there are new or unread alerts present,  a blue badge should be added to the upper right corner of the icon. We did not include a count value because it will not scale well from a readability standpoint. Let me know if you have questions.

**Comment by julienlim** [comment]
Related Bugzilla Tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1517246

**Comment by a2batic** [comment]
@nthomas-redhat @r0h4n @shtripat @GowthamShanmugam @gnehapk 
Patternfly seems to use a flag to check for read/unread alert [1]. They have used an attribute `unread: true/false` for this purpose. 

As per the current response from global alert API `/alerts `, we are not receiving any such flag. So, a flag will be required for this purpose.

[1] https://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer

**Comment by ltrilety** [comment]
I agree with @julienlim we need some indication that there are some active not cleared alerts. Ideally only those not acked/read. But for upcoming release just showing those active ones will be enough.

**Comment by gnehapk** [comment]
@nthomas-redhat @shtripat Even for indication of the new alerts, UI need a reference value to compare with. Once user logged in to tendrl, there should be some property in the `/alerts` API response so that the UI know that user has new alerts to read.

**Comment by shtripat** [comment]
@GowthamShanmugam ^^^ thoughts?

**Comment by GowthamShanmugam** [comment]
@shtripat when warning alert is replaced by clearing alert I am marking acked value in alert object as True https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/alert/__init__.py#L47

Using this flag they can easily identify the number of uncleared alerts.

my doubt is why we need an unread alert count here, is that uncleared alert count of unread alert count?

**Comment by a2batic** [comment]
@GowthamShanmugam, Ui needs a flag which says, following, for example:-
The flag can be a Boolean with is true when ` alerts received > alerts received in last polling `. We don't require alert count/number. We just need to tell user that there are more alerts.

**Comment by cybernth** [comment]
@GowthamShanmugam , @a2batic, I don't think whatever mechanisms discussed here are reliable enough to give consistent results. If you want to have this implemented properly, we need to catogorize alerts based on the read/unread( Using the ack fetaure) in backend which can't be done with in the time frame we are looking for.
What we can do right now is to show an indication if there is any un-cleared alerts(alerts with severity > info) present in the drawer. For this there is no backend changes required as the UI itself can figure this out based on the results of the API call.
Make sense? @julienlim @r0h4n @shtripat @ltrilety

**Comment by julienlim** [comment]
+1 @nthomas-redhat, i.e. showing indicator for uncleared alerts.  We don't need a count.  As we have no ability to ack/unack an alert, this seems to be the only option.
