### ISSUE TITLE
Improvements/Enhancements  for concept-b implementation

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ui#780]
- No expanded view for hosts on cluster list.
- Modal for showing import task errors.
- Add a link to the 'All Clusters' view to open the import task details in a new page (at this point the left navigation will be hidden). Once a cluster is successfully imported, a link will be provided to direct the user to 'Cluster detail' views for the newly imported cluster.
- In all list views, we will be using buttons to show primary actions and kebab menu to show secondary actions.
- Add 'Volumes count' and 'Alerts count' on cluster list view.
- Add 'Bricks count' on host list view.

**Comment by gnehapk** [comment]
@r0h4n @shtripat @nthomas-redhat There is requirement from UX that we should add `volumes` and `alerts` count on cluster list page and `bricks` count on host list view which are currently not present in the API response.  Please inform once these counts are available in the API/backend.

**Comment by julienlim** [comment]
@gnehapk @a2batic @cloudbehl @mcarrano 

I took some AI's when we last spoke related to the Concept B implementation.

(1)  check on the status for context selector with the Patternfly team.
* Current PF design: http://www.patternfly.org/pattern-library/navigation/context-selector/
* Current status: No one on PF team is working on code for the design yet, but seeing if we can get this into the backlog
* Another project has the Context Selector code in JQuery, but nothing in Angular as of yet.  Is this something you might be interested in?
* In the meantime, PF team is seeing if we can provide an HTML/CSS implementation (styling)

(2)  help in figuring out a one click step to go back to 'All clusters' view from the user’s view.
* Current status: In progress -- current thinking is to leverage breadcrumbs.  We have to update the mockups to show this.  Pending updates by @mcarrano.

**Comment by mcarrano** [comment]
@gnehapk @julienlim I've added a breadcrumb to the top of the Users page to give the user one-click access to return to the All Clusters view. You can find that here: https://redhat.invisionapp.com/share/8QCOEVEY9#/244738633_Users  Note that this breadcrumb is also added to other admin views (although I understand they have not yet been implemented).

The user should also be able to navigate back to All Clusters or to any other cluster from this view using the context selector menu. Note that All Clusters should always be the first item in that menu so it's easy to access.

Let me know if you have questions.

**Comment by julienlim** [comment]
Thanks @mcarrano.

To summarize, for the "one click step to go to `All Clusters`," the Admin pages were updated to include breadcrumbs to get to All Clusters more easily.

From a given cluster, you still need to go to the Context Switcher to get to ‘All Clusters’ -- Rationale is that while it would be nice to have a "home" like button to see all clusters (portfolio on a bunch of accounts if you'd like to think of that analogy), the user is only looking at All Clusters when he/she wants to Import Cluster or Unmanage Cluster -- both operations are not frequent uses.  When there are enough users saying there's a need to go to All Clusters often, then we'll revisit it.

@gnehapk @a2batic @cloudbehl @mcarrano @Tendrl/tendrl-core @Tendrl/tendrl-qe

**Comment by gnehapk** [comment]
@julienlim JQuey implementation of the context selector might be useful for us. Please provide the link where we can see the implementation.
@mcarrano @julienlim Thanks for providing the design for one click step to go back to 'All clusters' view from the user’s view. Will start the implementation.

**Comment by Rohoover** [comment]
@julienlim 
Here is the link to Foreman's work with the vertical navigation which I believe includes the context switcher:

https://github.com/theforeman/foreman/pull/4794#issuecomment-325651601

**Comment by julienlim** [comment]
Thanks @Rohoover!

@gnehapk @a2batic @cloudbehl @mcarrano See link @Rohoover provided for the JQuery implementation of the context selector in the Foreman project.  Hope it is helpful.

**Comment by gnehapk** [comment]
@julienlim @mcarrano With the new changes introduce for concept b, some of the UX designs are not in sync, which can create confusion to QE guys while testing. 

Following are the new changes which needs to be reflected in UXD (UI implementation for all the changes are done.):
-   Volume and Alert count on cluster list page 
   Attaching screenshot for the current implementation 
![screenshot from 2018-02-01 17-58-02](https://user-images.githubusercontent.com/5517376/35679138-01295bc6-077c-11e8-9992-a3fbb31750db.png)

-   Brick count on host list page
   Attaching screenshot for the current implementation 
![brick-count](https://user-images.githubusercontent.com/5517376/35735399-a34babd8-084a-11e8-9ea5-416135e4baf5.png)

-   Remove donut and other charts from the list views if it is no longer required
-   Task detail UXD for import task.  We have added "All Clusters" in the breadcrumb similar to user list view to take the user to All Clusters page in case of import cluster task fails.
    Attaching screenshot for the current implementation 
    
![import-task-progress](https://user-images.githubusercontent.com/5517376/35735388-935d2ea4-084a-11e8-9064-c9a057cc952a.png)

-   Add "Track Progress" link to all the clusters whose import flow is in progress on cluster list view which will redirect the user to import task detail view.
   Attaching screenshot for the current implementation 
  
 
![task-progress-link](https://user-images.githubusercontent.com/5517376/35684954-62dccbde-078e-11e8-8aa2-1ad786834808.png)

Please update the UX designs( i.e. the invisions)

@a2batic @cloudbehl @julienlim @mcarrano Please feel free to add/suggest if I missed anything.

**Comment by mcarrano** [comment]
@gnehapk I have updated the screens that you requested in the InVision deck here: https://redhat.invisionapp.com/share/8QCOEVEY9

Just a couple of things to note:

* We adjusted the alignment a bit of items in the list view on the Clusters view. The message string (i.e. import status, etc) is now aligned with the 'View details' link to the right of the row before the Import button. We also feel that the Volume Profiling, Volumes, and Alerts fields should be hidden for any cluster that is not currently managed.

* On the Hosts list, Gluster Version should be added as the first item for each host.

* Alerts should always be the last field in all lists so I have updated the mockups accordingly.

Let @julienlim or I know if you have any questions.

**Comment by gnehapk** [comment]
@mcarrano  I think you forget to remove "Details" button from [cluster list ](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738628) view.  

Also on [volume list](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738623) view, the dashboard action should be a button similar to other views.

**Comment by mcarrano** [comment]
@gnehapk @julienlim I have updated these wireframes and uploaded changes here: https://redhat.invisionapp.com/share/8QCOEVEY9

**Comment by julienlim** [comment]
Noting that the related spec is [Tendrl UI Concept B Changes](https://github.com/Tendrl/specifications/pull/256/files#diff-e0b34a23c645111a673d7bfbb541c7fc).
