### ISSUE TITLE
Tasks - inconsistent labeling for completed tasks

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#800]
We are showing different labels currently in the Tendrl UI for tasks that have been completed.

Task Details - we show "Finished"
<img width="559" alt="screen shot 2018-02-02 at 11 33 58 am" src="https://user-images.githubusercontent.com/5589919/35744049-4d032a18-080d-11e8-841e-68f127b6e3ad.png">

Task List - we show "Completed"
<img width="1253" alt="screen shot 2018-02-02 at 11 34 44 am" src="https://user-images.githubusercontent.com/5589919/35744072-60392768-080d-11e8-8e1f-b18cb51824d3.png">

Can we change the one in "Task Details" from "Finished" to "Completed" and make them consistent?

@gnehapk @a2batic @mcarrano @Tendrl/tendrl-qe

**Comment by gnehapk** [comment]
@julienlim Please verify this issue.

**Comment by julienlim** [comment]
@gnehapk Verified that Tasks Details now shows "Completed"
