### ISSUE TITLE
No brick detected or shown

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#803]
@gnehapk @a2batic @cloudbehl  @nthomas-redhat @Tendrl/tendrl-qe 

I just installed the latest [Tendrl 1.5.5](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.5-(install-guide)), and the Tendrl UI does not seem to be displaying any brick information though I can clearly see brick information from the CLI.

**CLI snippet:**

```
[root@node1 ~]# gluster volume status

Status of volume: vol1
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick node1:/bricks/brick1                  49152     0          Y       1293 
Brick node2:/bricks/brick1                  49152     0          Y       1122 
Brick node3:/bricks/brick1                  49152     0          Y       1128 
Self-heal Daemon on localhost               N/A       N/A        Y       4282 
Self-heal Daemon on node3                   N/A       N/A        Y       3884 
Self-heal Daemon on node2                   N/A       N/A        Y       3930 
 
Task Status of Volume vol1
------------------------------------------------------------------------------
There are no active volume tasks
```

**UI screenshots:**
![screen shot 2018-02-05 at 3 40 27 pm](https://user-images.githubusercontent.com/5589919/35827659-e5ffb824-0a8a-11e8-8086-90ae9f7ec9f3.png)

![screen shot 2018-02-05 at 3 40 36 pm](https://user-images.githubusercontent.com/5589919/35827667-eb1a1f16-0a8a-11e8-90b9-66597d747a7e.png)

![screen shot 2018-02-05 at 3 40 47 pm](https://user-images.githubusercontent.com/5589919/35827678-f05660ac-0a8a-11e8-9005-d9f5c0cda39d.png)

![screen shot 2018-02-05 at 3 40 56 pm](https://user-images.githubusercontent.com/5589919/35827683-f36cd3a2-0a8a-11e8-8d43-962144338f09.png)

**Comment by gnehapk** [comment]
@julienlim Please share the API response for `clusters/{clusterId }/volumes/{volId}/bricks` and `clusters/{clusterId }/nodes/{fqdn}/bricks` .

**Comment by julienlim** [comment]
API response for clusters/{clusterId }/volumes/{volId}/bricks

```
curl -XGET  -H "Authorization: Bearer 7eaf382c5aedccc2f64ba884a13ba0c2c14e8a1b8f2fe933f49d752d3e690d03" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/clusters/5dbc159e-e4f9-442c-8de7-2ef74354094c/volumes/ccc0500e-6365-4ac1-9149-d32e87444f80/bricks

{"bricks":[]}
```

**Comment by julienlim** [comment]
API response for clusters/{clusterId }/nodes/{fqdn}/bricks

```
curl -XGET  -H "Authorization: Bearer 7eaf382c5aedccc2f64ba884a13ba0c2c14e8a1b8f2fe933f49d752d3e690d03" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/clusters/5dbc159e-e4f9-442c-8de7-2ef74354094c/nodes/node1.localdomain/bricks

{"bricks":[]}
```

@gnehapk

**Comment by gnehapk** [comment]
@r0h4n @nthomas-redhat @shtripat Since the API returns empty array, UI is not displaying any bricks for it. Please check.

**Comment by gnehapk** [comment]
@r0h4n @shtripat @nthomas-redhat Please close the issue, if its fixed.

**Comment by r0h4n** [comment]
This is not seen in Milestone 3, please verify again

**Comment by stephenrjones** [comment]
Hello,

After doing an install of Tendrl 1.6.3 using Ansible and pointing to an operational GlusterFS system, I'm seeing this exact issue ({"bricks":[]}). The import function brought in the nodes and volume information, however I'm getting 'No Bricks Detected' for all 3 of the nodes in the cluster. Any recommendations to resolve this issue?
