### ISSUE TITLE
"Incorrect" Cluster ID shown

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#804]
Problem:
The cluster ID being shown in the Events is not the canonical reference shown to the user, which may lead to user confusion as to what cluster is being referred to (even though we're looking at the given cluster is question).

```
Cluster ID (in breadcrumb) is 5dbc159e-e4f9-442c-8de7-2ef74354094c

Note: Cluster ID shown in the Events message:
Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from unhealthy to healthy
```

Tendrl release: latest [Tendrl 1.5.5](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.5-(install-guide))

Screenshot:
![screen shot 2018-02-05 at 3 54 06 pm](https://user-images.githubusercontent.com/5589919/35828346-1e558e2c-0a8d-11e8-9cc6-a3a5b6a17c19.png)

@gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim Please share the API response for `/clusters/{cluster_id}/notifications`.

@r0h4n @shtripat @GowthamShanmugam @nthomas-redhat It seems that API/backend is giving different cluster Id in events message. Please look into it.

**Comment by GowthamShanmugam** [comment]
@gnehapk i will check this

**Comment by julienlim** [comment]
@gnehapk @GowthamShanmugam 

```
root# curl -XGET -H "Authorization: Bearer 7eaf382c5aedccc2f64ba884a13ba0c2c14e8a1b8f2fe933f49d752d3e690d03" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/notifications

[{"message_id":"4ba33f07-81e0-4969-a476-5162096aa1e7","timestamp":"2018-02-06T16:57:12.721829+00:00","priority":"notice","message":"Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from unhealthy to healthy"},{"message_id":"cd92bb8e-4658-44e2-b0fe-4e92ffe5fcc1","timestamp":"2018-02-06T16:56:59.735553+00:00","priority":"notice","message":"Node node1.localdomain is UP"},
{"message_id":"dacd9eaa-f854-413a-a198-9ca43a3770c3","timestamp":"2018-02-06T16:56:57.180301+00:00","priority":"notice","message":"Status of peer: node1 in cluster 5dbc159e-e4f9-442c-8de7-2ef74354094c changed from Disconnected to Connected"},
{"message_id":"9820ad78-d8c7-456a-8247-aba5cd4db680","timestamp":"2018-02-06T16:55:01.568859+00:00","priority":"notice","message":"Node node3.localdomain is UP"},
{"message_id":"ad93b565-99a9-4cce-a112-e2247b347f08","timestamp":"2018-02-06T16:55:01.362865+00:00","priority":"notice","message":"Node node2.localdomain is UP"},
{"message_id":"9017232e-043b-4ebc-aa28-c664b5c5bba0","timestamp":"2018-02-06T16:54:59.747687+00:00","priority":"notice","message":"Node node0.localdomain is UP"},
{"message_id":"a2cb5fd4-8687-4a41-ba68-e2f4b55de96a","timestamp":"2018-02-05T20:25:16.372218+00:00","priority":"notice","message":"Job finished successfully (job_id: 14e7207a-02d4-4e97-a0c7-214bf71a91e8)"},
{"message_id":"90a5945d-071a-4abe-a559-35ad3ccda01d","timestamp":"2018-02-05T20:24:38.577316+00:00","priority":"notice","message":"Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from unhealthy to healthy"},
{"message_id":"de5f080a-956c-4d40-a487-ba9aedb449fe","timestamp":"2018-02-05T20:18:51.285841+00:00","priority":"notice","message":"Node node3.localdomain is UP"},
{"message_id":"dbd51668-d16b-4cb2-9c26-f488111e76a1","timestamp":"2018-02-05T20:18:51.182729+00:00","priority":"notice","message":"Node node2.localdomain is UP"},
{"message_id":"03ead5e2-f5c5-4016-8405-173eca0a8d43","timestamp":"2018-02-05T20:18:51.179940+00:00","priority":"notice","message":"Node node1.localdomain is UP"},
{"message_id":"a876e0bb-4b28-4e22-975d-4479a6a2d17a","timestamp":"2018-02-05T20:14:53.547585+00:00","priority":"notice","message":"Node node0.localdomain is UP"},
{"message_id":"fe095c65-2405-4d09-a1b3-9fb07281b4ce","timestamp":"2018-02-05T20:11:29.588803+00:00","priority":"notice","message":"Node node0.localdomain is UP"}]
```

**Comment by gnehapk** [comment]
@julienlim The response you have shared is for global events. Please share the API response for /clusters/5dbc159e-e4f9-442c-8de7-2ef7435409/notifications where `5dbc159e-e4f9-442c-8de7-2ef7435409` is cluster id.

**Comment by julienlim** [comment]
@gnehapk @GowthamShanmugam 

$ curl -XGET -H "Authorization: Bearer 2c5e787459ffb60628be753e18d1ddd6cd265c91351cf22cc3d4c7b99cb8fa8c" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/clusters/5dbc159e-e4f9-442c-8de7-2ef74354094c/notifications


[{"message_id":"128d21ee-7e00-4747-aacf-6300d5625109","timestamp":"2018-02-12T14:45:57.404110+00:00","priority":"notice","message":"Node node3.localdomain is UP"},{"message_id":"83d487df-b907-4830-9ef4-fabb4cc7c299","timestamp":"2018-02-06T21:45:50.451435+00:00","priority":"notice","message":"Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from unhealthy to healthy"},{"message_id":"b8a5bca0-4387-4c6a-8fbd-d9c91ac70399","timestamp":"2018-02-06T21:45:37.720162+00:00","priority":"notice","message":"Status of peer: node3 in cluster 5dbc159e-e4f9-442c-8de7-2ef74354094c changed from Disconnected to Connected"},{"message_id":"816d324a-988a-47e6-9ffc-941da1d344f9","timestamp":"2018-02-06T21:39:38.216429+00:00","priority":"notice","message":"Status of peer: node3 in cluster 5dbc159e-e4f9-442c-8de7-2ef74354094c changed from Connected to Disconnected"},{"message_id":"a5560fd1-c04d-4281-8a32-cf951d97c5a8","timestamp":"2018-02-06T21:39:12.521350+00:00","priority":"notice","message":"Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from healthy to unhealthy"},{"message_id":"4ba33f07-81e0-4969-a476-5162096aa1e7","timestamp":"2018-02-06T16:57:12.721829+00:00","priority":"notice","message":"Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from unhealthy to healthy"},{"message_id":"cd92bb8e-4658-44e2-b0fe-4e92ffe5fcc1","timestamp":"2018-02-06T16:56:59.735553+00:00","priority":"notice","message":"Node node1.localdomain is UP"},{"message_id":"dacd9eaa-f854-413a-a198-9ca43a3770c3","timestamp":"2018-02-06T16:56:57.180301+00:00","priority":"notice","message":"Status of peer: node1 in cluster 5dbc159e-e4f9-442c-8de7-2ef74354094c changed from Disconnected to Connected"},{"message_id":"9820ad78-d8c7-456a-8247-aba5cd4db680","timestamp":"2018-02-06T16:55:01.568859+00:00","priority":"notice","message":"Node node3.localdomain is UP"},{"message_id":"ad93b565-99a9-4cce-a112-e2247b347f08","timestamp":"2018-02-06T16:55:01.362865+00:00","priority":"notice","message":"Node node2.localdomain is UP"},{"message_id":"a2cb5fd4-8687-4a41-ba68-e2f4b55de96a","timestamp":"2018-02-05T20:25:16.372218+00:00","priority":"notice","message":"Job finished successfully (job_id: 14e7207a-02d4-4e97-a0c7-214bf71a91e8)"},{"message_id":"90a5945d-071a-4abe-a559-35ad3ccda01d","timestamp":"2018-02-05T20:24:38.577316+00:00","priority":"notice","message":"Health status of cluster: gluster-195d43d86fd38ba5929e44529d1fa0b985f42f03946e0bb5ada6999805556674 changed from unhealthy to healthy"},{"message_id":"de5f080a-956c-4d40-a487-ba9aedb449fe","timestamp":"2018-02-05T20:18:51.285841+00:00","priority":"notice","message":"Node node3.localdomain is UP"},{"message_id":"dbd51668-d16b-4cb2-9c26-f488111e76a1","timestamp":"2018-02-05T20:18:51.182729+00:00","priority":"notice","message":"Node node2.localdomain is UP"},{"message_id":"03ead5e2-f5c5-4016-8405-173eca0a8d43","timestamp":"2018-02-05T20:18:51.179940+00:00","priority":"notice","message":"Node node1.localdomain is UP"}]

**Comment by GowthamShanmugam** [comment]
This issue is fixed

**Comment by gnehapk** [comment]
@julienlim Please verify this issue and close it, if its working fine.

**Comment by gnehapk** [comment]
@julienlim I am closing this issue. Please open it if you see this issue again.
