### ISSUE TITLE
Actions related to Profiling not shown in Events

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#807]
When I Enable/Disable Profiling for cluster on `Clusters` UI page then there is no message about this on Events page for the cluster.
![0207](https://user-images.githubusercontent.com/22369801/35917042-e8942df8-0c0c-11e8-9340-8df9168ab969.png)

Tested with:
```
tendrl-grafana-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-node-agent-1.5.5-20180202T165439.9e57adf.noarch
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-grafana-plugins-1.5.5-20180202T171247.8435143.noarch
tendrl-monitoring-integration-1.5.5-20180202T171247.8435143.noarch
tendrl-notifier-1.5.5-20180202T172143.34fc113.noarch
tendrl-api-httpd-1.5.5-20180202T172550.51b6c71.noarch
tendrl-commons-1.5.5-20180202T165022.2295e4e.noarch
tendrl-api-1.5.5-20180202T172550.51b6c71.noarch
tendrl-ui-1.5.5-20180206T071442.da9a942.noarch
```

CC: @julienlim

**Comment by shtripat** [comment]
Based on latest changes in get-state output in gluster, when there is a change in volume profiling info, an event can be generated from tendrl side. I will take this up.

**Comment by gnehapk** [comment]
@r0h4n @shtripat @nthomas-redhat Please close the issue, if its fixed.

**Comment by r0h4n** [comment]
@shtripat  any update on this?

**Comment by shtripat** [comment]
@r0h4n now we have actions available at volume level to set/unset profiling. Also while sync when there is change found it raises events for the same.

**Comment by shtripat** [comment]
This could be closed

**Comment by fbalak** [comment]
@shtripat I will close it but I would like to wait for https://github.com/Tendrl/gluster-integration/issues/579 to be resolved. Now I am able to show only message `Value of volume profiling for volume: volume_beta_arbiter_2_plus_1x2 of cluster 6925ae1b-afdc-4bc3-97f0-90acf941fa1f`.

**Comment by gnehapk** [comment]
@fbalak Since https://github.com/Tendrl/gluster-integration/issues/579 has been closed, can you please verify and close this issue.
