### ISSUE TITLE
list of host should be displayed for failed import cluster 

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ui#808]
UXD - https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738627

**Comment by a2batic** [comment]
@gnehapk @nthomas-redhat, according to design, host list should contain hostname and host IP address, but we are not receiving host ip address from any of the API

**Comment by r0h4n** [comment]
Tendrl requires fqdn for all nodes , why is the host ip required here? Also, what happens when there's multiple IP for a host?

@julienlim

**Comment by julienlim** [comment]
@gnehapk @r0h4n @a2batic 

Ack Tendrl requires FQDN.  Host IP is more for troubleshooting as the dialog is supposed to help with troubleshooting.

Host IP doesn't need to show every IP address to the host, all it needs to show the IP address for the FQDN (e.g. like what you would get via nslookup).

**Comment by julienlim** [comment]
Related to https://github.com/Tendrl/specifications/pull/256#issuecomment-364402195.

@mcarrano

**Comment by gnehapk** [comment]
@mcarrano @julienlim To maintain the consistency, I would like to suggest to display the [host list](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/278907431) in the similar design as we have displayed the other list views. Currently the [host list view](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/278907431) design is different from other [list views](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738628). What are your thoughts?

**Comment by julienlim** [comment]
@gnehapk @mcarrano 

The same thought had occurred to us; however, if we did display it in a similar fashion, users would ask why don't they have the same detailed information (when the only thing we have is hostname/FQDN, IP address, and perhaps Gluster version at this point which if we do have available we should show).  Hence, why we decided not to.
