### ISSUE TITLE
import task fail not clear error message

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#813]
From the error message provided using `View Details` link on `All Clusters` page it doesn't have to be clear what happened.
E.g. I changed baseurl to not existing one in tendrl repository file on `ltrilety-usm2-gl6` machine, so the import had to fail. However the message present in the modal is

`Atom Execution failed. Error: Error executing atom: tendrl.objects.Cluster.atoms.ImportCluster on flow: Import existing Gluster Cluster`.

That's because the import didn't end exactly when the issue was hit. There were several other actions finished after that.

View Details modal window:
![image](https://user-images.githubusercontent.com/22369834/36025607-ece10060-0d93-11e8-9d22-feed6d0e84a6.png)

Import task details last messages:
![image](https://user-images.githubusercontent.com/22369834/36025716-59bf8d50-0d94-11e8-876f-b0e0ff9f0aee.png)

Import task details - the important message location:
![image](https://user-images.githubusercontent.com/22369834/36026137-138849e2-0d96-11e8-9c68-2e38ce2c9520.png)

BTW [design](https://redhat.invisionapp.com/share/8QCOEVEY9) says there should be whole import task details available.

Tested with:
```
tendrl-monitoring-integration-1.5.5-20180208T071934.ef4055b.noarch
tendrl-commons-1.5.5-20180202T165022.2295e4e.noarch
tendrl-api-1.5.5-20180202T172550.51b6c71.noarch
tendrl-ui-1.5.5-20180207T051807.2334615.noarch
tendrl-grafana-plugins-1.5.5-20180202T171247.8435143.noarch
tendrl-notifier-1.5.5-20180202T172143.34fc113.noarch
tendrl-node-agent-1.5.5-20180202T165439.9e57adf.noarch
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-grafana-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-api-httpd-1.5.5-20180202T172550.51b6c71.noarch
```

**Comment by gnehapk** [comment]
@ltrilety As per the latest [design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/282443505), error modal has been removed. Error messages can be seen at import task detail view. Hence, closing this issue.
