### ISSUE TITLE
Brick Details accessed from Volumes page differ from design

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#816]
There are differences compared to the [design document for Brick Details accessed from Volumes page](https://redhat.invisionapp.com/share/XMAOW3UC5#/screens/221662356):

- [ ] In the design document is shown that for each brick is available `PID`. In current implementation there is `Actions` column.
- [ ] In the design document is filter for bricks. It is missing in current implementation.
- [ ] In the design document is navigation with: `Overview`, `Bricks`, `Rebalance`, `Tuning`, `Permissions`, `Configuration` and `Events`. It is missing in current implementation.
- [ ] In the design document are shown buttons: `Expand All` and `Collapse All`. They are missing in current implementation.

![0212_bricks2](https://user-images.githubusercontent.com/22369801/36103636-38277a4e-1010-11e8-8de3-2ca03da018ef.png)

Tested with:
```
tendrl-commons-1.5.5-20180208T071828.160b4d4.noarch
tendrl-api-1.5.5-20180202T172550.51b6c71.noarch
tendrl-ui-1.5.5-20180207T051807.2334615.noarch
tendrl-grafana-plugins-1.5.5-20180208T071934.ef4055b.noarch
tendrl-monitoring-integration-1.5.5-20180208T071934.ef4055b.noarch
tendrl-notifier-1.5.5-20180202T172143.34fc113.noarch
tendrl-node-agent-1.5.5-20180202T165439.9e57adf.noarch
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-grafana-selinux-1.5.4-20171212T044512.1f5eb63.noarch
tendrl-api-httpd-1.5.5-20180202T172550.51b6c71.noarch
```

**Comment by julienlim** [comment]
@fbalak @gnehapk @a2batic @mcarrano @mbukatov @nthomas-redhat @jjkabrown1

* Showing PID column is a nice-to-have but not mandatory (if there's not enough space to show it).
* Filter, Expand All, and Collapse All did not get implemented (as there was not enough time to get it done, and I'm not sure what the plan is for it).
* The other tabs mentioned (e.g. Overview, Rebalance, Tuning, Permissions, Configuration and Events) were deferred and not part of the MVP.  Note however that one can see Events for a given cluster (just not in context of the volume) from the left-hand navigation menu.

**Comment by gnehapk** [comment]
@fbalak Fixed in tendrl-ui-1.6.1-20180317T042235.84aac52.noarch.rpm build. Please verify and close the issue.

**Comment by fbalak** [comment]
Looks ok --> Closing.

Tested with:
```
tendrl-ansible-1.6.1-1.el7.centos.noarch
tendrl-api-1.6.2-1.el7.centos.noarch
tendrl-api-httpd-1.6.2-1.el7.centos.noarch
tendrl-commons-1.6.2-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.2-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.2-1.el7.centos.noarch
tendrl-node-agent-1.6.2-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.2-1.el7.centos.noarch
```

**Comment by gnehapk** [comment]
Since, two more filters "Utilization more than" and "Utilization less than" have to be implemented for volume's  brick detail view. Hence, opening this issue.

**Comment by julienlim** [comment]
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1559390.
