### ISSUE TITLE
View Details should provide Task Details

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#821]
`View Details` link should redirect to correct Task Details all the time - during the import cluster run and in the case when the run fails. There should not be the Import Failure Modal any more.

**Comment by julienlim** [comment]
Design may be found at https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738628.

@ltrilety @gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by gnehapk** [comment]
@ltrilety  Fixed with the milestone 3 release. Hence, closing it. Please open, if you see any issue,
,

**Comment by ltrilety** [comment]
Seems fixed, however I was not able to get proper failed import state, because of https://github.com/Tendrl/ui/issues/827#issuecomment-371427988

**Comment by ltrilety** [comment]
Tested with:
tendrl-ui-1.6.1-3.el7rhgs.noarch

looks fine
