### ISSUE TITLE
context switcher drop down list - missing id(s) for imported cluster(s)

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#825]
The context switcher drop down list doesn't show id for an imported cluster.
Moreover the details of the cluster cannot be opened by clicking on the cluster link right away, it starts to work after page reload.

Test scenario:
 1. Install tendrl and start to import an cluster
 2. Go to all-clusters page, wait till the import is finished
 3. Check context switcher menu, try to click on cluster link

Context switcher drop down menu
![image](https://user-images.githubusercontent.com/22369834/36369439-7fa884bc-155b-11e8-996e-59830d06f298.png)

Tested version:
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-ansible-1.5.4-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch

**Comment by ltrilety** [comment]
I checked the link and it cannot work as it is before page reload:
```
<a ng-class="{'unmanaged':(cluster.managed !== 'Yes')}" ui-sref="cluster-hosts({clusterId: cluster.name})" class="ng-binding" href="#/clusters">55b9d27c-0c64-4e45-aed2-064d3852760c</a>
```

After page reload:
```
<a ng-class="{'unmanaged':(cluster.managed !== 'Yes')}" ui-sref="cluster-hosts({clusterId: cluster.name})" class="ng-binding" href="#/cluster-hosts/55b9d27c-0c64-4e45-aed2-064d3852760c">55b9d27c-0c64-4e45-aed2-064d3852760c</a>
```

**Comment by gnehapk** [comment]
@ltrilety Can you please share the API response received for `/clusters` API.

**Comment by fbalak** [comment]
Link to imported cluster on `task` page generated right after import is also invalid. When I click on it I am not redirected. `View cluster details` link references to `hostname/TendrlModule`:
![0220_nolink](https://user-images.githubusercontent.com/22369801/36418784-29c77690-1630-11e8-8ead-e3329e005ab0.png)

Tested with:
```
tendrl-ansible-1.5.5-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
```

**Comment by fbalak** [comment]
Now I tested multiple imports with different clusters and it worked as expected. It was probably problem with browser settings.

**Comment by cybernth** [comment]
@gnehapk , can you close this as the fix is already merged

**Comment by gnehapk** [comment]
Closing this issue as the fix PR has been posted.
