### ISSUE TITLE
Unmanage cluster job can be initiated multiple times from UI

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ui#828]
When `unmanage` task is initiated from `All clusters` page then there is a dialog box with option `View Task Progress` or dismiss the dialog box by x button.
![0220_unmanage_dialog](https://user-images.githubusercontent.com/22369801/36422444-4b7a423e-163c-11e8-8fdb-62e4e2b56d10.png)
When x button is selected then the dialog box is closed and `unmanage` task is created but page does not change. User can try to create another `unmanage` job that fails. The page is updated after a few seconds (about 20 seconds) and new failing jobs are also created after a few seconds. UI should be updated after the first task is created.
![0220_more_jobs](https://user-images.githubusercontent.com/22369801/36422777-cdb3288c-163d-11e8-8b19-d46112915128.png)

Tested with:
```
tendrl-ansible-1.5.5-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
```

**Comment by a2batic** [comment]
@fbalak, Cluster list takes some time to reload after triggering unmanage as it will be updated only if API is sending correct data. If you click unmanage again before clusterlist is reloaded with latest API response, it will create a new job for unmanage.
Please share your API response after triggering unmanage operation.

**Comment by fbalak** [comment]
@a2batic You are right, `clusters` API call is sent periodically after a few seconds and the UI is correctly updated right after the response is obtained. Maybe it would be good to disable the `Unmanage` option in kebab menu after API call for unmanage is sent and update it with next successful `clusters` API response.

**Comment by cybernth** [comment]
But even in that case, user would be able to open another browser and try the same.
In any case I won't consider this as a deal breaker because backend handles this properly and fails the job

**Comment by gnehapk** [comment]
@fbalak  Unmanage option will be disabled in UI once user performs unmanage. It will be updated based on the next clusters API call values.

**Comment by gnehapk** [comment]
@fbalak  Fixed with the milestone 3 release. Hence, closing it. Please open, if you see any issue,
