### ISSUE TITLE
un-manage should be available when import fails

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#829]
If import fails in new build the import button remains active, but even if all issues are fixed a cluster cannot be imported again as it always fail and unmanage button is not available.

![import_fail](https://user-images.githubusercontent.com/22369834/36423629-0192c1e6-1641-11e8-8881-fd2514bd8eff.png)

Tested version:
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-ansible-1.5.5-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch

**Comment by cybernth** [comment]
@a2batic , can you close this issue if the fix is merged?

**Comment by ltrilety** [comment]
@nthomas-redhat I'll close the issue when I verify this issue, probably in next build.

**Comment by a2batic** [comment]
@ltrilety, this issue has been fixed with the latest master (tendrl-ui-1.6.0-20180223T121254.729004b.noarch.rpm). Please verify.

**Comment by ltrilety** [comment]
I was not able to get proper failed import state because of https://github.com/Tendrl/ui/issues/827#issuecomment-371427988

**Comment by ltrilety** [comment]
Tested with:
tendrl-ui-1.6.1-3.el7rhgs.noarch

looks fine
