### ISSUE TITLE
Tasks list shows lot of overlaps if no of tasks is huge in UI

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ui#833]
When the list of tasks is huge there is a overlap seen in UI as below

![screenshot from 2018-02-22 08-34-42](https://user-images.githubusercontent.com/6771252/36518202-8c4c9be8-17ab-11e8-87bd-e32af9daa27a.png)

**Comment by shtripat** [comment]
@gnehapk @a2batic ^^^

**Comment by gnehapk** [comment]
@shtripat Issue has been fixed, Please verify it and close.
