### ISSUE TITLE
No volumes after successful import, unmanage, then import

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#837]
Release: Tendrl 1.6.0 - latest master (as of Feb 22 2018)

I imported successfully a cluster, and then unmanaged it successfully, and then imported again the same cluster.  After the unmanage, the Volumes list for the cluster is empty.

Screenshot from first import:
![screen shot 2018-02-22 at 2 16 57 pm](https://user-images.githubusercontent.com/5589919/36560874-094ec33a-17e0-11e8-8e2e-e7da28745137.png)

Screenshot from second import (after unmanage):
![screen shot 2018-02-22 at 2 49 22 pm](https://user-images.githubusercontent.com/5589919/36560883-163c7a06-17e0-11e8-9778-e0779c5db848.png)

Task List:
![screen shot 2018-02-22 at 2 34 08 pm](https://user-images.githubusercontent.com/5589919/36560897-212720b0-17e0-11e8-8c02-056384b7d424.png)

@gnehapk @a2batic @r0h4n @nthomas-redhat @Tendrl/qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim can you please share the API response for `/clusters/{cluster_id}/volumes`

**Comment by julienlim** [comment]
```
# curl -XGET  -H "Authorization: Bearer 3e1acf6780c4d1834702bc74fe1afaeb0419311483bae437d800468210c02a90" http://127.0.0.1/api/1.0/clusters/44f8f6f3-a103-437b-a3e1-701db25c5382/volumes

{"volumes":[]}
```

@gnehapk

**Comment by gnehapk** [comment]
@julienlim Since API is returning empty response, UI is not displaying any volume. 
@r0h4n @nthomas-redhat @shtripat @GowthamShanmugam Please check.

**Comment by shtripat** [comment]
@gnehapk There is a change now in import cluster which would mark the import job finished only when all the gluster nodes report as first sync done. This should resolve the issue.

[1] https://github.com/Tendrl/gluster-integration/pull/565
[2] https://github.com/Tendrl/commons/pull/827

**Comment by gnehapk** [comment]
@julienlim Fixed with the milestone 3 release. Hence, closing it. Please open, if you see any issue,
