### ISSUE TITLE
Users submenu

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#839]
The `title` and `id` of submenu where `Users` link is located is `notifications` as of now. 
```
<a data-toggle="dropdown" class="dropdown-toggle nav-item-iconic" href="" data-template="" data-animation="am-fade-and-slide-top" bs-dropdown="dropdown" title="Notifications" id="notifications" aria-expanded="false">
```
The title and id should be something else as for sure this is not just about notifications. It should be e.g. `User Management` as `title` and `usermanagement` as `id`.

BTW The `id` is not unique as the same one has following alerts menu.

Tested version:
tendrl-ui-1.6.0-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@ltrilety Can you please close this issue, if done.

**Comment by ltrilety** [comment]
Fixed in:
tendrl-ui-1.6.1-1.el7.centos.noarch
