### ISSUE TITLE
drop-down menu aria-labelledby

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#840]
There are two drop-down menus with the same label. User management one with `Users` link and the one for user actions like `My Settings` and `Logout`.
```
<ul class="dropdown-menu" role="menu" aria-labelledby="usermenu">
```

Such duplicates complicate a test automation a little.

Tested version:
tendrl-ui-1.6.0-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@ltrilety Can you please close this issue, if done.

**Comment by ltrilety** [comment]
Fixed in:
tendrl-ui-1.6.1-1.el7.centos.noarch
