### ISSUE TITLE
Unmanage Cluster failed: Unusual UI behavior

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#844]
Unmanage cluster failed, and I'm observing some unusual behavior:

(1) Instead of showing the task details for the Unmanage cluster, it shows me an error message that is truncated.  Message should wordwrap if needed and not be truncated. 

(2) The Modal says "Import Cluster" vs. "Unmanage Cluster" which is surprising since user is trying to Unmanage the cluster.

<img width="1267" alt="screen shot 2018-02-27 at 3 30 15 pm" src="https://user-images.githubusercontent.com/5589919/36795090-1b34c84e-1c70-11e8-9b54-32c4c727580f.png">

<img width="1280" alt="screen shot 2018-02-27 at 11 48 29 am" src="https://user-images.githubusercontent.com/5589919/36741914-5b4940d4-1bb4-11e8-8d4f-8162f4bf1cac.png">

@gnehapk @Tendrl/qe @a2batic @shtripat

**Comment by gnehapk** [comment]
@julienlim Fixed with the milestone 3 release. Hence, closing it. Please open, if you see any issue,
