### ISSUE TITLE
Task status not updated for a long time

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ui#852]
1. trigger import cluster
2. Go to task details page
3. Task status is displayed as 'New', even after the task is in progress and task details are getting updated on the screen

**Comment by gnehapk** [comment]
@nthomas-redhat Can you please share the API response of `/jobs/{jobId}/status` received

**Comment by gnehapk** [comment]
@nthomas-redhat Fixed with the milestone 3 release. Closing it.
