### ISSUE TITLE
Warning and errors in firefox browser console

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#861]
I have a lot of warnings and errors in my browser console, when I open tendrl UI and log in.

E.g.

message | css location
--------- | ------------
Unknown property ‘size’.  Declaration dropped.  | main.css:1:414
Error in parsing value for ‘display’.  Declaration dropped. | main.css:1:779
Error in parsing value for ‘-webkit-box-pack’.  Declaration dropped. | main.css:1:2691
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector. | libraries.css:5:1401
downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:3) source: http://<tendrl_server_hostname>/fonts/OpenSans-Regular-webfont.woff2 | libraries.css:1:515

I have seen those errors and warnings with:
Firefox Quantum 58.0.2 (64-bit)
tendrl-ui-1.6.1-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@ltrilety Myself and @a2batic, we both tried and this error is not reproducible. Attaching screenshot for the same.
![screenshot from 2018-03-12 10-39-04](https://user-images.githubusercontent.com/5517376/37266661-c51dfd1a-25e1-11e8-8d18-f49bfd1633f3.png)

**Comment by ltrilety** [comment]
@gnehapk yeah, you 're right. I found that too, when I try it in Fedora. The reason of those errors is that I run the Firefox on my mac machine.

**Comment by julienlim** [comment]
@ltrilety @gnehapk @a2batic I tried it with Firefox on my Mac, and I didn't see those errors.  For the OpenSans error, you may need to load the font on your Mac.

**Comment by ltrilety** [comment]
@julienlim you're right last time I checked the errors were gone.
Where the version I was using:
tendrl-ui-1.6.1-3.el7rhgs.noarch

That said I am closing this issue.
