### ISSUE TITLE
Breadcrumbs appearing when not needed, and overly long breadcrumbs in detail pages

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#864]
In tendrl 1.6.1 release, I'm observing the following when I am looking at a given cluster:
* breadcrumbs on the hosts, volumes, tasks, and events pages (from left-nav) when not needed and not specified in design [Hosts List](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/283620800), [Volumes List](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738623), [Tasks List](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/251481034), and [Events List](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738616)

<img width="1192" alt="screen shot 2018-03-09 at 1 01 00 pm" src="https://user-images.githubusercontent.com/5589919/37223560-ec3a0be0-239e-11e8-83b5-e1e28120ab90.png">

* overly long breadcrumbs for the details pages (Volume details and Host details), where it should be "ClusterName > VolumeName" for volume details and "ClusterName > Hostname" for host details.  See [Volume details design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738621) for additional information.

<img width="1181" alt="screen shot 2018-03-09 at 1 03 24 pm" src="https://user-images.githubusercontent.com/5589919/37223598-0779105e-239f-11e8-82e3-a8d057aeb7e3.png">

@gnehapk @a2batic @Tendrl/qe

**Comment by a2batic** [comment]
@julienlim @mcarrano, I have a doubt about design[1]. There is a hyperlink on the clustername for all breadcrumbs. This hyperlink links to which view ?

[1] https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/284143399

**Comment by mcarrano** [comment]
@a2batic This should take you back to the parent list where that item lives, either the Host list or the Volume list to that cluster. Does that make sense?

**Comment by a2batic** [comment]
@mcarrano, yes, that make sense. Thankyou.
