### ISSUE TITLE
Host details issues

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#865]
In tendrl 1.6.1, for the host details that show the bricks for a given node in a cluster, there are a few things that need to be addressed:

(1) breadcrumb overly long -- see https://github.com/Tendrl/ui/issues/864 for more details
(2) the brick path should be shown before the volume name
(3) for truncated volume name, user should be able to hover to see what the full name is (like on the brick path)
(4) Avoid truncating text (including utilization) as much as possible by allotting more space to the columns as needed, whenever possible

<img width="1192" alt="screen shot 2018-03-09 at 1 25 32 pm" src="https://user-images.githubusercontent.com/5589919/37230421-7471f926-23b5-11e8-9ae1-b7b19a99698c.png">

<img width="1042" alt="screen shot 2018-03-09 at 4 18 23 pm" src="https://user-images.githubusercontent.com/5589919/37230452-8dcb3518-23b5-11e8-8d4d-ce3c7c998fd5.png">

See [Host Detail design](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/284143399_Cluster_Details-Hosts-Bricks) for further information.

@gnehapk @a2batic @Tendrl/qe @mcarrano

**Comment by gnehapk** [comment]
@julienlim  Fixed in tendrl-ui-1.6.1-20180317T042235.84aac52.noarch.rpm build. Please verify and close the issue.
