### ISSUE TITLE
Filtering in the Host Details not working consistently

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#866]
I've posted a series of screenshots to show the filtering in the host details that shows some unexpected behavior:

<img width="1206" alt="screen shot 2018-03-09 at 4 42 32 pm" src="https://user-images.githubusercontent.com/5589919/37231381-f61e0c46-23b8-11e8-8740-73f2cc18b2c0.png">

<img width="1207" alt="screen shot 2018-03-09 at 4 44 01 pm" src="https://user-images.githubusercontent.com/5589919/37231417-2503bbfa-23b9-11e8-9857-b3e3dfbd4496.png">

<img width="1265" alt="screen shot 2018-03-09 at 4 37 12 pm" src="https://user-images.githubusercontent.com/5589919/37231453-4472cf30-23b9-11e8-9425-4588cad90ad4.png">

@gnehapk @a2batic @Tendrl/qe @mcarrano

**Comment by a2batic** [comment]
@julienlim, it seems to be patternfly bug.
The filter component[1], shows similar behavior.

[1] https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter

**Comment by gnehapk** [comment]
@julienlim In the filter component,  multiple 'text' filter values are AND'ed together. So its basically searching for records which have both `Brick Path: 1` and `Brick Path: 49152`, which doesn't match with any record. Hence, its showing you no results.

**Comment by julienlim** [comment]
@gnehapk I was expecting an OR behavior vs. an AND behavior so was confused by the results.

@mcarrano From filtering perspective, do you expect OR or AND behavior?

**Comment by mcarrano** [comment]
@julienlim @gnehapk Should be an AND behavior. That's how it's defined in PatternFly. So the idea is that you incrementally narrow the results list as you apply more filters.

**Comment by gnehapk** [comment]
@julienlim @mcarrano As the filter is working as expected. Hence closing the issue.

**Comment by julienlim** [comment]
@gnehapk @mcarrano I'm not sure that the filter is working correctly as '1' is valid and so is '4912', so that means it should return the 2nd row and not null/no rows.
