### ISSUE TITLE
indices in case of clear alert 

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#867]
Indices for alerts are decreased when a clear alert comes. That's fine as long as the related alert is present however in some strange situation it could happen that the alert does not exist. That leads to state when the number of alerts could be minus number.

BTW In my case I just imported a cluster which looks like 'ready to use' before the import was altogether completed.

![alert_nr](https://user-images.githubusercontent.com/22369834/37276278-9178984e-25e1-11e8-9f10-4c69bb1cdbb7.png)

Tendrl version:
tendrl-commons-1.6.1-1.el7.centos.noarch
tendrl-api-1.6.1-1.el7.centos.noarch
tendrl-ui-1.6.1-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-ansible-1.6.1-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.1-1.el7.centos.noarch
tendrl-api-httpd-1.6.1-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-grafana-plugins-1.6.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.6.1-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@ltrilety Please share the `/clusters` API response.

**Comment by ltrilety** [comment]
@gnehapk you're most probably right with your suspicion that the issue is not on UI side. Unfortunately I don't have that response anymore, as of now API is telling me I have 2 alerts for the clusters whilst all other indices says zero. Feel free to move this issue where it belongs.

**Comment by GowthamShanmugam** [comment]
PR is under review, Every gluster-integration sync we are recalculating alert count and updating. Please verify and close this issue https://github.com/Tendrl/gluster-integration/pull/599

**Comment by gnehapk** [comment]
@GowthamShanmugam Please close this issue if fixed.

**Comment by GowthamShanmugam** [comment]
This issue is fixed, We are now calculating alert count in each gluster-integration sync,  So the alert count always matches with a number of alerts.  

@gnehapk we can close this issue. @ltrilety please reopen this issue if it is reprodusable with the latest master.

**Comment by GowthamShanmugam** [comment]
This issue is fixed in PR: https://github.com/Tendrl/gluster-integration/pull/599
