### ISSUE TITLE
Cluster detail link

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#869]
The details of the cluster cannot be opened by clicking on the cluster link right away, it starts to work after page reload.

Test scenario:

 1. Install tendrl and start to import an cluster
 2. Go to all-clusters page, wait till the import is finished
 3. Try to click on the cluster id in the clusters list (not in the context switcher drop-down menu)

![cluster_link](https://user-images.githubusercontent.com/22369834/37276902-721759f2-25e3-11e8-9495-ac2cf5f7e076.png)

Tendrl version:
tendrl-ui-1.6.1-1.el7.centos.noarch

**Comment by gnehapk** [comment]
@ltrilety  Fixed in tendrl-ui-1.6.1-20180317T042235.84aac52.noarch.rpm build. Please verify and close the issue.
