### ISSUE TITLE
Alert count objects variable warning_count is renamed to alert_count

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/ui#872]
Currently, UI is looking for a field "warning_count" from API response to the display alert counts. But "warning_count" is renamed to "alert_count".  So to display alert count UI need to change this filed name.

changes required in:
    1. cluster alert count
    2. node wise alert count
    3. volume alert count

**Comment by gnehapk** [comment]
@GowthamShanmugam  Fixed in tendrl-ui-1.6.1-20180317T042235.84aac52.noarch.rpm build. Please verify.

**Comment by GowthamShanmugam** [comment]
Verified, i can see it in UI
