### ISSUE TITLE
Enable/Disable profiling at cluster level reset the flag to 'leave-as-is'

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ui#879]
Etcd after enable/disable profiling
{
"key": "/clusters/1d3929ec-f466-4957-8183-83e80771a9ca/volume_profiling_flag",
"value": "leave-as-is",
"modifiedIndex": 13645,
"createdIndex": 13645
},

UI seems to be sending the incorrect payload:
{enable_volume_profiling: "enable"}

should it be "Cluster.volume_profiling_flag ??

**Comment by cybernth** [comment]
@shtripat , @shirshendu

**Comment by shtripat** [comment]
Now backend provides cluster level flow for enable/disable volume profiling for all the underlying volumes. UI needs changes to invoke the API for the same as a flow and show the flow details as usual cluster level flows. The input data for the same would be `Cluster.volume_profiling_flag` and values can be set as `enable` or `disable`.

[1] https://github.com/Tendrl/gluster-integration/pull/593

**Comment by shtripat** [comment]
@mbukatov @julienlim @nthomas-redhat once this job is in progress , the progress can be seen at cluster level using  `View Details` option. After completion of the flow, it would need a sync to reflect all the details at volume and cluster level properly.

**Comment by gnehapk** [comment]
@mcarrano @julienlim Please update the UX of cluster list view to display the `Pending` state for Volume Profiling column, if the job for enable/disable volume profile task in in progress.

**Comment by mcarrano** [comment]
@gnehapk We have added this to the Clusters list here: https://redhat.invisionapp.com/share/HVGA7O575AZ#/244738628_Clusters

Basically, when the task is in progress, the state should change to Pending and be linked to the task details. Let us know if you have any questions.

**Comment by gnehapk** [comment]
@nthomas-redhat Fixed. Please verify.
