### ISSUE TITLE
UI should disable the button when button or link is clicked for profiling

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ui#890]
UI needs to disable the button when the Profiling job is in progress, right now a person can fire multiple jobs to enable or disable the profiling from UI at a time when a job is already running.

**Comment by gnehapk** [comment]
PR - https://github.com/Tendrl/ui/pull/889

**Comment by gnehapk** [comment]
If a user clicked on enable/disable profiling link or button on cluster list or volume list view, UI disabled the link/button and if the API failed for it, it will enabled again. Once next API call response received, link/button will be enabled/disabled based on the API response. If user refreshes the view, again link/button will be enabled/disabled based on the API response

**Comment by gnehapk** [comment]
Bugzilla - https://bugzilla.redhat.com/show_bug.cgi?id=1560879

**Comment by gnehapk** [comment]
@cloudbehl Fixed. Please verify.
