### ISSUE TITLE
Style of text fields is not unified

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#892]
Style of 'text fields' is not unified.
In most cases we use something like "Pascal Case", in other words all initial characters are capitals like 'Clusters', 'Volume Profiling', 'Ready to Use' ...
But there's some exceptions to this rule like 'UP', 'DOWN' as status for hosts, 'Ready to import' and 'unmanage the cluster'.
We should correct those exceptions to use the same style as everything else.

**Comment by gnehapk** [comment]
@ltrilety Sine the PR is merged, closing this issue.
