### ISSUE TITLE
'Unmanage' not present for misconfigured cluster

### ISSUE THREAD

**Issue by a2batic** [Tendrl/ui#946]

**Comment by a2batic** [comment]
@julienlim, should Unmanage be available for misconfigured clusters ?

**Comment by julienlim** [comment]
@a2batic  Unmanage should be available for misconfigured clusters.

**Comment by gnehapk** [comment]
@a2batic Is this fixed? Please close it if solved.

**Comment by a2batic** [comment]
@gnehapk Yeah, Its fixed.
