### ISSUE TITLE
If volume.profiling_enabled in [None, ""], UI should report the value as `Unknown`

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ui#959]
In link with https://bugzilla.redhat.com/1578333 the volumes with empty value for `profiling_enabled` flag, should be showing `Unknown` for `Volume profiling` value in UI. This is required for glusterfs version which dont support profiling data in get-state output for individual volumes.

If volume.profiling_enabled == 'yes' set as `Enabled` in UI
If volume.profiling_enabled == 'no' set as `Disabled` in UI

**Comment by shtripat** [comment]
@gnehapk ^^^

**Comment by gnehapk** [comment]
As per discussion with @shtripat, this changes needs to be done for both cluster and volume list views. 
For cluster list view, both Enable and Disable profiling action should be allowed if `Volume Profiling`  is `Unknown` but for volume list view, both Enable and Disable profiling action should be disabled if `Volume Profiling`  is `Unknown`.
